### ISSUE TITLE
Server Error on disconnecting a client

### ISSUE THREAD

**Issue by Sajjad2678** [Cysharp/MagicOnion#100]
What is the correct way to disconnect a client from the server without any error log at server side with StreamingHub?  because when I leave a room an error created in the server. but the server, not crash
i used this code for disconnect a client from the server :
`await client.LeaveAsync();`
`await client.CloseChannelAsync();`
`await channel.ShutdownAsync();`
client is an instance from GamingHubClient and channel is a instance of Channel class.
also  i use .net 4.7.1 
Error in the server :
![error](https://user-images.githubusercontent.com/12018364/53862048-3f215100-3ffb-11e9-80b4-e5864be83ba4.jpg)

**Comment by neuecc** [comment]
the log of this message is harmless.
current gRPC(C#) shows some unnecessary system log.
