### ISSUE TITLE
Question: Can MagicOnion use Sockets? If so, can it be used alongside HTTP2?

### ISSUE THREAD

**Issue by snarlynarwhal** [Cysharp/MagicOnion#101]
I want to write a cross-platform multiplayer game. I'd prefer to use regular tcp sockets on desktop and mobile. We do this for a current project and it works great, but want to use MagicOnion for our next project. Is this possible?

I can't edit the title, but I meant "alongside http2."

**Comment by neuecc** [comment]
> alongside http2

yes.

**Comment by snarlynarwhal** [comment]
Okay great. I could not find this in the doc, so sorry if it's there and I missed it, but:

How can you configure the transport layer(s) in MagicOnion?

**Comment by neuecc** [comment]
Currently everything completely dependent on gRPC.
