### ISSUE TITLE
IDisposable support for service classes and StreamingHub

### ISSUE THREAD

**Issue by andrzej-lenart** [Cysharp/MagicOnion#102]
Hi,

Thank you very much for this great library! I would like to ask about supporting IDisposable for classes that inherit from ServiceBase or StreamingHub. 

From what I have managed to deduce, lifecycle of the class that inherit from ServiceBase is as follows:
- it is created using parametless constructor 
- method is called
- eventually it is garbage collected

Could you advise please where is a good place for releasing resources?

**Comment by neuecc** [comment]
Thanks!

I'm trying to create servcie class instance integrated with DI. #64
About lifecycle, will solve in DI Container.

**Comment by neuecc** [comment]
`1.2.0` supports DI.
