### ISSUE TITLE
How to make it work on WebGL?

### ISSUE THREAD

**Issue by Serepa** [Cysharp/MagicOnion#103]
Is it possible to use MagicOnion on WebGL? Did you try it? If yes, how to make it work? Now gRPC usage crashes WebGL build.

**Comment by neuecc** [comment]
Currentl MagicOnion is depenent gRPC Core(it is C Native Library) so you can not use on WebGL.
If server is Unary, you can use HttpGateway and HTTP/1 client instead of MagicOnion Client.
If server is StreamingHub, I'm investigating WebSocket Gateway.

**Comment by mwegner** [comment]
There is a pure Python implementation of gRPC out there: https://github.com/vmagamedov/grpclib

I've never looked at the deep internals of gRPC, so I don't know if such a thing is possible with C#, or how much of gRPC's speed comes from its C implementation.

It would be great to see a pure C# implementation, if such a thing is ever possible or practical.  Relying on gRPC support for a platform is a problem, especially with Unity and console development (even with tvOS there are some SSL issues that appear between the iOS version, for instance).

**Comment by neuecc** [comment]
Pure C# gRPC project is now active in here https://github.com/grpc/grpc-dotnet/

> We plan to provide a managed .NET Core client as well (possibly with limited feature set at first)

If it comes, works well on all platforms.
