### ISSUE TITLE
Room Based Game

### ISSUE THREAD

**Issue by khaaaniii** [Cysharp/MagicOnion#106]
Hi.
Can this package use for room based games?
I used UNET to do my stuff but now its going to be deprecated!
i checked this package and i want to know can i use this package for create a multiplayer roombased game that if a room is full create another room and so on !
any suggestion ?
Best regards

**Comment by neuecc** [comment]
`StreamingHub.Group` is support for create room based game.

**Comment by khaaaniii** [comment]
is there anyway for StreamingHub.Group to limit number of players in a room and prevent joining the room if the game in room has been started ?

**Comment by neuecc** [comment]
Group has `TryAddAsync(string groupName, int incluciveLimitCount, bool createIfEmpty)` method.
