### ISSUE TITLE
Is There any simple example for using streaming hub?

### ISSUE THREAD

**Issue by dhaniYanuar** [Cysharp/MagicOnion#108]
I am trying to use streaming hub method, but i confuse to create structure for client in streaming hub method. i already search in documentation but there is no example for client in streaming hub method.

**Comment by neuecc** [comment]
Will SampleProject help for you?
https://github.com/Cysharp/MagicOnion/tree/master/samples

**Comment by dhaniYanuar** [comment]
@neuecc thank you very much, i will use it for my study.
