### ISSUE TITLE
Timer in StreamingHub

### ISSUE THREAD

**Issue by JauntyGame** [Cysharp/MagicOnion#111]
@neuecc thanks for your great framework!
I am creating turn-based game, StreamingHub is exact what I need. Just have 2 questions:
User will have 30 seconds to do turn, and if he missed his time, server should do turn for this user by itself. 
1. Where should I place the timer and logic that will do turn for that user?
2. How can I loop through the users when they will do theirs turn to inform next user that his turn has started?

**Comment by neuecc** [comment]
1.
If trigger of timer is user action, invoke `async Task Timer() { await Task.Delay(TimeSpan.FromSeconds(30)); }` and ignore result Task(fire-and-forget pattern) and pass with cancellation token for operation succeed.

2.
Broadcast event(next userId) to all(or target) user?

**Comment by JauntyGame** [comment]
1. Trigger of timer should be server action. Because user can do logout, or got disconnected, and server still should do turns for that user. Also if all users from game table will got disconnected, server also should do turns (someone can be reconnected, and I should restore his playing state).
2. Sounds good!
