### ISSUE TITLE
can we connect it with java script?

### ISSUE THREAD

**Issue by dhaniYanuar** [Cysharp/MagicOnion#113]
we know that MagicOnion is an Realtime Network Engine like SignalR, Socket.io and RPC-Web API Framework like any web-framework. but can we use it in java script?, because i want to make a game client from unity and phaser, and connect it with magic onion server.

**Comment by neuecc** [comment]
This will done when WebSocketGateway is finished.
https://github.com/Cysharp/MagicOnion/issues/60

**Comment by dhaniYanuar** [comment]
thank you @neuecc you did really a great job.
