### ISSUE TITLE
new sample application is freeze in Unity

### ISSUE THREAD

**Issue by kubota62** [Cysharp/MagicOnion#114]
sample ReadMe : How to run the app
1 : Launch ChatApp.Server from VisualStudio.
2 : Run ChatScene from UnityEditor.
run sample chat! 

↓ after
3 : Stop Unity
4 : Run Unity → Freeze!

5 : shotdown server process → revive Unity!

in Unity 2018.3.12f1

please help...

**Comment by neuecc** [comment]
thanks, we'll investigate it.

**Comment by vivilily** [comment]
It was freezing because we did not release Hub and Channel.
We have modified the Sample application and updated the README, so please check.

Thank you for the report.
