### ISSUE TITLE
Client Running Error Reporting

### ISSUE THREAD

**Issue by landonzeng** [Cysharp/MagicOnion#117]
I put the implementation of the service interface in netstandard separately, and then the server directly references it and runs it. Client will report errors when requesting，Error Info：
`Unhandled Exception: System.AggregateException: One or more errors occurred. (Status(StatusCode=Unimplemented, Detail="")) ---> Grpc.Core.RpcException: Status(StatusCode=Unimplemented, Detail="")
   at MagicOnion.UnaryResult`1.Deserialize()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Client.Program.Main(String[] args) in F:\MyDemoProject\MagicOnionProject\Client\Program.cs:line 19`

The structure of my project is as follows:
![QQ截图20190412163015](https://user-images.githubusercontent.com/7336781/56023415-5bbe5080-5d40-11e9-9f17-dc154f553145.png)
![2](https://user-images.githubusercontent.com/7336781/56023433-637df500-5d40-11e9-9b4f-b7bf6c9ea773.png)

**Comment by neuecc** [comment]
Unimplemented is like 404.

Could you show all codes?(Client/Program.cs, Interface/ITest.cs, Servers/Program.cs, Services/Test.cs )

**Comment by landonzeng** [comment]
Client/Program.c
`using Grpc.Core;
using Interface;
using MagicOnion.Client;
using System;

namespace Client
{
    class Program
    {
        static void Main(string[] args)
        {

            // 然后你就可以根据IP和端口拿到对于的服务
            var channel = new Channel("127.0.0.1", 9990, ChannelCredentials.Insecure);


            var client = MagicOnionClient.Create<ITest>(channel);
            // 调用
            var result = client.SumAsync(500, 200).ResponseAsync.Result;

            Console.WriteLine("Client Received:" + result);


            Console.ReadLine();
        }
    }
}
`

Interface/ITest.cs:
`using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using MagicOnion;

namespace Interface
{
    // 定义接口和方法，IService，UnaryResult是MagicOnion自带
    public interface ITest : IService<ITest>
    {
        UnaryResult<string> SumAsync(int x, int y);
    }
}
`

Servers/Program.cs:
`using Grpc.Core;
using Grpc.Core.Logging;
using MagicOnion.Server;
using System;

namespace Servers
{
    class Program
    {
        static void Main(string[] args)
        {
            GrpcEnvironment.SetLogger(new ConsoleLogger());

            //设置请求记录输出
            MagicOnionServiceDefinition service = MagicOnionEngine.BuildServerServiceDefinition(new MagicOnionOptions(true)
            {
                MagicOnionLogger = new MagicOnionLogToGrpcLogger()
            });

            var server = new Server
            {
                Services = { service },
                Ports = { new ServerPort("127.0.0.1", 9990, ServerCredentials.Insecure) }
            };

            // launch gRPC Server.
            server.Start();

            Console.WriteLine($"Server IP:127.0.0.1  Prot:9990");
            Console.ReadLine();
        }
    }
}
`

Services/Test.cs :
`using Interface;
using MagicOnion;
using MagicOnion.Server;
using System.Threading.Tasks;

namespace Services
{
    // 实现接口，ServiceBase是MagicOnion自带
    public class Test : ServiceBase<ITest>, ITest
    {
        public UnaryResult<string> SumAsync(int x, int y)
        {
            Logger.Debug($"Received:{x}, {y}");

            return  UnaryResult((x + y).ToString());
        }
    }
}
`

**Comment by neuecc** [comment]
thanks, I'll investigate it.

**Comment by vivilily** [comment]
@landonzeng
`Grpc.Core.RpcException: 'Status (StatusCode = Unimplemented, Detail = "")'` error is
It occurs because the corresponding method is not registered in `MethodHandlers` property that `MagicOnionServiceDefinitiong` of return value of `MagicOnionEngine.BuildServerServiceDefinition` has.

Assembliy obtained by `AppDomain.CurrentDomain.GetAssemblies` is registered by default.
The Test class is not used in the Servers project, it is stripped and it is excluded from `AppDomain.CurrentDomain.GetAssemblies`.

In this case, you can solve it by registering Assembly manually.
```csharp
MagicOnionServiceDefinition service = MagicOnionEngine.BuildServerServiceDefinition(
    new[] {typeof(Test).Assembly },  // Manually add
    new MagicOnionOptions(true)
    {
        MagicOnionLogger = new MagicOnionLogToGrpcLogger()
    }
);
```

Thank you for confirmation.

**Comment by landonzeng** [comment]
@vivilily Thanks!
