### ISSUE TITLE
Using AppService interface in place of Grpc

### ISSUE THREAD

**Issue by Noemata** [Cysharp/MagicOnion#118]
I was wondering if you had any thoughts on what would be involved using the UWP AppService interface in place of Grpc Sockets.  I'm looking for the shortest path to get this done.  Does it make more sense to add another "socket" type to Grpc then simulate a socket like connection with AppService, or would it be simpler to create an alternate wrapper that consumes MagicOnion in a manner similar to Grpc.  The part that worries me the most is the Protobuf dependency of Grpc.

Why do this?  Because AppService is much faster and avoids security limitations for UWP Apps on the same device.

Your thoughts?

**Comment by neuecc** [comment]
I think UWP AppService is like Unix domain socket.
Some gRPC implementations can select TCP or Unix domain socket, but has no AppService.
So unfortunately gRPC/MagicOnion have no features and maybe can not add it.
