### ISSUE TITLE
Support UnityPackageManager

### ISSUE THREAD

**Issue by neuecc** [Cysharp/MagicOnion#123]
https://blogs.unity3d.com/2019/04/16/introducing-unity-2019-1/#pacman

> You can now visualize your packages and core dependencies in the Editor, install a package directly from a GitHub repository, and manage private and Unity-hosted registries side by side. This release also includes support for Assembly definition references (see the Version Defines section). Join the discussion on the Unity Package Manager forum and check the 2019.1 manual for more information.

**Comment by longfin** [comment]
Is this issue resolved? or, is it canceled? IMHO, it would be nice if MagicOnion could be installed through UPM.
