### ISSUE TITLE
C# UWP Release build fails due to: warning ILT0028

### ISSUE THREAD

**Issue by Noemata** [Cysharp/MagicOnion#125]
When creating a Release build of a UWP application that uses the C# bindings for grpc, the following warning is initially issued:

X:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\2.2.3\tools\Microsoft.NetNative.targets(801,5): warning : ILTransform : warning ILT0028: Found native library 'X:\xxx\obj\x86\Release\ilc\in\grpc_csharp_ext.x64.dll' with unexpected CPU architecture 'amd64', while the current build target architecture is set to 'x86'. Your application may fail to launch. Please make sure to build your application with the matching CPU architecture.

This warning eventually manifests in a failure to build.

Something about the way the nuget package is configured is causing the wrong architecture to be selected for both x86 and x64 architecture Release builds. They appear to be inverted, so when building for x86 Release, grpc_csharp_ext.x64.dll is selected and when building for x64 Release, grpc_csharp_ext.x86.dll is selected.
Debug builds are correct.

This problem persists up to v1.20 of grpc.

**Comment by neuecc** [comment]
maybe requires this fix
https://github.com/tarukosu/grpc/commit/26584b249e360f28504c4f0aadd5f9ab02826e1e
( @tarukosu 's great hack)

**Comment by Noemata** [comment]
The @tarukosu hack appears to be a runtime change that alters the way DLLs get loaded at runtime.  The problem I'm describing happens during build resulting in the selection of the wrong DLL to satisfy dynalink imports.  Also of note is the fact that Debug builds without issue, so the @tarukosu change does not explain why the Debug build selects the correct DLL during build.  Selection of the wrong DLL only happens for a Release build.  Given Microsoft.NetNative.targets throws up the warning, it's some sort of targeting problem that is incorrectly inverted (x86 when it should be x64/x64 when it should be x86) for a Release build.

**Comment by Noemata** [comment]
Looking at this further, it appears that Debug does not go through the dynalink resolution phase during build, and is able to select the correct grpc_csharp_ext DLL at runtime.  Whereas there is some sort of architecture inversion problem with the selected grpc_csharp_ext DLL when building for Release.  The mechanism that's used to select the correct architecture for a Release build needs fixing.  I was not able to find any issue with the way Grpc targets are set within its nuget package.  This is starting to look like yet another .Net Native build bug.

**Comment by Noemata** [comment]
I was able to work around the nuget package issue related to the wrong grpc_csharp_ext DLL being selected.  Unfortunately, that did not resolve the many "MCG0007: Unresolved P/Invoke method" warnings which cause the build to ultimately fail with a "ILT0014: Failed to compile interop source code." error.

It appears this form of DllImport is a problem for a UWP build (example):

            [DllImport(ImportName)]
            public static extern void grpcsharp_shutdown();

**Comment by Noemata** [comment]
Could you please explain how the Http2Client reference is at all related to the DLL import bug?

**Comment by neuecc** [comment]
> Could you please explain how the Http2Client reference is at all related to the DLL import bug?

Pure C# HttpClient is does not import C library.
