### ISSUE TITLE
How to connect server use StreamingHub in LAN network

### ISSUE THREAD

**Issue by JoeCoderJC** [Cysharp/MagicOnion#126]

**Comment by neuecc** [comment]
Is in LAN special?
You can create `new Channel("local ip");`

**Comment by JoeCoderJC** [comment]
![image](https://user-images.githubusercontent.com/37283803/56489713-d5a6c480-650c-11e9-83d0-ff7cd2722244.png)

**Comment by JoeCoderJC** [comment]
please give sample to me. I have deployed but failed 
![image](https://user-images.githubusercontent.com/37283803/56489884-81501480-650d-11e9-9766-031cad971186.png)

**Comment by JoeCoderJC** [comment]
![image](https://user-images.githubusercontent.com/37283803/56490001-e0ae2480-650d-11e9-84f9-4245496a2262.png)

**Comment by JoeCoderJC** [comment]
![image](https://user-images.githubusercontent.com/37283803/56490026-f02d6d80-650d-11e9-94cd-b8ab839d931e.png)

**Comment by JoeCoderJC** [comment]
I Can't connect to Grpc server running on docker for windows. please help me. thank you

**Comment by JoeCoderJC** [comment]
RpcException: Status(StatusCode=Unknown, Detail="Stream removed")

**Comment by carrasco39** [comment]
@JoeCoderJC what was your solution? Did the containerization work?
