### ISSUE TITLE
How do I know if a client connection is successful

### ISSUE THREAD

**Issue by leoterry-ulrica** [Cysharp/MagicOnion#130]
// standard gRPC channel
                    GrpcFactory.ClientChannel = new Channel(GrpcFactory.GrpcConf.Host, GrpcFactory.GrpcConf.Port, ChannelCredentials.Insecure);
                    // get MagicOnion dynamic client proxy
                    GrpcFactory.TaskProxy = MagicOnionClient.Create<IMagicOnionTaskService>(GrpcFactory.ClientChannel);

GrpcFactory. GrpcConf. Host IP no matter what, no error when start.

**Comment by khaaaniii** [comment]
i think` createdchannel.state` is what you want !

**Comment by leoterry-ulrica** [comment]
if (GrpcFactory.ClientChannel.State == ChannelState.Idle)
                    {
                        LOG.Info($"gRPC连接成功，IP：{GrpcFactory.GrpcConf.Host}，Port：{GrpcFactory.GrpcConf.Port}。");
                    } 
right?

**Comment by neuecc** [comment]
```csharp
// you can connect explicitly
await channel.ConnectAsync();

// you can check current status
if (channel.State == ChannelState.Idle)
{
}

// you can monitor state changed
var last = channel.State;
await channel.WaitForStateChangedAsync(last);
```

**Comment by leoterry-ulrica** [comment]
thankyou very much

**Comment by leoterry-ulrica** [comment]
`  await GrpcFactory.ClientChannel.ConnectAsync();
                    if (GrpcFactory.ClientChannel.State == ChannelState.Ready)
                    {
                        LOG.Info($"gRPC连接成功，IP：{GrpcFactory.GrpcConf.Host}，Port：{GrpcFactory.GrpcConf.Port}。");
                    }
                    else
                    {
                        LOG.Error($"gRPC连接失败，状态：{GrpcFactory.ClientChannel.State}，IP：{GrpcFactory.GrpcConf.Host}，Port：{GrpcFactory.GrpcConf.Port}。");
                        LOG.Info("4秒后重连gRPC Server......");
                        await Task.Delay(TimeSpan.FromSeconds(4));
                        await ConnectMagicOnionHostAsync();
                    }`
Is there something wrong? 
`await GrpcFactory.ClientChannel.ConnectAsync()`
Once not connected, can not enter the following logical judgment.
@neuecc

**Comment by neuecc** [comment]
First of all, gRPC connection is automatically connect/reconnect in channel.
But, if you want to do everything explicitly, use ConnectAsync(deadline) and try-catch.
