### ISSUE TITLE
dotnet new template

### ISSUE THREAD

**Issue by neuecc** [Cysharp/MagicOnion#131]
for `.NET Core/Unity` and `.NET Core/.NET Core`.
https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates

package naming(install by `dotnet new -i packagename` command)
`MagicOnion.UnityTemplate` and `MagicOnion.DotNetCoreTemplate` ?
`MagicOnion.Template.Unity` and `MagicOnion.Template.DotNetCore` ?

**Comment by itn3000** [comment]
according to the [templating list](https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new), majority is *.Templates or *.Template.

**Comment by neuecc** [comment]
thank you for the useful information!
