### ISSUE TITLE
Is "Microsoft.Extensions.Hosting" required for MagicOnion.Hosting?

### ISSUE THREAD

**Issue by tanaka-takayoshi** [Cysharp/MagicOnion#136]
Since MagicOnion.Hosting package has no dependency for "Microsoft.Extensions.Hosting" package, I have to add the reference manually to use `new HostBuilder()`.

```xml
  <ItemGroup>
    <PackageReference Include="MagicOnion" Version="2.0.5" />
    <PackageReference Include="MagicOnion.Hosting" Version="2.0.5" />
    <!-- manual `dotnet add package Microsoft.Extensions.Hosting` is required to add the following line -->
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="2.2.0" />
  </ItemGroup>
```

I wonder it should be described in the [README](https://github.com/Cysharp/MagicOnion#hosting) or this dependency should be added to the NuGet package.
Which do you prefer?

**Comment by neuecc** [comment]
Yes, right!

**Comment by neuecc** [comment]
`1.2.0`'s MagicOnion.Hosting dependent Microsoft.Extensions.Hosting in default.
(and use `MagicOnionHost.CreateDefaultBuilder()` to recommended way)
