### ISSUE TITLE
General + License and Dependency questions

### ISSUE THREAD

**Issue by KarloX2** [Cysharp/MagicOnion#139]
Hi !

I'm looking at this project because I seek for a (future) substitution for WCF (nettcp/duplex communication between .NET processes) that will allow the same type of communication (fast/duplex/secure/session aware) under .NET 5 (when WCF probably won't be available any more).

This is very promising. So what I'm looking for is a solution for .NET 5 that will allow to re-use the existing DataContracts and ServiceContracts (with hopefully no or little modifications) and communicate using gRPC instead of WCF/nettcp, without the need to use a new data definition language. Possible?

I'd like to have session support. Is that built-in or would I need to implement something on my own?

A few questions I have about what is required and which licenses apply:

- MagicOnion is under MIT, right?
- It uses gRPC from https://packages.grpc.io  ?
- Could that switch to https://github.com/grpc/grpc-dotnet which claims to be (or will be) a managed pure .NET implementation?
- MagicOnion depends on MessagePack which is under MIT license, right?
- MessagePack again makes use of lz4net (has other permissive license). Is that an option, can I use MagicOnion / MessagePack without lz4net?
- More dependencies (outside .NET standard)

Thanks!
Karlo

**Comment by neuecc** [comment]
session support is not built-in, require your own.
(maybe it will implement MagicOnionFilter and backend is redis, it is not difficult)

* yes, MIT.
* no, MagicOnion(.NET Core) gRPC dependent is only NuGet Release
* grpc-dotnet support is on roadmap, currently no but near future
* yes, MessagePack-CSharp is MIT
* MessagePack-CSharp includes lz4net code, it can not separate now
* no dependencies, everything is listed on NuGet(exclude for Unity)
