### ISSUE TITLE
StreamingHub Example?

### ISSUE THREAD

**Issue by KarloX2** [Cysharp/MagicOnion#142]
I'm trying to reproduce the StreamingHub example from the main project readme but it seems there are missing some parts. I can't see how the client is supposed to be implemented and some types are missing. Is the complete example available somewhere or another complete example for StreamingHub ?

**Comment by neuecc** [comment]
Thanks, I've added to ReadMe.

**Comment by KarloX2** [comment]
Ok, but I still cannot see how to instantiate / activate the server and the client.

**Comment by neuecc** [comment]
> how to instantiate / activate the server and the client
Is it means how to host and deploy?

Setup project structure is served on samples.
https://github.com/Cysharp/MagicOnion/tree/master/samples

Build and CI sample is not yet.
