### ISSUE TITLE
is Thread safe necessary?

### ISSUE THREAD

**Issue by khaaaniii** [Cysharp/MagicOnion#143]
Is it necessary to lock arrays and common variables to be thread safe ?
does magic onion handle requests in multithreads ?
i want to read and write an array ? how can i be sure the array is up to date and synchronized?

best regards

**Comment by neuecc** [comment]
`MagicOnionClient`, `MagicOnionStreamingHubClient` is almostly thread-safe.
MagicOnionStreamingHubClient's receiving events is dependent on `SynchronizationContext`.
If in Unity, it is thread-safe, in .NET Core, it is not thread-safe.
