### ISSUE TITLE
Support generic types in IService<>

### ISSUE THREAD

**Issue by bbougot** [Cysharp/MagicOnion#146]
Is it possible to add generics to the IService<> resolvers?

Something like this:

    public interface IRemoteContract<T> : IService<IRemoteContract<T>>
    {
        UnaryResult<Task> ProcessRemotely(T item, NodeMetrics nodeMetrics);
    }

I get this output when I compile:
<img width="914" alt="Capture d’écran 2019-05-14 à 20 51 40" src="https://user-images.githubusercontent.com/8962802/57723982-1ae09100-768a-11e9-9519-06030b31a45b.png">

**Comment by neuecc** [comment]
Could you provide a full code to reproduce it?

**Comment by bbougot** [comment]
Here's a full sample to reproduce the issue, please launch Smart.GrandCentralDispatch.Client:
https://www.dropbox.com/s/p54qoc93wm4gxgd/Smart.GrandCentralDispatch.zip?dl=0

**Comment by bbougot** [comment]
Well, I managed to get it working by resolving the assembly which actually override my generic method to provide a concrete implementation of my generic type.
Instead of doing this:

    var service = MagicOnionEngine.BuildServerServiceDefinition(
        new[] { typeof(**Smart.GrandCentralDispatch.Resolvers.Resolver**).Assembly },  // Manually add
        new MagicOnionOptions(true)
        {
            MagicOnionLogger = new MagicOnionLogToGrpcLogger()
        }
    );

I'm doing:

    var service = MagicOnionEngine.BuildServerServiceDefinition(
        new[] { typeof(**Smart.GrandCentralDispatch.Server.Resolvers.Resolver**).Assembly },  // Manually add
        new MagicOnionOptions(true)
        {
            MagicOnionLogger = new MagicOnionLogToGrpcLogger()
        }
    );

which makes the MagicOnion engine to resolve the class:

    public sealed class Resolver : Resolver<Message>
    {
        public override async UnaryResult<Task> ProcessRemotely(Message message, NodeMetrics nodeMetrics)
        {
            return Task.Delay(125);
        }

instead of:

    public abstract class FuncResolver<T> : ServiceBase<IRemoteContract<T>>, IRemoteContract<T>
    {
        public virtual UnaryResult<Task> ProcessRemotely(T item, NodeMetrics nodeMetrics)
        {
            throw new NotImplementedException();
        }
    }

**Comment by neuecc** [comment]
thanks, I should wrote discover service problems to ReadMe.
There is one problem with using Generics.
Currently, MagicOnion creates gRPC path from interface and does not resolve closed generics.
for example path will be `IRemoteContract<T>.ProcessRemotely`.
This means can not create many service definitions in one generics service interface.

I'll change to resolve path of generics interface(it will be `IRemoteContract_Message.ProcessRemotely`, etc...).

**Comment by bbougot** [comment]
Yes I encoutered the same issue with resolving closed generics, I had to create several methods on the same contract for the same intent, otherwise that part https://github.com/Cysharp/MagicOnion/blob/master/src/MagicOnion/Server/MagicOnionEngine.cs#L133 failed because the handlers HashSet can not hold several times the same method definition.

Anyway, appart from this it works great so far!

**Comment by licentia88** [comment]
so any workaround for this? I'm stucked with the same problem...
