### ISSUE TITLE
Can load balancing be achieved through Magic Onion Filter?

### ISSUE THREAD

**Issue by gpg1993** [Cysharp/MagicOnion#147]
![50969539-2bd59600-1522-11e9-84ab-15dd85e3dcac](https://user-images.githubusercontent.com/16316663/57754271-a1e04880-7720-11e9-9bc7-f42b9f84783a.png)
Can you give me an example?

**Comment by neuecc** [comment]
LoadBalancer is out of concern about MagicOnion.
use NLB(on AWS), etc.
