### ISSUE TITLE
How do I use this framework to set up a cluster

### ISSUE THREAD

**Issue by leoterry-ulrica** [Cysharp/MagicOnion#148]
How do I use this framework to set up a cluster? zookeeper? consul?
thx

**Comment by neuecc** [comment]
I'm recommending container.
Pack to docker and push to any registries.
And run on container orchestrator services(Fargate, ECS, Kuberenetes, or any other managed kubernetes).

Load balancing,
For Unary(API) Services, to use tcp loadblanacer(like AWS NLB, ELB).
For Streaming, to use any service-discovery(or matching service, create your own or  use agones, open-match, etc.)

**Comment by leoterry-ulrica** [comment]
okay, thx.
