### ISSUE TITLE
Failed using DI: Type needs parameterless constructor

### ISSUE THREAD

**Issue by bbougot** [Cysharp/MagicOnion#150]
I'm trying to use dependency injection as explained [here](https://github.com/Cysharp/MagicOnion#di), but when I start my client I get the following exception:

> InvalidOperationException : Type needs parameterless constructor, class:Smart.GrandCentralDispatch.Contract.Resolvers.PayloadResolver

My service code is:

    public class PayloadResolver : FirstRemotePartialResolver<Payload, string>
    {
        private readonly Serilog.ILogger _logger;

        public PayloadResolver(Serilog.ILogger logger)
        {
            _logger = logger;
        }

        public override async UnaryResult<string> ProcessFirstRemotely(Payload payload,
            NodeMetrics nodeMetrics)
        {
            _logger.Information(
                $"New payload {payload.Body} received from node {nodeMetrics.Id}...");
            return payload.Body;
        }
    }

where FirstRemotePartialResolver is:

    public class FirstRemotePartialResolver<TU, TV> : FirstRemotePartialFuncResolver<TU, TV>
    {
        public override Func<TU, NodeMetrics, UnaryResult<TV>> GetFirstRemoteFunc()
        {
            return ProcessFirstRemotely;
        }
    }

and FirstRemotePartialFuncResolver is:

    public abstract class FirstRemotePartialFuncResolver<TU, TV> : ServiceBase<IFirstRemotePartialContract<TU, TV>>, IFirstRemotePartialContract<TU, TV>
    {
        public abstract Func<TU, NodeMetrics, UnaryResult<TV>> GetFirstRemoteFunc();

        public virtual UnaryResult<TV> ProcessFirstRemotely(TU item, NodeMetrics nodeMetrics)
        {
            throw new NotImplementedException();
        }
    }

I configure the DI like this:

    MagicOnionHost.CreateDefaultBuilder()
    .UseMagicOnion(
        new MagicOnionOptions(isReturnExceptionStackTraceInErrorDetail: true),
        new ServerPort(listeningAddress, listeningPort, ServerCredentials.Insecure))
    .ConfigureServices((context, services) =>
    {
        var basePath = $@"{Directory.GetParent(Assembly.GetAssembly(typeof(Program)).FullName).FullName}\logs";
        if (!Directory.Exists(basePath))
        {
            Directory.CreateDirectory(basePath);
        }

        var logger = new LoggerConfiguration()
            .WriteTo.Console()
            .CreateLogger();

        services.AddSingleton<IRestClient, RestClient>();
        services.AddSingleton<Serilog.ILogger>(logger);
        // Set-up the cluster
        services.AddRemoteCluster<Payload, Uri, string, string>(
            sp => sp.GetService<IMemoryCache>(),
            sp => new PayloadResolver(sp.GetService<Serilog.ILogger>()),
            sp => new UriResolver(sp.GetService<Serilog.ILogger>(), sp.GetService<IRestClient>()),
            sp => new RequestResolver(sp.GetService<Serilog.ILogger>()));
    })

I don't know what is going on, I'm using latest version (2.1.2).

<img width="1436" alt="Capture d’écran 2019-05-17 à 09 35 36" src="https://user-images.githubusercontent.com/8962802/57913168-5054cc80-788c-11e9-8e94-7b98a7f343ad.png">

<img width="1436" alt="Capture d’écran 2019-05-17 à 09 35 47" src="https://user-images.githubusercontent.com/8962802/57913181-577bda80-788c-11e9-8f72-e468c6e3a3ba.png">

**Comment by bbougot** [comment]
Here's a full sample: https://www.dropbox.com/s/5a1uvhpvkgvb02t/Smart.GrandCentralDispatch.zip?dl=0
Please launch Smart.GrandCentralDispatch.Node

**Comment by bbougot** [comment]
My bad, I was mixing MagicOnion server with MagicOnionHost.

**Comment by neuecc** [comment]
Okay.
