### ISSUE TITLE
How to Compile MagicOnion without errors

### ISSUE THREAD

**Issue by Sajjad2678** [Cysharp/MagicOnion#152]
Hi Guys. I am new in working with this great pack so excuse me if my questions are beginner.
1) when I downloaded code I can't successfully compile and build solution also in the current version when I tried to compile it I encountered a lot of errors (628 errors). then I used NuGet for installing MagicOnion pack on my client and server projects and anything works well. How I can successfully compile and build MagicOnion without any error?
2) in 1.9 version I created a sample project only for testing communication between client and server ، I do not use MagicOnionCodeGenerator and my code works as excepted(of course not in unity). Is it true that when I want to use MagicOnion with Unity I have to use the MagicOnionCodeGenerator?

**Comment by neuecc** [comment]
1. requires detail of what kind of error
2. Unity + IL2CPP requires code generator. Editor or Mono environment, don't need.

**Comment by Sajjad2678** [comment]
1)

almost all the errors were related to fixing references. I fixed those errors But there are still a few errors :

**Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0122	'StreamingHubClientBuilder<TStreamingHub, TReceiver>' is inaccessible due to its protection level	DynamicCodeDumper	E:\Users\Sajjad\Downloads\MagicOnion_2.1\MagicOnion-master\sandbox\DynamicCodeDumper\Program.cs	42	Active
Error	CS0016	Could not write to output file 'C:\GitHubRepositories\MagicOnion\sandbox\Sandbox.NetCoreServer\Sandbox.NetCoreServer.xml' -- 'Could not find a part of the path 'C:\GitHubRepositories\MagicOnion\sandbox\Sandbox.NetCoreServer\Sandbox.NetCoreServer.xml'.'	Sandbox.NetCoreServer	E:\Users\Sajjad\Downloads\MagicOnion_2.1\MagicOnion-master\sandbox\Sandbox.NetCoreServer\CSC	1	Active
Error	CS0122	'AssemblyHolder' is inaccessible due to its protection level	DynamicCodeDumper	E:\Users\Sajjad\Downloads\MagicOnion_2.1\MagicOnion-master\sandbox\DynamicCodeDumper\Program.cs	40	Active
Error	CS0122	'StreamingHubClientAssemblyHolder' is inaccessible due to its protection level	DynamicCodeDumper	E:\Users\Sajjad\Downloads\MagicOnion_2.1\MagicOnion-master\sandbox\DynamicCodeDumper\Program.cs	43	Active**

as you can see all **inaccessible** errors related to ENABLE_SAVE_ASSEMBLY directive

2) Do you mean if I want to create a game and use IL2CPP I just have to use MagicOnionCodeGenerator?

**Comment by neuecc** [comment]
1.

DynamicCodeDumper is support tool so you can remove project.
or uncomment this line https://github.com/Cysharp/MagicOnion/blob/master/src/MagicOnion/MagicOnion.csproj#L4-L5

2.

Yes.

**Comment by Sajjad2678** [comment]
Thank you
