### ISSUE TITLE
Does MagicOnion support client-server communication within Blazor application?

### ISSUE THREAD

**Issue by vova-lantsov-dev** [Cysharp/MagicOnion#153]

**Comment by neuecc** [comment]
No and No Plans.

**Comment by snarlynarwhal** [comment]
Hi, I found an article that Steve Sanderson wrote recently called [Using gRPC-Web with Blazor WebAssembly](https://blog.stevensanderson.com/2020/01/15/2020-01-15-grpc-web-in-blazor-webassembly/). I haven't had a chance to see if it works for MagicOnion too, but it looks like it might be possible now?
