### ISSUE TITLE
Custom routing api swagger HttpGateway

### ISSUE THREAD

**Issue by tuongntk** [Cysharp/MagicOnion#155]
So, first of all tks you for your contribution to the open sources network. I'm so appreciate with this library.
 I'd like to have one question for customization.
 Ex: I have service as:

```csharp
public interface IMyFirstService : IService<IMyFirstService>
{
    UnaryResult<string> SumAsync(int x, int y);
}
```

Is there any option to custom routing by Attribute to method like this:

```csharp
[Route("/api/sum")]
UnaryResult<string> SumAsync(int x, int y);
```

Tks u and have a nice day.

**Comment by neuecc** [comment]
Thank you.

I don't provide attribute routing for HTTP Gateway.
Could you use `MapMiddleware`?

**Comment by tuongntk** [comment]
I'm using your libs and just thinking new customization flexible for Http Gateway with custom routing url and custom http method. I'm diving and learning your source code to understand. Maybe in the near future after clearing it i'll implement this feature. 

Tks you so much.
