### ISSUE TITLE
how to support the raspiberry?

### ISSUE THREAD

**Issue by Rhaegarlai** [Cysharp/MagicOnion#158]
I wonder that it supports the raspiberry? My program toasted that Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "/home/pi/libgrpc_csharp_ext.x86.so" when it run on ARM.Is there a way to support ARM?

**Comment by neuecc** [comment]
Currently no, but if we complete pure C# client, maybe works.
https://github.com/Cysharp/MagicOnion/issues/115

**Comment by Rhaegarlai** [comment]
I found that https://github.com/grpc/grpc-dotnet is available on ARM . It seems to use "libgrpc_csharp_ext.x86.so" because the project has the same files too.

**Comment by neuecc** [comment]
grpc-dotnet is mainly for server project.
but it (will) contains client project(with HttpClient HTTP/2 support).
