### ISSUE TITLE
Android Service Communication

### ISSUE THREAD

**Issue by Sajjad2678** [Cysharp/MagicOnion#159]
Hi guys. our team currently working on a game makes with unity. we decide to use an android service for communicating between MagicOnion server and android service .so can anyone guide us on how to use java for sending objects to  MagicOnion server or is there any helpful link? 
Thank you

**Comment by neuecc** [comment]
Currently can not send(connect) directry from Java gRPC to C# MagicOnion.
You can use HttpGateway to interop other language.

**Comment by EbramTawfik** [comment]
so is there way to get .proto file so it can be used for different programming language like Go or Java?

**Comment by ogswr** [comment]
no way, because magiconion doesn't have pure proto implementation.
