### ISSUE TITLE
Create Android/IOS LAN party gmae

### ISSUE THREAD

**Issue by Sajjad2678** [Cysharp/MagicOnion#172]
we want to use MagicOnion for our mobile game. in our game, gamers can play together in a LAN party without using the internet. I guess in this case one of the players must be the server. is it possible now or in feature? 
thank you for your amazing tool.

**Comment by neuecc** [comment]
In my slide page14 is described it.
https://www.slideshare.net/neuecc/the-usage-and-patterns-of-magiconion/14

**Comment by Sajjad2678** [comment]
do you mean only a pc can be a MagicOnionServer (Not UNITY)? or clients(mobile devices) can too

**Comment by neuecc** [comment]
Yes, only PC can be a MagicOnionServer.
Currently(and also future) does not support that Unity(Editor/PC/Mobile/etc...) can be a Server.

**Comment by Sajjad2678** [comment]
thank you for your fast response
