### ISSUE TITLE
Enhancement:  Add GRPC Interoperability with "standard" gRPC clients

### ISSUE THREAD

**Issue by delfuria** [Cysharp/MagicOnion#173]
HI, this is a great package and inside this framework we can use raw gRPC APIs.
But actually there's no interoperability between MagicOnion and "standard" gRPC client.
What i mean is that we cannot call MagicOnion server from a gRPC client.
Sure, we can use Http gateway but it will be great the capability of consume MagicOnion service from gRPC client written in any supported language.
This could be a great improvement !!!
Thanks

**Comment by neuecc** [comment]
Yes, I'll check how protobuf-net.Grps done or create .proto from MagicOnionCodeGenerator(moc.exe).
https://github.com/protobuf-net/protobuf-net.Grpc

But the priority is low.

**Comment by delfuria** [comment]
Hi, thanks for the reply, but the "problem" as mentioned in a tweet is not the creation of .proto but the marshalling from MessagePack to ProtoBuff since in MagicOnion you use the 1st.
I know that for you this is a low priority issue, but i think that it could be a game changer and open usage of your library for every use and not just for use inside an unit project.
Thanks again for your work !
