### ISSUE TITLE
Push message from server to a single client

### ISSUE THREAD

**Issue by Britvich** [Cysharp/MagicOnion#196]
In a multiuser environment, a client might want to send a message to a specific client (e.g. a chat whisper), using the server as a message router from one client to another client. Is there a way for a server to send (or forward) a message to another client, without that other client soliciting it?

As a work around, I suppose I could use `BroadcastExceptSelf`, with the message including a desired recipient, and have each client ignore broadcasts that aren't for them. That would add a lot of unnecessary traffic though.

**Comment by neuecc** [comment]
I'm thinking of exposing the Group to the outside.
I think that function is essential.

**Comment by neuecc** [comment]
I've now added in `BroadcastTo`/`BroadcastToSelf` in `Ver 2.6.1`.
Please try it.

**Comment by Britvich** [comment]
Thanks @neuecc for the fast addition of this function. I will try it soon.
