### ISSUE TITLE
Question: How to set Unity as the server and ASP.net Core API as the client & server

### ISSUE THREAD

**Issue by VR-Architect** [Cysharp/MagicOnion#201]
Thanks for the excellent work on this. 

Do you mind adding a document page on how to reverse the client/server config so Unity is the server and the ASP.net CORE API is the client & server?

Here is my use case:

- Unity Client
  - Communicates to a web service on ASP.net Core API server
     - Sends an asset to a web service that can handle large files
  - Runs MagicOnion client communicating to ASP.net Core API server
     - Receives results of asset upload to CDN server
- ASP.net Core API server
  - Runs MagicOnion server to communicate with the Unity client
    - Validates user, receives uploaded asset, saves asset to location Unity build server can get to
  - **Runs MagicOnion client to communicate with the Unity build server**
    - Notifies the build server of the new asset
    - Once asset is built, sends back results to the Unity client
- Unity build server
  - **Runs MagicOnion server to communicate with the ASP.net Core API server**
    - Builds the asset and saves to asset CDN server
    - Sends results back to the ASP.net Core API server

Thanks for the help!

**Comment by neuecc** [comment]
MagicOnion does not support *Unity as the server* .
