### ISSUE TITLE
Is there any "Group-Wide" storage?

### ISSUE THREAD

**Issue by kt81** [Cysharp/MagicOnion#213]
I'm trying to store data that has global state of one StreamingHub's group
but I could not find such a storage in the StreamingHubBase and IGroup.

For example, we can use it in the case like that to add the Chat Log functionality to the "ChatHub" sample project easily.

**Comment by mayuki** [comment]
MagicOnion doesn't have Group-wide (Hub level) storage. If you want to store any data in each group, please consider using something like `ConcurrentDictionary<K, V>`.

**Comment by kt81** [comment]
Thanks!
