### ISSUE TITLE
InvalidOperationException on Disconnect from server

### ISSUE THREAD

**Issue by marekhanzlik** [Cysharp/MagicOnion#214]
When i close my client there is exception on the server

```
W1101 14:58:09.042071 Grpc.Core.Server Exception while handling RPC. System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Grpc.Core.Internal.AsyncCallServer`2.SendStatusFromServerAsync(Status status, Metadata trailers, Nullable`1 optionalWrite) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\AsyncCallServer.cs:line 137
   at Grpc.Core.Internal.DuplexStreamingServerCallHandler`2.HandleCall(ServerRpcNew newRpc, CompletionQueueSafeHandle cq) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\ServerCallHandler.cs:line 255
   at Grpc.Core.Server.HandleCallAsync(ServerRpcNew newRpc, CompletionQueueSafeHandle cq, Action continuation) in T:\src\github\grpc\src\csharp\Grpc.Core\Server.cs:line 346
```

I've tried it with the unity sample you provided but this exception is raised here too.
What is a correct way to shutdown the client withou triggering exception on server?

Edit: weird thing is, when i call disconnect (consists of Client.DisposeAsync() and then _grpcChannel.DisposeAsync()) after 7+ seconds, the exception will not emerge, only when i connect and disconnect within those 7 second the exception pops up

**Comment by Sajjad64** [comment]
Unfortunately this error occured for me any time i disconnect client in unity .However i  don't see any disruption in server work.

**Comment by mayuki** [comment]
This is gRPC Core related issue. Please see https://github.com/grpc/grpc/issues/9377

**Comment by Sajjad64** [comment]
so what is the solution?.it seems this problem not solved.even if we don't solve the problem is there any impact for server with many clients?

**Comment by LuigiElleBalotta** [comment]
> However i don't see any disruption in server work.

That's not true, if you stop unity and restart (and you never close the server), unity won't start until you shut down the server.

**Comment by marekhanzlik** [comment]
> > However i don't see any disruption in server work.
> 
> That's not true, if you stop unity and restart (and you never close the server), unity won't start until you shut down the server.

You are shutting down the client the wrong way then.
Are you disposing your client in OnDestroy() ?
```
protected async override void OnDestroy()
{
    await client.DisposeAsync();
}
```

**Comment by LuigiElleBalotta** [comment]
Sorry, where can i find OnDestroy method? Newbie in unity

**Comment by marekhanzlik** [comment]
Open new ticket pls and i'll help you there, lets not pollute this thread
