### ISSUE TITLE
RedisGroup requires add ConnectionMultiplexer to MagicOnionOptions.ServiceLocator before create it

### ISSUE THREAD

**Issue by tranan-mirabo** [Cysharp/MagicOnion#216]
I try connect to redis server and set DefaultGroupRepositoryFactory is RedisGroupRepositoryFactory but it throw an error.
![Capture](https://user-images.githubusercontent.com/56952692/68262471-f6cc9e00-0075-11ea-951e-4c7d20e45ce0.PNG)

What is correct way to use redis with magiconion?

**Comment by mayuki** [comment]
If you are using `MagicOnion.Hosting`, please use `ConfigureServices` in the same way as .NET Core Generic Host.

```csharp
var magicOnionHost = MagicOnionHost.CreateDefaultBuilder(useSimpleConsoleLogger: true)
    .UseMagicOnion(options, new ServerPort("localhost", 12345, ServerCredentials.Insecure))
    .ConfigureServices(services =>
    {
        services.AddSingleton(ConnectionMultiplexer.Connect("localhost:6379"));
    })
    .UseConsoleLifetime()
    .Build();
```

**Comment by tranan-mirabo** [comment]
thanks you!
