### ISSUE TITLE
[Unity3D/MessagePack] Exception client side

### ISSUE THREAD

**Issue by LuigiElleBalotta** [Cysharp/MagicOnion#222]
Hello, I am working on a Unity3D repository, everything worked fine (MoveAsync, i even implemented a new endpoint called SendAnimationAsync).
Now i want to implement a login form, when I try to call the method to send username and password I receive this error:

`InvalidOperationException: Does not registered client factory, dynamic code generation is not supported on IL2CPP. Please use code generator(moc).
MagicOnion.Client.StreamingHubClient.Connect[TStreamingHub,TReceiver] (Grpc.Core.CallInvoker callInvoker, TReceiver receiver, System.String host, Grpc.Core.CallOptions option, MessagePack.IFormatterResolver resolver, Grpc.Core.Logging.ILogger logger) (at Assets/Scripts/MagicOnion/Client/StreamingHubClient.cs:24)
MagicOnion.Client.StreamingHubClient.Connect[TStreamingHub,TReceiver] (Grpc.Core.Channel channel, TReceiver receiver, System.String host, Grpc.Core.CallOptions option, MessagePack.IFormatterResolver resolver, Grpc.Core.Logging.ILogger logger) (at Assets/Scripts/MagicOnion/Client/StreamingHubClient.cs:13)
NotLoggedClient+<ConnectAsync>d__10.MoveNext () (at Assets/Scripts/Login/NotLoggedClient.cs:56)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
NotLoggedClient+<InitializeClient>d__9.MoveNext () (at Assets/Scripts/Login/NotLoggedClient.cs:51)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at C:/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:114)
UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at C:/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:94)`

What am I missing? Obviously I used the Generator from the top unity menu without any errors.
![Cattura](https://user-images.githubusercontent.com/16773213/68866180-510fd380-06f4-11ea-9cf8-2b82155575c7.PNG)

This is my repository with the error: https://github.com/LuigiElleBalotta/ElleRealTime

Start the server then the client.

**Comment by mayuki** [comment]
MagicOnion Code Generator (moc) collects the interfaces (IService, IStreamingHub) in the .csproj.
I think you have split the one `Server` project to `Server` and `ServerShared` projects (and others). In that case, if `Server` refers to `ServerShared` as `ProjectReference`, `Server` doesn't contain the interfaces.

Could you consider the following solutions?
1. Use Linking Files (`LinkFromUnity` style) or
2. Use `ServerShared` project path instead of `Server` as the argument of `moc`.

**Comment by LuigiElleBalotta** [comment]
@mayuki have you seen the repo?
Because, IF YES, you would notice that the projects are organized the same as the sample of MagicOnion repository, so I have a c# console app (ElleRealTime) and inside MagicOnionTest/Assets/Scripts/ServerShared the shared folder/link, that has NO .csproj file, it's inside Assembly-CSharp.. 

So.. what should I do?

P.S. ElleRealTime.Shared is a shared project between server's DLL. So it's useless for the purpose.

**Comment by LuigiElleBalotta** [comment]
Ok maybe i fixed it, but with link folder i must make different entities for DB classes (because if I use link from a unity project folder i can't add the reference do a framework that i wrote, so my class "Account" can't be:

> public class Account : **View**

I had to move that class outside the linked folder.
By the way i'm implementing a login form and probably i need some support, i will update here in a few hours..

**Comment by LuigiElleBalotta** [comment]
Ok, now i can login, thanks! I adopted the second solution. By the way, now i got another problem (no idea why it happens).
When i click on a .cs file in unity, visual studio opens but i got this error:
![Cattura](https://user-images.githubusercontent.com/16773213/68930763-60902a80-078f-11ea-9448-4c0f676a1014.PNG)

In english it should be something similar to:
Selected file is not a valid solution file

Any idea why this happen?
