### ISSUE TITLE
hope support all interface maps

### ISSUE THREAD

**Issue by wilsonliu78** [Cysharp/MagicOnion#223]
**MagicOnionEngine.cs**

//var interfaceMap = classType.GetInterfaceMap(inheritInterface);

                    var interfaceMaps = GetAllInterfaceMaps(classType).Where(x=>x.TargetMethods.Length>0);
                    foreach (var interfaceMap in interfaceMaps) {
                        for (int i = 0; i < interfaceMap.TargetMethods.Length; ++i)
 

static IEnumerable<InterfaceMapping> GetAllInterfaceMaps(this Type type) =>
    type.GetTypeInfo()
         .ImplementedInterfaces
         .Select(i => type.GetInterfaceMap(i));

**Comment by mayuki** [comment]
Does it mean you want to implement multiple services in one class?

**Comment by wilsonliu78** [comment]
> Does it mean you want to implement multiple services in one class?
like this:
interface a {
    UnaryResult<x> f1(dynamic input);
}
interface b: a, IService<b>
{
  
}

**Comment by wilsonliu78** [comment]
> Does it mean you want to implement multiple services in one class?

like this:
interface a {
UnaryResult f1(dynamic input);
}
interface b: a, IService<b>
{

}
