### ISSUE TITLE
Problems with StreamingHubClient

### ISSUE THREAD

**Issue by carrasco39** [Cysharp/MagicOnion#227]
Hello,
I keep getting this, when trying to connect to a StreamingHubClient. 
```
Cannot access a disposed object.
Object name: 'StreamingHubClient'.

   at MagicOnion.Client.StreamingHubClientBase`2.ThrowIfDisposed()
   at MagicOnion.Client.StreamingHubClientBase`2.WriteMessageWithResponseAsync[TRequest,TResponse](Int32 metthodId, TRequest message)
   at MatchmakingServer.Tests.ClientTest.Initialize()
```

my client connection code:
```cs
public async void Initialize()
        {
            Channel channel = new Channel("0.0.0.0", 7081, ChannelCredentials.Insecure);
            try {
                IMatchmaker client = StreamingHubClient.Connect<IMatchmaker, IMatchmakerReceiver>(channel, this);
                await client.RegisterTicket();

            }
            catch (Exception e) {
                Console.WriteLine($"{e.Message}\n\n{e.StackTrace}");
            }
            
        }
```
my server-side code: 
```cs
// setup MagicOnion and option.
            ServerPort port = new ServerPort("0.0.0.0", 7081, ServerCredentials.Insecure);
            var service = MagicOnionEngine.BuildServerServiceDefinition(isReturnExceptionStackTraceInErrorDetail: true);

            var server = new global::Grpc.Core.Server
            {
                Services = { service },
                Ports = { port }
            };

            try
            {
                // launch gRPC Server.
                server.Start();

            }
            catch (Exception e) {
                Console.WriteLine($"{e.Source}\n{e.Message}\n\n{e.StackTrace}");
            }
```

**Comment by mayuki** [comment]
StreamingHubClient may be disposed with an exception. Try enabling gRPC logging on the client and report furthermore details.

```csharp
GrpcEnvironment.SetLogger(new Grpc.Core.Logging.ConsoleLogger());
```

**Comment by Sajjad64** [comment]
i have same problem too with StreamingHubClient
This is my Server calss for connecting and shuttingdown client
`public class Server :IDisposable
    {
        private Channel _Channel;
        private ICatDogHub _StreamingClient;
        private ICatDogHubReceiver _CatDogHubReceiver;
        private Action _DisconnectHandler;
        private RunController _Controller;

        public bool IsConnected => _Channel.State == ChannelState.Ready;
        public bool IsConnecting => _Channel.State == ChannelState.Connecting;
        public bool IsShutdown => _Channel.State == ChannelState.Shutdown;
        public bool IsIdle => _Channel.State == ChannelState.Idle;
        public bool IsTransientFailure => _Channel.State == ChannelState.TransientFailure;
        public bool IsCreated => _Channel != null;

        public Server(ICatDogHubReceiver catDogHubReceiver,Action disconnectHandler)
        {
            _CatDogHubReceiver = catDogHubReceiver;
            _DisconnectHandler = disconnectHandler;
            _Controller = new RunController();
        }
        public async Task<(ChannelState, ICatDogHub)> ConnectToServer()
        {
            if (!_Controller.ServerIsReady)
            {
                return (ChannelState.Shutdown, null);
            }
            if (_Channel is null ||
                _Channel.State is ChannelState.Shutdown)
            {
                _Controller.GotoRunningState();
                await createChannelAndHub().ConfigureAwait(false);
                _Controller.GotoReadyState();
            }
            return (_Channel.State, _StreamingClient);
        }

        private async Task createChannelAndHub()
        {
            this._Channel = new Channel(Utility._ServerAddress, 12345, ChannelCredentials.Insecure);
            _StreamingClient = StreamingHubClient.
                Connect<ICatDogHub, ICatDogHubReceiver>(this._Channel, _CatDogHubReceiver);
        }
        public async UnaryResult<bool> Shutdown()
        {
            if (_Controller.ServerIsReady)
            {
                _Controller.GotoRunningState();
                bool result= await shutdownHubAndChannel();
                _Controller.GotoReadyState();
                return result;
            }
            return false;
        }

        private async UnaryResult<bool> shutdownHubAndChannel()
        {
            if (_Channel?.State != ChannelState.Shutdown)
            {
                await _StreamingClient.DisposeAsync();
                await _Channel.ShutdownAsync();
                Dispose();
                return true;
            }
            Dispose();
            return false;
        }

        public void Dispose()
        {
            _StreamingClient = null;
            _Channel = null;
        }`
for first time i call ConnectToServer() method and after a while i call Shutdown(). now when i calling 
ConnectToServer() method and if i call a method like Authorize() in my Hub it says :
ObjectDisposedException: Cannot access a disposed object.
Object name: 'StreamingHubClient'.
MagicOnion.Client.StreamingHubClientBase`2[TStreamingHub,TReceiver].ThrowIfDisposed () (at Assets/Scripts/MagicOnion/Client/StreamingHubClientBase.cs:270)
MagicOnion.Client.StreamingHubClientBase`2+<WriteMessageWithResponseAsync>d__23`2[TStreamingHub,TReceiver,TRequest,TResponse].MoveNext () (at Assets/Scripts/MagicOnion/Client/StreamingHubClientBase.cs:230)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
Assets.Scripts.ServerShared.ClientOperations.Authorize+<Run>d__5.MoveNext () (at Assets/Scripts/ServerShared/ClientOperations/Authorize.cs:26)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
OnlineGamer+<Authorize>d__19.MoveNext () (at Assets/OnlineGamer.cs:163)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
UIController+<Authorize>d__7.MoveNext () (at Assets/UIController.cs:38)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at C:/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:114)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

**Comment by Sajjad64** [comment]
This error only happens when I use unity as client, not when I use windows/console app as client

**Comment by andarilhoz** [comment]
I'm with the same problem.

This is the log i receive from gRPC logs before the "Cannot access a disposed object." error.

`
System.InvalidOperationException: Request stream has already been completed.
  at Grpc.Core.Internal.AsyncCall`2[TRequest,TResponse].CheckSendPreconditionsClientSide () [0x00040] in <b75a834ddb974a448cb6a55e7473c3e7>:0 
  at Grpc.Core.Internal.AsyncCall`2[TRequest,TResponse].CheckSendAllowedOrEarlyResult () [0x00000] in <b75a834ddb974a448cb6a55e7473c3e7>:0 
  at Grpc.Core.Internal.AsyncCallBase`2[TWrite,TRead].SendMessageInternalAsync (TWrite msg, Grpc.Core.WriteFlags writeFlags) [0x00031] in <b75a834ddb974a448cb6a55e7473c3e7>:0 
  at Grpc.Core.Internal.AsyncCall`2[TRequest,TResponse].SendMessageAsync (TRequest msg, Grpc.Core.WriteFlags writeFlags) [0x00000] in <b75a834ddb974a448cb6a55e7473c3e7>:0 
  at Grpc.Core.Internal.ClientRequestStream`2[TRequest,TResponse].WriteAsync (TRequest message) [0x0000d] in <b75a834ddb974a448cb6a55e7473c3e7>:0 
  at MagicOnion.Client.StreamingHubClientBase`2+<WriteMessageWithResponseAsync>d__23`2[TStreamingHub,TReceiver,TRequest,TResponse].MoveNext () [0x0011b] in <64e2bcd6b7444fbcb0c0e9c808d7481d>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <7d97106330684add86d080ecf65bfe69>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <7d97106330684add86d080ecf65bfe69>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <7d97106330684add86d080ecf65bfe69>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <7d97106330684add86d080ecf65bfe69>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <7d97106330684add86d080ecf65bfe69>:0 
  at Skydome.Backend.RelayServer.BaseRedisRelay`1+<ConnectAsync>d__11[TRedisBase].MoveNext () [0x00140] in <defd15c0ee5c4b73b8e050e5dbec3d53>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <7d97106330684add86d080ecf65bfe69>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <7d97106330684add86d080ecf65bfe69>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <7d97106330684add86d080ecf65bfe69>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <7d97106330684add86d080ecf65bfe69>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <7d97106330684add86d080ecf65bfe69>:0 
  at Skydome.Network.Internal.RedisRelay.ClientRedisRelay+<>c__DisplayClass0_0+<<RedisInitialization>b__0>d.MoveNext () [0x0008e] in <defd15c0ee5c4b73b8e050e5dbec3d53>:0 
 `

I tracked down and its happening when i try to initialize the StreamingHub:

`streamingClient = StreamingHubClient.Connect<IGamingHub, IGamingHubReceiver>(grpcChannel, this);`
