### ISSUE TITLE
Adding Context Items for services

### ISSUE THREAD

**Issue by Aranir** [Cysharp/MagicOnion#228]
I implemented a custom client filter:

```
	public class AppendIdentifierFilter: IClientFilter
	{
		public async ValueTask<ResponseContext> SendAsync(RequestContext context, Func<RequestContext, ValueTask<ResponseContext>> next)
		{
			context.Items.Add("test", "foo);
			return await next(context);
		}
	}
```

and tried to access it in my service on the server-side:

```
public async UnaryResult<Nil> Test()
		{
			Logger.Info($"we have the items {string.Join(", ", Context.Items.Keys)}");
....
```

But the items dictionary appears to be empty.

To initialize the service I used the following way:

```
MagicOnionClient.Create<ITestService>(_channel, new IClientFilter[]
				{
					new AppendIdentifierFilter(_identifier), 
				});
```

From the documentation, I could not figure out what part was still missing.

Thank you for any help

**Comment by mayuki** [comment]
There are no sharings between `RequestContext` (Client) and `CallContext` (Server). For example, you can use `CallContext.Items`  for sharing values between  MagicOnionFilters and a service method in the server-side per call.

If you want to pass any request key-values from client to server, use `RequestContext.CallOptions.Headers` (Client) and `CallContext.RequestHeaders` (Server).

```csharp
// Server: Client filter
public class MyClientFilter : IClientFilter
{
    public async ValueTask<ResponseContext> SendAsync(RequestContext context, Func<RequestContext, ValueTask<ResponseContext>> next)
    {
        context.CallOptions.Headers.Add("X-Foo", "Bar");
        return await next(context);
    }
}

// Server: Service filter
public class MyFilterAttribute : MagicOnionFilterAttribute
{
    public override async ValueTask Invoke(ServiceContext context, Func<ServiceContext, ValueTask> next)
    {
        var foo = context.CallContext.RequestHeaders.Get("x-foo")
        await next(context);
    }
}
```

**Comment by Alezy80** [comment]
@mayuki, the example you provided adds the same header to headers list on every call, thus list will be larger and larger. What is a correct way of using of Headers collection?

**Comment by mayuki** [comment]
Sorry. Certainly the example code does not work properly. To add a header to the request, use `WithHeaders` method.

```csharp
var client = MagicOnionClient.Create<IMyService>(channel)
    .WithHeaders(new Metadata
    {
        { "x-foo", "Bar" }
    });

await client.MethodBazAsync();
```

**Comment by Alezy80** [comment]
Yes, it works for service, but Hub does not have `WithHeaders` method.

**Comment by mayuki** [comment]
`StreamingHubClient.Connect` has `CallOptions` parameter that you can set `Metadata` using it. 

```csharp
var hubClient = StreamingHubClient.Connect<IMyHub, IMyHubReceiver>(
    channel,
    this,
    option: new CallOptions().WithHeaders(new Metadata()
    {
        { "x-foo", "Bar" }
    }));
```
