### ISSUE TITLE
Is there sample code that runs Telemetry?

### ISSUE THREAD

**Issue by novaoki** [Cysharp/MagicOnion#236]
I want to verify Telemetry in my environment.
I'm currently testing with CentOS 7.7, not docker.

The readme example code did not work.
Is there any sample code that works?
I would be very happy if I could see how it works with samples/ChatApp.

I think MagicOnion is a great framework!
Thank you.

**Comment by qq60665** [comment]
I have the same need.

**Comment by codmw44** [comment]
It is an example implementation of open-telemetry 0.2.0-alpha.179 (it is the last version in nuget.org). But original repository based on other NuGet source [https://github.com/open-telemetry/opentelemetry-dotnet](https://github.com/open-telemetry/opentelemetry-dotnet) and has different API in current version. 
I recommended taking a look at opentelemetry-dotnet examples. And add fresh version of opentelemetry-dotnet

**Comment by guitarrapc** [comment]
As README shows, you can work with opentemetry-dotnet 0.2.0-alpha.40.
Here's sample source.

> https://github.com/Cysharp/MagicOnion/commit/58dd85e31aeec3ddeba2ae1e6c37287fd941ca1e

Now I'm looking into opentemetry-dotnet 0.2.0-alpa282 and will update MagicOnion.Telemetry reference.
