### ISSUE TITLE
How to call client method from server?

### ISSUE THREAD

**Issue by AliBayatGH** [Cysharp/MagicOnion#242]
### Is there a way for a client to send a message to the server, or another client?

The sample code provides only one-way communication with no message streaming. How to write a code for server and client that supports bidirectional message streaming with .NET Core 3.0 using gRPC.

**Comment by neuecc** [comment]
Call `Broadcast`, in sample:
https://github.com/Cysharp/MagicOnion#streaminghub

```csharp
// Typed Server->Client broadcast.
Broadcast(room).OnJoin(self);

Broadcast(room).OnLeave(self);

Broadcast(room).OnMove(self);
```

**Comment by AliBayatGH** [comment]
> Call `Broadcast`, in sample:
> https://github.com/Cysharp/MagicOnion#streaminghub
> 
> ```cs
> // Typed Server->Client broadcast.
> Broadcast(room).OnJoin(self);
> 
> Broadcast(room).OnLeave(self);
> 
> Broadcast(room).OnMove(self);
> ```

I copied all the example code into a console َApp.
But I could not call a client method on the server.

**Comment by mayuki** [comment]
This is full sample code for StreamingHub server and client.
https://gist.github.com/mayuki/99625a489e5d50fe1cea575fee096c8c

**Comment by AliBayatGH** [comment]
> This is full sample code for StreamingHub server and client.
> https://gist.github.com/mayuki/99625a489e5d50fe1cea575fee096c8c

Thanks, but this is a private repository!
