### ISSUE TITLE
I have a problem chatting on the Android platform.

### ISSUE THREAD

**Issue by qq60665** [Cysharp/MagicOnion#248]
Hi, I have a problem chatting on the Android platform.
The server can receive messages sent by the client.
But cannot broadcast to other clients.
Official case of my chat code usage and Everything works fine on the windows platform.
I am very confused. Have other friends encountered similar problems?

                           best wishes

**Comment by neuecc** [comment]
Are you used a code-generator?
https://github.com/Cysharp/MagicOnion#server-and-clients
for mobile devices(IL2CPP), you should use code generator.

**Comment by qq60665** [comment]
> Are you used a code-generator?
> https://github.com/Cysharp/MagicOnion#server-and-clients
> for mobile devices(IL2CPP), you should use code generator.

Thanks for your reply, I seem to understand.
