### ISSUE TITLE
[Unity3D/3.0] UnsafeDirectBlitResolver is not found

### ISSUE THREAD

**Issue by kt81** [Cysharp/MagicOnion#250]
It seems that the unitypackage of MagicOnion 3.0.x has no `UnsafeDirectBlitResolver ` class so it causes compile error when the project using that class to resolve types.

**Comment by neuecc** [comment]
thanks, we're fixed in this commit https://github.com/Cysharp/MagicOnion/commit/889058f029b7111149bdbdcc097ef9523bc1fc76 and will release soon.

**Comment by kt81** [comment]
Thanks! 🍣
