### ISSUE TITLE
How to make it work with MS Orleans or Orleankka?

### ISSUE THREAD

**Issue by Tr0sT** [Cysharp/MagicOnion#251]
I saw in the description that this library is suitable as a transport protocol for Orleans (as I understand it). How exactly to launch silo to be able to use MS Orleans with this library under Unity (mobile platforms)? Could there be a Unity templates for both the server and the client in Unity? Is it possible atleast?

**Comment by neuecc** [comment]
Orleans is direct competitor.
There have similar functions so can not work with both.

**Comment by vrecluse** [comment]
Orleans and MagicOnion are not exactly the same thing.
Orleans is a feature rich actor model framework, actors(grains) are auto distributed in the cluster, which is very convenient to build a distributed back-end system, but it's not a proper choice to communicate with Unity directly.
MagicOnion, on the other hand, is very friendly to Unity users, and is possible to build micro-service system, but not as powerful as Orleans.
It would be a good choice to build server front-end with MagicOnion which Unity can talk to, and dispatch the request to Orleans back-end via Orleans client in MagicOnion server.
BTW, Orleans provides interfaces which you can customize message serialization by using MessagePack, etc.,

**Comment by TheCactusBlue** [comment]
I'll try to give a crack at adding Orleans support for MagicOnion.
