### ISSUE TITLE
How to broadcast all clients on server logic?

### ISSUE THREAD

**Issue by longfin** [Cysharp/MagicOnion#267]
I'm building a server logic for clients and it should broadcast when an event occurs that only the server knows it. so I need some method to invoke `StreamingHubBase.Broadcast()` in server logic.

According to `README.md`...

> If you want to create ServerSide loop and broadcast out of StreamingHub, you can pass Broadcast(room) result but it is unnatural, I'll add support kit of create server-side loop

Is there any plan or already implemented method about it? 

p.s I guess it may be duplicated of #242. 😕

**Comment by mayuki** [comment]
You can use `IGroup.CreateBroadcast<TReceiver>()` or similar methods for creating a broadcast proxy and pass the created proxy to a server logic.

https://github.com/Cysharp/MagicOnion/blob/629610fa14085b49bdf897ad7dc823ed22dedb4f/src/MagicOnion/Server/Hubs/Group.cs#L212

```csharp
public async Task HelloAsync()
{
    var group = await Group.AddAsync("GroupName");
    var receiver = group.CreateBroadcaster<IMyHubReceiver>();
    new ServerLogic(receiver).RunAsync();
}
...
class ServerLogic
{
    private readonly IMyHubReceiver _receiver;
    public ServerLogic(IMyHubReceiver receiver)
    {
        _receiver = receiver;
    }
    public async Task Run()
    {
        while (true)
        {
            await Task.Delay(1000);
            _receiver.OnEvent("Message");
        }
    }
}
```

**Comment by longfin** [comment]
@mayuki Thanks for the detailed sample code! but sadly, I don't have an idea that how can I get `Group` for `.CreateBroadcast()` in the server logic like as below.

```csharp
static async Task Main(string[] _)
{
    Task magicOnionRunner = MagicOnionHost
        .CreateDefaultBuilder()
        .UseMagicOnion()
        .RunConsoleAsync();

    Task broadcaster = Task.Run(async () =>
    {
        while (true)
        {
            await Task.Delay(TimeSpan.FromSeconds(10));
            // broadcast current server status to all peers here.
        }
    }
 
    await Task.WhenAll(magicOnionRunner, broadcaster);
}
```
or Should I put this logic to the class implements `StreamingHubBase`?

**Comment by longfin** [comment]
I found a workaround for a case that I wanted. but I'm not convinced it's natural. 😅

```
static async Task Main(string[] _)
{
    Task magicOnionRunner = MagicOnionHost
        .CreateDefaultBuilder()
        .UseMagicOnion()
        .RunConsoleAsync();

    Task broadcaster = Task.Run(async () =>
    {
        while (true)
        {
            await Task.Delay(TimeSpan.FromSeconds(10));
            IChatHub client = StreamingHubClient.Connect<IChatHub, IChatHubReceiver>(
              new Channel("localhost", 12345, ChannelCredentials.Insecure), 
              null
            );
            await client.JoinAsync(new JoinRequest
            {
                RoomName = "SampleRoom",
                UserName = "dummy"
            });
            while (true)
            {
                await Task.Delay(TimeSpan.FromSeconds(5));
                await client.SendMessageAsync("Broadcast");
            }
        }
    }
 
    await Task.WhenAll(magicOnionRunner, broadcaster);
}```

**Comment by mayuki** [comment]
In the next version, the Group will be replaced with a new model.
https://github.com/Cysharp/MagicOnion/pull/778

The new Group will have a broadcast mechanism that is separate from MagicOnion, and it will be possible to handle groups independently of operations from the Hub.
