### ISSUE TITLE
Re-Enabling Task Methods on Client interfaces

### ISSUE THREAD

**Issue by to11mtm** [Cysharp/MagicOnion#268]
Thank you for writing MagicOnion, it is a very nice and easy to use library and looking at the code has taught me a lot.

I noticed that `Task` types aren't allowed on Clients anymore, due to issues with Unity performance.

Would it be possible to add the support back in if it is done in a way that doesn't impact Unity? (i.e. `Task`s are still executed synchronously, or perhaps in the 'old way' that would cause a frame loss; Unity users could just opt not to use that side of things.) 

Biggest reason for this ask is that Porting code over from SignalR is a bigger lift currently; SignalR only allows `Task` returning methods on Client, but MagicOnion only supports `void` at this time.

I have a branch that seems to work based on the existing unit tests (uncommenting the 'task' tests passes) but still need to check some things on it (namely, whether deadlocks become a concern with the way I've fixed the problem.) I can put it as a draft merge if anyone is interested in reviewing it.

**Comment by neuecc** [comment]
Regardless of Unity, it is unacceptable for clients to delay when consuming messages.
If it makes sense to change to the Task signature, it's OK,
No, just for compatibility with SignalR.
