### ISSUE TITLE
How would you implement Authentication with MagicOnion? Does it work with IdentityServer?

### ISSUE THREAD

**Issue by snarlynarwhal** [Cysharp/MagicOnion#272]
How would you implement Authentication with MagicOnion? Does it work with IdentityServer?

If so, where can I get more information on how to set that up?

**Comment by mayuki** [comment]
We are preparing a simple authentication mechanism using JWT.
Currently, integration with IdentityServer is not planned.

**Comment by snarlynarwhal** [comment]
Alright awesome, JWT works for me! I look forward to it.

**Comment by Obrell86** [comment]
You can make use of JWT and IdentityServer right now by adding it to your headers.
`var headers = new Metadata
   {
     {"Authorization", $"Bearer {token}}
   };
MagicOnionClient.Create<TClient>(channel).WithHeaders(headers);
`
And implementing a Filter in MagicOnion which verifies it against your IDP.
Just get the token with
`context.CallContext.RequestHeaders.FirstOrDefault(x => x.Key == "Authorization")?.Value?.Substring(7)`

**Comment by snarlynarwhal** [comment]
Ah thanks so much @Obrell86!
