### ISSUE TITLE
UWP Release build crashes: Dynamic code generation is not supported on this platform.

### ISSUE THREAD

**Issue by Noemata** [Cysharp/MagicOnion#289]
I was finally able to get gRPC working in a UWP Release build context.  I verified that the Protobuf approach works as expected.  I'm starting to wonder if anyone has gotten this far with a UWP Release build?  I had to make a number of changes to the gRPC C# managed layer just so it would not crash due to invalid code generation by the .Net Native compiler.

Now that gRPC is working, MagicOnion crashes here:

var client = MagicOnionClient.Create<IMyFirstService>(channel);

With the exception being: Dynamic code generation is not supported on this platform.

Are there any workarounds or is it not possible to use the .Net Native toolchain? If not possible, UWP apps will never be able to go into the store using MagicOnion.

**Comment by neuecc** [comment]
Avoid by code generation as in Unity.
https://github.com/Cysharp/MagicOnion#unity-client-supports

**Comment by Noemata** [comment]
Could you please clarify "avoid by code generation" as in Unity?  I don't understand.
