### ISSUE TITLE
Decouple MagicOnion from MessagePack

### ISSUE THREAD

**Issue by Rurouni** [Cysharp/MagicOnion#29]
At the moment many core MagicOnion classes on Unity side are coupled with MessagePack through statics. That makes it hard to use just some parts of framework.  For example I am using just core bits with protobuf-net instead of MessagePack and my own server side framework, so every merge with upstream is total pain in places like ChannelContext.cs or MagicOnionClient.cs because of dependencies on MessagePack

I think it's great that MagicOnion comes in fully assembled opinionated package, but it would be even better if it was more layered and decoupled through interfaces allowing people to adapt or rewrite parts of it without hard fork and losing link with original repo

**Comment by neuecc** [comment]
Yes, it is absolutely necessary.
I would like to be able to generate .proto so that MagicOnion can be connected with other gRPC or native iOS/Android or others.
Currently, the system is tightly coupled by DynamicTupleArgument etc.
I want to think about a way to decouple.

**Comment by psibernetic** [comment]
Just want to show interest in this as well. MagicOnion is great, but I want to support other languages in the near future.

**Comment by isairz** [comment]
Hi. I'm looking for a wonderful way to connect Unity client with a server using protobuf.
Is it possible to use MagicOnion with custom serialize/deserialize ?

**Comment by neuecc** [comment]
MagicOnion v2 is more tightly coupled with MessagePack(ex StreamingHub)
so decouple MessagePack is not realistic.
