### ISSUE TITLE
SampleApp Freeze with forced shutdown. [Unity Standalone Il2cpp]

### ISSUE THREAD

**Issue by kubota62** [Cysharp/MagicOnion#295]
MagicOnion:3.0.11
gRPC:grpc_unity_package.2.29.0-dev
Unity:2018.4.1f1

Server:
1.Run MagicOnion Sample ChatApp.Server

Client Build:
1.Run ChatApp.Unity in Unity
2.Install gRPC on Plugin
3.[Assets\Plugins\Grpc.Core\runtimes\grpc_csharp_ext_dummy_stubs.c] Edit
Add at the end

```
void dlopen() {
  fprintf(stderr, "Should never reach here");
  abort();
}
void dlerror() {
  fprintf(stderr, "Should never reach here");
  abort();
}
void dlsym() {
  fprintf(stderr, "Should never reach here");
  abort();
}
```

4.Standalone Il2cpp build

Confirm things:
1.Run Build App
2.gRPC connect. channnel state is Ready
3.Click [×] in the upper right window
4.App Freeze!!

Please Can you tell me how to avoid it?

**Comment by kubota62** [comment]
Problem solved
maybe 

add this code
```
async void OnApplicationQuit()
{
    await this.streamingClient.DisposeAsync();
}
```

**Comment by kubota62** [comment]
please confirm

**Comment by TheCactusBlue** [comment]
From readme.md:

```cs
    // dispose client-connection before channel.ShutDownAsync is important!
    public Task DisposeAsync()
    {
        return client.DisposeAsync();
    }
```
