### ISSUE TITLE
Unloading broken assembly ‘Google.Protobuf.dll’, this assembly can cause crashes in the runtime.

### ISSUE THREAD

**Issue by qq60665** [Cysharp/MagicOnion#296]
Hi, @mayuki @neuecc ,when I import the latest version of the gRPCs library (2.29.0-dev), the Unity client prompts "Unloading broken assembly Assets / Plugins / Google.Protobuf / lib / net45 / Google.Protobuf.dll, this assembly can cause crashes in the runtime", may I ask What causes it, do other friends know? Thanks
![QQ截图20200330011752](https://user-images.githubusercontent.com/24306962/77855664-665d4880-7224-11ea-9d20-ac447969ceae.png)

By the way, I have another question. There are three assemblies (System.Buffers.dll, System.Memory.dll and System.Runtime.CompilerServices.Unsafe.dll ) in the plugin folder in the "ChatApp.Unity" sample that conflict with the gRpcs library. Which side should I keep?

**Comment by mayuki** [comment]
This error is caused by the problem in gRPC Unity package. (https://github.com/grpc/grpc/issues/22251 , https://github.com/grpc/grpc/issues/21908)
If you are using gRPC with MagicOnion only, you can remove `Google.Protobuf` and avoid the problem.

**Comment by qq60665** [comment]
thanks @mayuki
