### ISSUE TITLE
General question on Magic Onion practical application as web-framework.

### ISSUE THREAD

**Issue by bitindicium** [Cysharp/MagicOnion#306]
Magic Onion can be used for non-realtime web-framework. Is it well suited for games that maintain a large amount of client side game state which is incrementally updated with server interaction? I could imagine ways to make this work, but they may not take advantage of Magic Onion's strengths.

For example, during game initialization we retrieve a collection of heroes. With Magic Onion, we can define a strongly typed response class for that initial retrieval. Hero instances are serialized automatically for us. When the player upgrades a hero, we return only the updated level for that hero. With Magic Onion, the response class is strongly typed and serialization is automatic, but to apply the changes to the hero state, we would need a system to located the hero and copy data out. Another option might be that the hero is always sent in full (or the dynamic subset of it) and downstream consumers (UI) accommodate the swapping.

This may be a simple system to implement, however I am wondering if this is an intended use of Magic Onion.

**Comment by mayuki** [comment]
MagicOnion is an RPC framework that works closely with the C# type system and relies on gRPC.
`Unary` RPC (`IService<T>`) as the GET or POST equivalent of the popular Web APIs and is intended to be used as a replacement for them.

However, MagicOnion only provides pure RPC and streaming, and it is up to the developers on how to handle and serialize the data.
For example, MagicOnion does not provide a mechanism to send a subset of Hero data.

**Comment by bitindicium** [comment]
Thank you. I understand. I will experiment with different approaches to serialization using Magic Onion.
