### ISSUE TITLE
サーバからクライアントにBroadcastするには

### ISSUE THREAD

**Issue by kyamamoto03** [Cysharp/MagicOnion#307]
こんにちは、MagicOnionを使いアプリを開発しています。
サーバからクライアントにBroadcastする方法はあるのでしょうか？
例えば、サーバの時間をJoinしているクライアントに定期的送るなどといった形です。

**Comment by TheCactusBlue** [comment]
はい、StreamingHubをReceiverで使用できます。

**Comment by kyamamoto03** [comment]
サーバでJoinしているユーザ一覧やRoom一覧の取得や特定のユーザにメッセージを送る場合はどのようにしたらいいでしょうか？

**Comment by mayuki** [comment]
Group という仕組みがあるのでそちらを利用することでブロードキャストできます。
https://github.com/Cysharp/MagicOnion#group-and-groupconfiguration

ただし、ユーザーの一覧を取得する仕組みはないため、その情報はアプリケーションで管理する必要があります。

**Comment by kyamamoto03** [comment]
なるほど。グループの管理や接続しているユーザなどの管理はMagicOnionではなく別のTCPなどの回線でやる必要があるというとこですか。

**Comment by mayuki** [comment]
別回線はなくても大丈夫です。

具体的にどうユーザーを管理、保持したいかというのはアプリケーションの要件にもよりますが、例えば1つのサーバーで完結する場合はインメモリで持つという方法があります。

```csharp
private static readonly ConcurrentDictionary<Guid, string> _userNameByConnection
    = new ConcurrentDictionary<Guid, string>();

async Task JoinAsync(string name)
{
    await Group.AddAsync("GroupName");
    _userNameByConnection[Context.ContextId] = name;
}

async Task LeaveAsync()
{
    await Group.RemoveAsync("GroupName");
    _userNameByConnection.Remove(Context.ContextId);
}
```

MagicOnion は接続ごとに ID を発行して、その 接続 (ID) に対するブロードキャストを制御する仕組み(Group)を持っていますが、接続がアプリケーションから見ると「何か」というの部分に関知していないので ID に対する「何か」の紐づけはアプリケーション側で実装する必要があります。

接続中のユーザー一覧が必要であれば上記のような static 変数や Redis のような仕組みが必要ですし、もしそういったものが必要なければ StreamingHub のインスタンスは接続ごとに作成されるので StreamingHub のインスタンス変数にデータ(例えばユーザーIDとか)を保持しておくこともできます。

**Comment by kyamamoto03** [comment]
StaticのListクラスを作成しJoinしたユーザを保存。
サーバの任意のタイミングでListクラスからJoinデータを取得し、メソッドを呼び出したところ、クライアントにPushすることが出来ました。
ありがとうございました。

**Comment by kyamamoto03** [comment]
StaticのListクラスを作成しJoinしたユーザを保存。
サーバの任意のタイミングでListクラスからJoinデータを取得し、メソッドを呼び出したところ、クライアントにPushすることが出来ました。
ありがとうございました。
