### ISSUE TITLE
Is it possible to pass more than one argument to a function in IL2CPP?

### ISSUE THREAD

**Issue by TheCactusBlue** [Cysharp/MagicOnion#311]
It seems to rely on DynamicArgumentTuple, which doesn't seem to function properly on IL2CPP, Due to issues with MessagePack.

**Comment by TheCactusBlue** [comment]
Also, same issue with calling a function with a List with a type argument - both of these issues can be circumvented by having a wrapper class.
Basically, none of the Dynamic Resolvers are working for unity, as shown in the README of https://github.com/neuecc/MessagePack-CSharp.

**Comment by neuecc** [comment]
Have you tried moc(MagicOnionCompiler)?

**Comment by TheCactusBlue** [comment]
I figured it out, I forgot to include MagicOnionResolver in my list of registered resolvers.
