### ISSUE TITLE
HttpGateway and Swagger under .NET Framework 4.6.1

### ISSUE THREAD

**Issue by andkorsh** [Cysharp/MagicOnion#313]
Is it possible to enable the HttpGateway along with Swagger under the "old" .NET Framework? I assume it needs some middleware (Owin?)? I was able to install the nuget but not sure what's the next step to turn it on.

**Comment by neuecc** [comment]
HttpGateway is netstandard2.0 and it depends "Microsoft.AspNetCore.Mvc.Abstractions"(same as netstandard 2.0).

**Comment by andkorsh** [comment]
Hey JFYI - I've added the support for OWIN Middleware in my own Fork, I have tested in with the very basic example (under .NET Framework Console App) and it seems to work just fine. To do that, I had to extract the AspNet.Core-related logic into a separate project MagicOnion.HttpGateway.AspNetCore and create a separate MagicOnion.HttpGateway.Owin targeting .NET Framework 4.7.2.

I think this might be a good addition for your library. This is the work-in-progress, but if you want me to, I can clean this up, add some test projects and usage documentations some time next week. Let me know if it makes any sense to you.

Here's a very simple usage example (can be hosted in IIS or in the console app using Microsoft.Owin.Host.HttpListener):

```C#
    class Startup1
    {
        public void Configuration(IAppBuilder app)
        {
            // Optional:Add Summary to Swagger
            // var xmlName = "Sandbox.NetCoreServer.xml";
            // var xmlPath = Path.Combine(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location), xmlName);
            // HttpGateway requires two middlewares.
            // One is SwaggerView(MagicOnionSwaggerMiddleware)
            // One is Http1-JSON to gRPC-MagicOnion gateway(MagicOnionHttpGateway)
            app.UseMagicOnionSwagger(Program.MagicOnionServiceDefinition.MethodHandlers, new SwaggerOptionsOwin("MagicOnion.Server", "Swagger Integration Test", "/")
            {
                // XmlDocumentPath = xmlPath
            });
            app.UseMagicOnionHttpGateway(Program.MagicOnionServiceDefinition.MethodHandlers, new Channel("localhost:12345", ChannelCredentials.Insecure));
        }
    }
```
