### ISSUE TITLE
Hololens2での動作

### ISSUE THREAD

**Issue by kyamamoto03** [Cysharp/MagicOnion#315]
Hololens2(Snapdragon)でMagicOnionを使うとエラーが発生するのですが(x86Windowsでは正常に動作しています）やはりサポート外なのでしょうか？

**Comment by mayuki** [comment]
Hololens 2 での動作は確認していませんが、gRPC のネイティブライブラリが現状 Windows の ARM32/64 に対応していないため動作しないのではないかと思います。

**Comment by kyamamoto03** [comment]
やはり。
回答ありがとうございました。
