### ISSUE TITLE
[Info]Working MagicOnion in production environment.

### ISSUE THREAD

**Issue by neuecc** [Cysharp/MagicOnion#32]
My company's new game - https://kuro-kishi.jp/ released in iOS/Android market on 28th, April.

Currently it receives 15,000 connections at peak time and it is growing.
Our system has two roles.

* Service - Unary API Service/Realtime notification, with Redis pubsub backend
* BattleEngine - Inmemory battle logic server, it is MORPG's playground(1~8 players per field).

We're monitoring application metrics by Datadog.
I've created Datadog C# Client.
https://github.com/neuecc/DatadogSharp

![image](https://cloud.githubusercontent.com/assets/46207/25664540/e1848640-3055-11e7-9cea-683cc554016e.png)

![image](https://cloud.githubusercontent.com/assets/46207/25664543/e3db9fe6-3055-11e7-8863-c74b54487369.png)

I'll talk about this architecture at AWS Summit Tokyo 2017 on 2017-05-30~06-02.
http://www.awssummit.tokyo/
When talk is done, I'll upload translated presenation slide.

And of course, I will start working on .NET Standard and other improvements.

**Comment by kimsama** [comment]
Great job! Waiting the slide. 

I have a question: 

About one of the servers, BattelEngine, you've mentioned. 

Is that runs on connection based? Which means, is that keep all connections during of a battle is going? 

Just wander about that you've used gRPC as connection based protocol. 

Best, 

-Kim

**Comment by neuecc** [comment]
Slide of AWS Summit Tokyo and details of BattleEngine server-side gameloop.
http://engineering.grani.jp/entry/2017/06/02/190012

There are not translated yet(written in Japanese).

**Comment by psibernetic** [comment]
Very much interested in translated slides or metrics!

**Comment by parkycai** [comment]
Hi @neuecc , I'm trying to find out a suitable way to implement token authentication in MagicOnion.  I've used LightNode in my previous project, and it's done by using Filters and storing token in headers. It seems grpc hasn't implemented interceptor in csharp version. Do you have any suggestions for implementing token authentication?
Thanks for the great project :)
