### ISSUE TITLE
Unity generated exception

### ISSUE THREAD

**Issue by zzragida** [Cysharp/MagicOnion#33]
I tried unity project generate but not working.
error messages to below.

environment
- Unity 2017.1.0f1(.net 3.5) or Unity 5.6.2f1
- MagicOnionGenerate from github project

==============================================================
D:\library\Unity\MagicOnion\src\MagicOnion.CodeGenerator\bin\Debug\moc.exe --input=
GRPC-Client.csproj --output=Assets\Scripts\MagicOnion\MagicOnionGenerated.cs
Project Compilation Start:GRPC-Client.csproj
Project Compilation Complete:00:00:04.0922816

Method Collect Start

처리되지 않은 예외: System.Exception: Invalid Return Type, method:.cctor returnT
ype:void
   위치: MagicOnion.CodeAnalysis.MethodCollector.ExtractRequestResponseType(IMet
hodSymbol method, MethodType& methodType, String& requestType, String& responseT
ype, ITypeSymbol& unwrappedOriginalResponseType) 파일 D:\library\Unity\MagicOnio
n\src\MagicOnion.CodeGenerator\CodeAnalysis\MethodCollector.cs:줄 187
   위치: MagicOnion.CodeAnalysis.MethodCollector.CreateMethodDefinition(IMethodS
ymbol y) 파일 D:\library\Unity\MagicOnion\src\MagicOnion.CodeGenerator\CodeAnaly
sis\MethodCollector.cs:줄 123
   위치: System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   위치: System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   위치: System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   위치: MagicOnion.CodeAnalysis.MethodCollector.<Visit>b__8_0(INamedTypeSymbol
x) 파일 D:\library\Unity\MagicOnion\src\MagicOnion.CodeGenerator\CodeAnalysis\Me
thodCollector.cs:줄 73
   위치: System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   위치: System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()
   위치: System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   위치: System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   위치: MagicOnion.CodeAnalysis.MethodCollector.Visit() 파일 D:\library\Unity\M
agicOnion\src\MagicOnion.CodeGenerator\CodeAnalysis\MethodCollector.cs:줄 72
   위치: MagicOnion.CodeGenerator.Program.Main(String[] args) 파일 D:\library\Un
ity\MagicOnion\src\MagicOnion.CodeGenerator\Program.cs:줄 93

**Comment by neuecc** [comment]
Thank you for try to use.
Hmn, could you show target class?

**Comment by zzragida** [comment]
sure below that

IMyFirstService.cs
===================================================
using MagicOnion;

namespace FooSample
{
    public interface IMyFirstService : IService<IMyFirstService>
    {
        UnaryResult<string> SumAsync(int x, int y);
    }
}

additionally my project folder
![image](https://user-images.githubusercontent.com/4442732/28705843-94fb4fc6-73ac-11e7-9813-194325fb8fe2.png)

**Comment by neuecc** [comment]
thanks, I've find if exists invalid class, can not generate.
I'll fix it but quick solution, separete service definition
https://github.com/neuecc/MagicOnion#project-structure and pass `ServiceDefinition.csproj`.

**Comment by zzragida** [comment]
thanks. i will try service project seperate.

**Comment by zzragida** [comment]
additionally i tried generate separate definition project and add method.
then same issue

D:\library\Unity\MagicOnion\src\MagicOnion.CodeGenerator\bin\Debug\moc.exe --input=ServiceDefin
tion\ServiceDefintion.csproj --output=GRPC-Client\Assets\Scripts\MagicOnionGenerated.cs
Project Compilation Start:ServiceDefintion\ServiceDefintion.csproj
Project Compilation Complete:00:00:06.3494738

Method Collect Start

처리되지 않은 예외: System.Exception: Invalid Return Type, method:SumLegacyTaskA
sync returnType:System.Threading.Tasks.Task<MagicOnion.UnaryResult<string>>
   위치: MagicOnion.CodeAnalysis.MethodCollector.ExtractRequestResponseType(IMet
hodSymbol method, MethodType& methodType, String& requestType, String& responseT
ype, ITypeSymbol& unwrappedOriginalResponseType) 파일 D:\library\Unity\MagicOnio
n\src\MagicOnion.CodeGenerator\CodeAnalysis\MethodCollector.cs:줄 187
   위치: MagicOnion.CodeAnalysis.MethodCollector.CreateMethodDefinition(IMethodS
ymbol y) 파일 D:\library\Unity\MagicOnion\src\MagicOnion.CodeGenerator\CodeAnaly
sis\MethodCollector.cs:줄 123
   위치: System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   위치: System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   위치: System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   위치: MagicOnion.CodeAnalysis.MethodCollector.<Visit>b__8_0(INamedTypeSymbol
x) 파일 D:\library\Unity\MagicOnion\src\MagicOnion.CodeGenerator\CodeAnalysis\Me
thodCollector.cs:줄 73
   위치: System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   위치: System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()
   위치: System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   위치: System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   위치: MagicOnion.CodeAnalysis.MethodCollector.Visit() 파일 D:\library\Unity\M
agicOnion\src\MagicOnion.CodeGenerator\CodeAnalysis\MethodCollector.cs:줄 72
   위치: MagicOnion.CodeGenerator.Program.Main(String[] args) 파일 D:\library\Un
ity\MagicOnion\src\MagicOnion.CodeGenerator\Program.cs:줄 93


IMyFirstService.cs
========================================================
using MagicOnion;
using System.Threading.Tasks;

namespace FooSample
{
    public interface IMyFirstService : IService<IMyFirstService>
    {
        UnaryResult<string> SumAsync(int x, int y);
        Task<UnaryResult<string>> SumLegacyTaskAsync(int x, int y);
        Task<ClientStreamingResult<int, string>> ClientStreamingSampleAsync();
        Task<ServerStreamingResult<string>> ServerStreamingSampleAsync(int x, int y, int z);
        Task<DuplexStreamingResult<int, string>> DuplexStreamingSampleAsync();
    }
}

**Comment by zzragida** [comment]
additionally more information to below
can not initialize ReferenceSymbols.cs INamedTypeSymbols
- Task
- TaskOfT
- GenerateDefineIf

![image](https://user-images.githubusercontent.com/4442732/29103528-0a47da04-7cfb-11e7-84ab-f20fb52307bc.png)

**Comment by neuecc** [comment]
Is your project type new csproj?

**Comment by zzragida** [comment]
Yes seperated new project.
Can i append project to solution?

**Comment by neuecc** [comment]
Sorry, new means VS2017's new csproj structure.

**Comment by zzragida** [comment]
Yes. that is VS2017's new csproj structure
