### ISSUE TITLE
Service methods support overload?

### ISSUE THREAD

**Issue by 0xF6** [Cysharp/MagicOnion#333]
Are you planning to add support for overloaded functions? 
Or will it be overly slow performance?

```
System.InvalidOperationException: Method does not allow overload
   at MagicOnion.Server.MagicOnionEngine
```

**Comment by neuecc** [comment]
Currently no planned.
Overload is not supported by gRPC, so MagicOnion's own additional binary checks are required.
This breaks compatibility, code complexity, and performance.
