### ISSUE TITLE
Integration inside ASP.NET Core server.

### ISSUE THREAD

**Issue by JinsPeter** [Cysharp/MagicOnion#335]
This issue is primarily a set of questions..
I noticed that the server Swagger implementation works with an ASP.NET Core Api gateway. If I understand correctly, This runs an ASP. NET Server with Magic onion on the same console app.

I have a few questions.
1. Can I have MagicOnion streaming hub running as a hosted service in an ASP.NET Core App. I will need to use the Redis backplane too.
2. If not, Can I use the same mechanism as the swagger implementation to have a fully functional ASP.NET Core Web API server running in one host and server to client messages handled by MagicOnion's streaming hub.
3. Can I use a .NET Framework client like I can do in plain gRPC. 
I'm evaluating Magic Onion over plain gRPC for the Redis backplane and distributed servers. Would that be a right choice.?

**Comment by mayuki** [comment]
MagicOnion v2 Swagger API Gateway server runs on a single console application, but MagicOnion runs on a separate GenericHost from ASP.NET Core. Therefore, the services (`IServiceProvider`) are not shared between the gateway and the server.

The Swagger API Gateway server is a kind of MagicOnion client that proxy for HTTP/1 clients. It also means that you can run it on a different server.

- **NOTE:** The next version will be fully integrated with ASP.NET Core.

> 1. Can I have MagicOnion streaming hub running as a hosted service in an ASP.NET Core App. I will need to use the Redis backplane too.

The Redis backplane is needed when you want to distribute group messages across multiple servers. 

If an application on MagicOnion needs to communicate with an application on ASP.NET Core, then it needs to either provide a bridging service or a MagicOnion (gRPC) client as same as a Swagger API Gateway server.

> 3. Can I use a .NET Framework client like I can do in plain gRPC.
I'm evaluating Magic Onion over plain gRPC for the Redis backplane and distributed servers. Would that be a right choice.?

MagicOnion client is available in the .NET Framework (and Unity).
We believe that MagicOnion is a good choice for a unified, distributed C# server environment.

**Comment by ogswr** [comment]
> * **NOTE:** The next version will be fully integrated with ASP.NET Core.
Which means we can fully integrate MO with Identity Server4 using general annotations like Authorize?
When that will be available for us and do you think it has production-ready stability?
Currently the combination of proto and il2cpp have some troubles and which requires additional ugly hacks you know that i don't want.

Thanks.

**Comment by JinsPeter** [comment]
@mayuki  Do you have streaming hub example you can point me to?
The ChatHub sample is not fully implemented it seems.

**Comment by JinsPeter** [comment]
Also, One of the most useful use case of a streaming hub in an application is to call a client method from server.
I have the below app.
**My Type defenitions**
```csharp
[MessagePackObject]
public class JoinRequest 
{
    [Key(0)]
    public string ClientAppIdentifier{ get; set; }
}

public class SomeMessageType 
{
    [Key(0)]
    public string Message { get; set; }
}

public interface IAmClient
{
     void OnRecieveMessage(SomeMessageType message);
}

public interface IAmStreamingServer : IStreamingHub<IAmStreamingServer, IAmClient>
{
    Task Join (JoinRequest joinRequest);

    Task SendMessageToClient(SomeMessageType message);
}

public interface IDoSomething 
{
        Task StartExternalListener();
}

``` 
**My Streaming hub server**
```csharp
    public class Program
    {
        static async Task Main(string[] args)
        {
            await MagicOnionHost.CreateDefaultBuilder()
                .UseMagicOnion()
               .ConfigureServices((hostContext, services) =>
               {
                   services.AddSingleton<IDoSomething, MyWorkerService>();
                })
                .RunConsoleAsync();
        }
    }

public MyWorkerService() : IDoSomething()
{
    public async Task StartExternalListener()
     {
        // This code listen Some external service and notify the client according to its progress.
     }
}
public class MyStreamingServer : StreamingServerBase<IAmStreamingServer, IAmClient>, IAmStreamingServer
{
   private IGroup room;
   
   public async Task Join(JoinRequest joinRequest)
   {
      this.room = await  Group.AddAsync(joinRequest.ContextualGroupName);  
   }
  
   public async Task SendMessageToClient(SomeMessageType message)
   {
      Broadcast(room).OnRecieveMessage(message);
   }
}
```
**My Client App**
```csharp 

   public class StreamClient : IAmClient
    {
        public voidOnRecieveMessage(SomeMessageType message)
        {
            Console.WriteLine($"Message:{message} ");
        }
    }

   class Program
    {
        static async Task Main(string[] args)
        {
            await Start();
        }

        static async Task  Start()
        {
            var channel = new Channel("localhost", 12345, ChannelCredentials.Insecure);
            var streamingClient = StreamingHubClient.Connect<IAmStreamingServer, IAmClient>(channel, new StreamClient());

            await streamingClient.Join(new JoinRequest ()
            {
               ClientAppIdentifier = "ClientApp"
            });
           await RegisterDisconnectEvent(streamingClient);
        }

        private async Task RegisterDisconnectEvent(INotificationHub streamingClient)
        {
            try
            {
                await streamingClient.WaitForDisconnect();
            }
            finally
            {
                Console.Write("disconnected server.");
            }
        }
    }

```

The above is be sample Streaming server-client Implementation.
I want to be able to call the `SendMessageToClient(SomeMessageType message)` of Hub for one specific client of many connected clients from the `MyWorkerService` class of the Streaming Server. 
How would I do that?

**Comment by JinsPeter** [comment]
Another question I have from the above scenario is, If I want to use Redis Backplane for server scaleout. What would I add?
MagicOnion/ ReadMe says to add
**Part 1**
```csharp
[GroupConfiguration(typeof(RedisGroupRepositoryFactory))]
public class MyStreamingServer
{
}
```
and 

**Part 2**
```csharp
// configure ConnectionMultiplexer(StackExchange.Redis) to MagicOnionOption.ServiceLocator
var option = new MagicOnionOption();
option.ServiceLocator.Register(new ConnectionMultiplexer(...));
```
But the second part is nowhere found in the above example? Do I need to do that?

**Comment by JinsPeter** [comment]
@mayuki  @neuecc 
Anyone who know the answers to above, please share

**Comment by mayuki** [comment]
Sorry, we don't have a release date for the next version, but we're targeting in the coming months.

MagicOnion vNext targets to integrate ASP.NET Core in the hosting model. Support for Authorize and other features may be available in later versions (vNext + N).

**Comment by JinsPeter** [comment]
Thanks for that update..
What about [https://github.com/Cysharp/MagicOnion/issues/335#issuecomment-664614740](question 1)  and [https://github.com/Cysharp/MagicOnion/issues/335#issuecomment-664618341] (question2)

**Comment by mayuki** [comment]
If you want to send a message from outside the Hub, you can create a broadcast receiver and pass it on to an external service class.

```csharp
// The StreamingHub is instantiated for each connection.
public class MyHub : StreamingHubBase<IMyHub, IMyHubReceiver>, IMyHub
{
    private readonly MyWorkerService _workerService;
    private readonly ConcurrentDictionary<string, IGroup> _groupByChannel = new ConcurrentDictionary<string, IGroup>();

    public MyHub(MyWorkerService workerService)
    {
        _workerService = workerService ?? throw new ArgumentNullException(nameof(workerService));
    }

    public async Task JoinAsync(string channel)
    {
        var group = await Group.AddAsync(channel);
        _groupByChannel[channel] = group;
        _workerService.Register(channel, Broadcast(_group));
    }

    public async Task SendMessageAsync(string channel, string message)
    {
        Broadcast(_groupByChannel[channel]).OnMessageReceived(channel, message);
    }
}

public interface IMyHub : IStreamingHub<IMyHub, IMyHubReceiver>
{
    Task JoinAsync();
    Task SendMessageAsync(string channel, string message);
}

public interface IMyHubReceiver
{
    void OnMessageReceived(string channel, string message);
}

// Add `services.AddHostedService<MyWorkerService>();` in ConfigureServices method.
public class MyWorkerService : IHostedService
{
    private readonly CancellationTokenSource _cts = new CancellationTokenSource();
    private readonly ConcurrentDictionary<string, IMyHubReceiver> _broadcastReceivers = new ConcurrentDictionary<string, IMyHubReceiver>();

    private Task _runLoopTask;

    public Task StartAsync(CancellationToken cancellationToken)
    {
        _runLoopTask = RunAsync();
    }

    private async Task RunAsync()
    {
        while (!_cts.IsCancellationRequested)
        {
            // Send a message every second.
            foreach (var (channel, broadcastReceiver) in _broadcastReceivers)
            {
                broadcastReceiver.OnMessageReceived(channel, DateTimeOffset.Now.ToString());
            }

            await Task.Delay(1000);
        }
    }

    public void Register(string channel, IMyHubReceiver broadcastReceiver)
    {
        _broadcastReceivers.Add(channel, broadcastReceiver);
    }

    public async Task StopAsync(CancellationToken cancellationToken)
    {
        _cts.Cancel();

        if (_runLoopTask != null)
        {
            await _runLoopTask;
        }
    }
}
```

If you use the Redis backplane in this example, MyWorkerService needs to run on a single server somewhere.
If MyWorkerService runs on more than one server, then multiple messages from the external service class will be sent to clients.

This is because messages sent by broadcast receivers are delivered to all clients via Redis.

The Redis backplane is only used to deliver messages to the Group. If you need server-to-server communication, I recommend that you have a PubSub channel.

> Q.2

The factory of GroupRepository can also be changed in the `MagicOnionOptions` settings.
For example, if you are using Redis backed group repository, you can use the following code.

```csharp
options.DefaultGroupRepositoryFactory = new RedisGroupRepositoryFactory(new RedisGroupOptions(...));
```

**Comment by JinsPeter** [comment]
>`options.DefaultGroupRepositoryFactory = new RedisGroupRepositoryFactory(new RedisGroupOptions(...));`

There is no constructor for RedisGroupRepositoryFactory which take any argument, let alone one of type RedisGroupOptions.

Anyway I tries thee below code in Program.cs

``` csharp
     class Program
    {
        static async Task Main(string[] args)
        {
             ConnectionMultiplexer connectionMultiplexer = ConnectionMultiplexer.Connect("localhost:6379");
             DefaultServiceLocator defaultServiceLocator = DefaultServiceLocator.Instance;
             defaultServiceLocator.Register<ConnectionMultiplexer>(connectionMultiplexer);

             MagicOnionOptions options = new MagicOnionOptions(false)
             {
                 ServiceLocator = defaultServiceLocator
             };

             await MagicOnionHost.CreateDefaultBuilder()
                .UseMagicOnion(options,new ServerPort("localhost",12345, ServerCredentials.Insecure))
                .ConfigureServices((hostBuilder, services) =>
                {
                    services.AddHostedService<MyWorkerService>();
                })
                .RunConsoleAsync();
        }
    }

```

This gives me an error saying
RedisGroup requires add ConnectionMultiplexer to MagicOnionOptions.ServiceLocator before create it. Please try new MagicOnionOptions{DefaultServiceLocator.Register(new ConnectionMultiplexer)}'

What to do?

**Comment by mayuki** [comment]
Sorry, there were no constructor arguments in the current version. How about the following code?

```csharp
var conn = ConnectionMultiplexer.Connect("localhost:6379");

await MagicOnionHost.CreateDefaultBuilder()
    .UseMagicOnion()
    .ConfigureServices((hostContext, services) =>
    {
        services.AddSingleton(new RedisGroupOptions(conn));

        services.Configure<MagicOnionHostingOptions>(options =>
        {
            options.Service.DefaultGroupRepositoryFactory = new RedisGroupRepositoryFactory();
        });
    })
    .RunConsoleAsync();
```
