### ISSUE TITLE
Service hot update

### ISSUE THREAD

**Issue by parkycai** [Cysharp/MagicOnion#34]
I'm using LightNode in my previous project (thanks again!). By adding following code into LightNodeServerMiddleware.cs, I was able to update the handler assembly during runtime

![image](https://user-images.githubusercontent.com/22512293/28911930-bb9887ae-7864-11e7-8389-bf73fd8dedc4.png)

I wonder if there's any similar approach in MagicOnion.

**Comment by neuecc** [comment]
Thank you! and very interesting.

Maybe, it is related to `Grpc.Core.Server`.
I can only think of the following way.
`server.Kill` -> `new Server(MagicOnionServiceDefinition)`  -> `server.Start`

**Comment by parkycai** [comment]
Kill the server will cause a disconnection to the client. or will the client automatically restore the connect, even the stream connection won't notice the disconnection?
Anyway, I guess I have to dive into Grpc Server to find out a way to replace logic assemble during runtime. Thanks!

**Comment by parkycai** [comment]
Hi, I took some time this weekend and dig out the approach. I used some reflections so no need to modify the `grpc` source.
![image](https://user-images.githubusercontent.com/22512293/33802564-158a4fda-ddb5-11e7-8dff-10fe86f563ab.png)

Note:

1.  Assemblies can be loaded from raw binary dll files, so it can be overwritten in runtime.
2.  Remember to clean up old assemblies after the update.

**Comment by psibernetic** [comment]
@parkycai Problem you will run into is unloading assemblies is only supported through unloading entire AppDomains. It is a Framework only feature (not core) and very complicated.

**Comment by parkycai** [comment]
@psibernetic agreed. By "clean up old assemblies" I means dispose any resources used by the assemblies. So this is a comprimise, that I don't need to make any inter-appdomain communication but only waste acceptable amount of memory.
