### ISSUE TITLE
Type MyService has no implementation of interface ''."

### ISSUE THREAD

**Issue by gitwolflow** [Cysharp/MagicOnion#348]
Hi!

With this pattern:

// the special service
public interface ITypeService : IService<ITypeService>, IServiceMarker
{ ... }

// the Service Implementation
public class BackgroundRepository : BackgroundService<Model, IITypeService>, IITypeService 
{ ... }

// ServiceBase Construct
public class BackgroundService<TModel, TService> : ServiceBase<TService> where TService : IServiceMarker
{ ... }

I get during launch: 
Type 'BackgroundService' has no implementation of interface ''."

What does MagicOnion.Server.MagicOnionEngine.BuildServerServiceDefinition(System.Collections.Generic.IEnumerable<System.Type>, MagicOnion.Server.MagicOnionOptions)
need in addition.

Is the above construct even possible?

**Comment by mayuki** [comment]
The problem is caused by MagicOnion recognizing a `BackgroundService<TModel, TService>` with a generic parameter as a service.
You can solve the problem by marking the class as `abstract`.
