### ISSUE TITLE
Is there a "middleware" in client side?

### ISSUE THREAD

**Issue by parkycai** [Cysharp/MagicOnion#35]
Say, I want to check every call to the server that if  `StatusCode.Unauthenticated` is returned, I can popup a login window for the user. 
How to do it correctly? Thanks!

**Comment by neuecc** [comment]
in client side, you may can hook by gRPC's default mechanism - `CallInvoker`.

**Comment by parkycai** [comment]
Thanks very much! It does exactly what I expected! Cheers

**Comment by parkycai** [comment]
In my custom CallInvoker,  I can subscribe to `call.ResponseAsync` of `AsyncUnaryCall` and `AsyncClientStreamingCall` to monitor `StatusCode`. But since `AsyncServerStreamingCall` and `AsyncDuplexStreamingCall` don't have `ResponseAsync`, and `ResponseHeaderAsync` seems to complete before call finishes, I can't find a way to monitor these two types of call. Any idea? 
Thanks

**Comment by parkycai** [comment]
Looks like `Interceptor` is the best way to do it, but is not implemented in C#.

**Comment by neuecc** [comment]
Interceptor is now supported on official gRPC C#.
