### ISSUE TITLE
How many players per server can a single MagicOnion node support with StreamingHubs?

### ISSUE THREAD

**Issue by TheCactusBlue** [Cysharp/MagicOnion#350]
Hello, I'd like to ask about how much concurrent player capacity I can expect from a single MagicOnion server, using StreamingHubs. Thank you very much in advance!

**Comment by neuecc** [comment]
It follows the gRPC Bidirectional perf.
gRPC's benchmark is opened usually Unary but Bidirectional is unknown.

(For example. .NET 5's Unary req/sec)

![image](https://user-images.githubusercontent.com/46207/93053309-99947680-f6a2-11ea-84e6-55c915a76de0.png)

MagicOnion is trying to move grpc-dotnet
and preparing load testing framework - DFrame https://github.com/Cysharp/DFrame/
So when achieve both, will measure peformance.

**Comment by TheCactusBlue** [comment]
Thank you very much for your insightful comment. Another question I want to ask is if it is advisable to hold a DbContext in a StreamingHub, as that could end up exhausting the connection pool - are there any ways you would recommend about going so?

**Comment by mayuki** [comment]
I recommend not holding a DbContext in a StreamingHub.

If you need a DbContext, you can use IServiceProvider to create a scope and create a DbContext.

**Comment by TheCactusBlue** [comment]
@mayuki Thanks for the answer, things are performing much better now - are Services normally scoped as well, or should I manually scope these?

**Comment by mayuki** [comment]
Services are scoped on a per-Unary call request.
StreamingHubs also has scope, but it will continue to do so until the client is disconnected (which means it has a very long lifetime).
