### ISSUE TITLE
Question StreamingHub does not support DI or it needs custom implementation?

### ISSUE THREAD

**Issue by Speed258** [Cysharp/MagicOnion#352]
Hello, I'm want to use DI in my StreamingHub, but once I include my service, client crash with Task was canceled exception, code below with:

`public static async Task Main(string[] args)
        {
           // CreateHostBuilder(args).Build().Run();
            // setup MagicOnion hosting.
            var magicOnionHost = MagicOnionHost.CreateDefaultBuilder()
                .UseMagicOnion()
                .UseConsoleLifetime()
                .Build();

            // NuGet: Microsoft.AspNetCore.Server.Kestrel
            var webHost = CreateHostBuilder(args)
                .ConfigureServices((hostContext,collection) =>
                 {
                 // Add MagicOnionServiceDefinition for reference from Startup.
                     //collection.AddSingleton<MagicOnionServiceDefinition>(magicOnionHost.Services.GetService<MagicOnionHostedServiceDefinition>().ServiceDefinition);
                     collection.AddSingleton(magicOnionHost.Services.GetService<MagicOnionHostedServiceDefinition>().ServiceDefinition);
                     collection.AddScoped<IUserService, UserService>();
                 })

                .Build();

            // Run and wait both.
            await Task.WhenAll(webHost.RunAsync(), magicOnionHost.RunAsync());

        }`

and Hub code:
`public class ApplicationHub : StreamingHubBase<IClientSender, IClientReceiver>, IClientSender
    {
        private IUserService _userService;
        public ApplicationHub(IUserService userService)
        {}`

If I comment out (IUserService userService) client connects, if I uncomment client receive exception mentioned above, do magiconion hub does not support DI or does it need add DI services somewhere else? Thanks.

**Comment by mayuki** [comment]
I assume the problem is caused by the service not being registered in MagicOnion.

DI container of ASP.NET Core host is separate from MagicOnion host's, and you need to register your services in DI container of MagicOnion host.

```csharp
var magicOnionHost = MagicOnionHost.CreateDefaultBuilder()
    .UseMagicOnion()
    .ConfigureServices(services =>
    {
        services.AddScoped<IUserService, UserService>();
    })
    .UseConsoleLifetime()
    .Build();
```
