### ISSUE TITLE
.NET Framework Compatibility

### ISSUE THREAD

**Issue by CaiB** [Cysharp/MagicOnion#353]
Hello,

I'm trying to use the MagicOnion NuGet package with a project that, due to other requirements, must use .NET Framework (v4.0 or higher). When trying to install the package, I get the following error:

> Could not install package 'MagicOnion 3.0.13'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

The [Quick Start section in the MagicOnion readme](https://github.com/Cysharp/MagicOnion#quick-start) states
> for .NET 4.6, 4.7 and .NET Standard 2.0(.NET Core) available in NuGet.

Is there an option or something I need to set in NuGet to make this work?

Furthermore, I'd like to verify that I can use MagicOnion between a server and clients running on different .NET platforms (some .NET Core, some .NET Framework)?

Thank you!

**Comment by mayuki** [comment]
Sorry, some of the descriptions in the README are incorrect.

NET Standard 2.0 is required to run MagicOnion, but .NET Framework 4.6 is not .NET Standard 2.0.
This means that .NET Framework 4.6.1 or later version is required to work.

**Comment by CaiB** [comment]
Ah, that was simple. Switching to .NET Framework 4.6.1 allows me to install without issue.

Thank you!
