### ISSUE TITLE
Missed Python+Swagger example

### ISSUE THREAD

**Issue by OlegJakushkin** [Cysharp/MagicOnion#355]
I wanted a Python client for my C# web\server. Obviously grpc+msgpack sample would be great, yet it seems too much work for me, and protocol wrapping\generation is not clear. Thus Swagger seems to be the fastest option. So I created an example of [MagicOnion+Swagger+Python  here.](https://github.com/OlegJakushkin/MagicOnion-Blazor-MaterialUI-Python-Swagger-101)

Notes:
Swagger Python generators somehow tend to create bad\incomplete code from swagger autogenerated  by MagicOnion, so one has to:
 - use on-the-fly protocol wrapper code generation e. g. [bravado](https://github.com/Yelp/bravado) 
 - in combination with `config['validate_swagger_spec'] = False` 
 - had to use debugger to look at how and what is named (service member names, options)

**Comment by mayuki** [comment]
Thanks for the great example!

At the moment we have no official plans to add support for Python (client, sample, etc...), but a guide by the community should be helpful for those who need it.
