### ISSUE TITLE
Serverside gameloop question

### ISSUE THREAD

**Issue by dre0dru** [Cysharp/MagicOnion#357]
Found that [issue](https://github.com/Cysharp/MagicOnion/issues/119) that seems like gameloop support was added back in version 2.2, but I couldn't find any code that is related to gameloop. Or was this idea dropped?
If it was, whats the best practice to inject custom gameloop logic inside MO server? Use own service and just inject it into hub?
More on why am I asking. I want to accomplish several things:
1. Build some authorative server logic for relatively fast real-time multiplayer with low players count (2-4).
2. Explore magiconion as a whole. Use cases, connecting to DB, cloud hosting, scaling etc. 
3. Just learn how multiplayer games work in general with all things like reconciliation, interpolation, lag compensation, etc.
4. This is a study project, not something for production.

**Comment by mayuki** [comment]
The server-side game loop mechanism has been separated as a separate project.
You can find the repository here. https://github.com/Cysharp/LogicLooper

We're sorry, at this time we don't have sample code for real-time game logic with MagicOnion's StreamingHub. 
We plan to have a sample project in the future.
