### ISSUE TITLE
vNext, compatibility with .NetFramework client

### ISSUE THREAD

**Issue by wahmedswl** [Cysharp/MagicOnion#365]
Hi, will vNext will be compatible with .Net Framework client or it will also target .NetCore only?

Thanks

**Comment by mayuki** [comment]
The MagicOnion server requires .NET Core 3.1 or .NET 5.0.
But the client library still supports a wide range of platforms, from .NET Framework 4.6.1 to .NET 5.0 and Unity.

**Comment by wahmedswl** [comment]
@mayuki that's awesome 👍
