### ISSUE TITLE
Use custom Models?

### ISSUE THREAD

**Issue by starteNCS** [Cysharp/MagicOnion#372]
Hi,

I am trying to implement the rpc framework into my existing project with existing models. Can I, and if so how do I use my existing models in both of my c# web apis?
If I try to just copy my model in both of my apis I get this error:
`MessagePack.MessagePackSerializationException: Failed to serialize DieseAndereApi.Services.Model value.
 ---> MessagePack.FormatterNotRegisteredException: DieseAndereApi.Services.Model is not registered in resolver: MessagePack.Resolvers.StandardResolver`

**Comment by neuecc** [comment]
Custom Models will serialize by [MessagePack-CSharp](https://github.com/neuecc/MessagePack-CSharp/)
Maybe your `DieseAndereApi.Services.Model` does not marked `[MessagePackObject]`.
Also you can use `MessagePack.Resolvers.ContractlessStandardResolver.Options` to `MagicOnionOptions`.

**Comment by starteNCS** [comment]
Thank you for your fast response :)
