### ISSUE TITLE
DI for IGroupRepository

### ISSUE THREAD

**Issue by shersh** [Cysharp/MagicOnion#381]
I need to Broadcast message for group of connected users to group outside of StreamingHub. 
For example in asp net controller.

Is it implemented already?

In SinglaR it's similar as injection of HubContext where it is needed.

**Comment by mayuki** [comment]
Sorry, MagicOnion does not currently have `HubContext` equivalent.
You must create your own PubSub channel or keep the BroadcastReceiver.
