### ISSUE TITLE
"Request protocol 'HTTP/1.1' is not supported."

### ISSUE THREAD

**Issue by xracer007** [Cysharp/MagicOnion#382]
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Request protocol 'HTTP/1.1' is not supported.")

get this error on xamarin.forms as client side

**Comment by mayuki** [comment]
Currently, Xamarin does not support grpc-dotnet (pure-C#), so you need to use Grpc.Core (C-core binding library).
https://docs.microsoft.com/en-us/aspnet/core/grpc/client?view=aspnetcore-3.1#client-performance

```csharp
// WORKAROUND: Grpc.Net.Client (pure-C# gRPC client) is currently not working on Xamarin. Use Grpc.Core instead.
var channel = new Grpc.Core.Channel("10.0.2.2", 5000, ChannelCredentials.Insecure);
var client = MagicOnionClient.Create<IGreeterService>(channel.CreateCallInvoker());
```
