### ISSUE TITLE
How to switch GrpcChannel dynamically in IClientFilter?

### ISSUE THREAD

**Issue by zqlovejyc** [Cysharp/MagicOnion#385]

**Comment by mayuki** [comment]
You cannot switch the client's `Channel` (`CallInvoker`) with `IClientFilter`.
`IClientFIlter` is tied to `MagicOnionClient`, and `MagicOnionClient` is tied to the `Channel` (`CallInvoker`).

Please create a MagicOnionClient instance for each purpose.

**Comment by zqlovejyc** [comment]
> You cannot switch the client's `Channel` (`CallInvoker`) with `IClientFilter`.
> `IClientFIlter` is tied to `MagicOnionClient`, and `MagicOnionClient` is tied to the `Channel` (`CallInvoker`).
> 
> Please create a MagicOnionClient instance for each purpose.

I want to switch the unreachable `Grpcchannel` in `IClientFilter`. Is there any good solution?
