### ISSUE TITLE
A client sdk getting falsely picked up as a server service through reflection.

### ISSUE THREAD

**Issue by mshipley** [Cysharp/MagicOnion#387]
I have a server (A) that also acts as a client to a different magic onion server (B). When I bring in the SDK to connect to the server B, server A finds the interface through reflection and tries to register it as a service on server A.

The simplest work around I have for it is this:
![image](https://user-images.githubusercontent.com/1933170/101542762-1d839500-3958-11eb-9c03-034f153f97c5.png)

**Comment by mayuki** [comment]
Thanks for your feedback!

We have released a new version 4.0.3 that fixes the problem.
https://github.com/Cysharp/MagicOnion/releases/tag/4.0.3

**Comment by mshipley** [comment]
Thank you, I will test it out today.

**Comment by mshipley** [comment]
The fixes in 4.0.3 resolved the issue. Thank you.
