### ISSUE TITLE
UDP Support

### ISSUE THREAD

**Issue by onehundredfeet** [Cysharp/MagicOnion#397]
HI,

I haven't found it in the documentation, but it would be great if the realtime communication could be specified to travel over UDP with various options - (Reliable/unreliable | ordered/unordered etc ).

Is this currently possible? Or possible with an extension?

The Api is great and would love to use it but I have concerns that TCP may not be performant enough in all cases.

Thanks in advance.

**Comment by neuecc** [comment]
Currently MagicOnion's transport is dependent on gRPC C Core(on Unity).
The Server has been migrated to Pure C# (ASP.NET Core Kestrel), and the Client is also being converted to Pure C#.
Kestrel is transport modifiable (e.g., it has a QUIC implementation), and when both companies become Pure C#, they will be able to modify it by plugging in each other's transport implementations.

In other words, we can't do it now, but it's in our future plans.

**Comment by onehundredfeet** [comment]
To be clear, I really like having the TCP support, I just would like to also have a (R)UDP channel or two beside the TCP ones.

Ideally, you could have channels that are TCP and some that are UDP (or another transport library). I.e. not necessarily a whole replacement of all the transport.

**Comment by onehundredfeet** [comment]
Do you know when the client will be pure C#?

**Comment by neuecc** [comment]
2021 2Q-3Q

**Comment by parkycai** [comment]
> 2021 2Q-3Q

Will Unity client be pure C# too? The .so and .a file is way too big _(:з」∠)_
