### ISSUE TITLE
Any way to make this work with Godot?

### ISSUE THREAD

**Issue by zaksnet** [Cysharp/MagicOnion#409]
Hello!
Can someone please tell me if there is a way to make this work with [Godot ](https://godotengine.org) game engine?
I would guess that since there is a Unity package then there should be a way to port it to godot also.
Thank you.

**Comment by neuecc** [comment]
MagicOnion itself has almost no dependency on Unity, so it will work with a few modifications.
I don't know if the Unity version of gRPC, on which MagicOnion depends, will work.
But it will work, too, though it will require some modifications.

**Comment by zaksnet** [comment]
Hi @neuecc , Thank you for the answer!
I was trying to install MagicOnion package on the client which depends on .NET Core so it wouldn't work 😳 . MagicOnion.Client which depends on .NET Standard installs as expected but i could not figure out how to install Unity Grpc client :( . Any tips on those modifications you mentioned 🙏 ?
