### ISSUE TITLE
In the ChatRoomService example, BroadcastAllAsync (x => x.OnJoin) x always NullReferenceException

### ISSUE THREAD

**Issue by yoohoxiao** [Cysharp/MagicOnion#41]
How to solve this problem?

**Comment by neuecc** [comment]
it is caused from does not call RegisterStreamingMethod before call at once.
requires OnJoin before Broadcast...
However, null is not desirable, so I'd like to fix it.
thanks.

**Comment by yoohoxiao** [comment]
So how do I fix this problem now?

**Comment by neuecc** [comment]
Who calls BroadcastAll?
In the chat scenario, although I think that someone will surely start after Join.

**Comment by yoohoxiao** [comment]
```
public async Task<ServerStreamingResult<ChatRoomMember>> OnJoin()
{
  return await GetStreamingContextRepository().RegisterStreamingMethod(this, OnJoin);
}
```

**Comment by yoohoxiao** [comment]
Now this problem can not be resolved, there are other ways, I do not know where to modify.

**Comment by neuecc** [comment]
please show reproduce client code.
below code is works fine.

```csharp
static async Task RunChat(ChannelContext ctx)
{
    // create room
    var client = ctx.CreateClient<IChatRoomService>();

    var room = await await client.CreateNewRoom("test", "A"); // TODO:IChatRoomCommand sample is old so require await await...

    var result = await await client.SendMessage(room.Id, "foo bar baz");
    Console.WriteLine("Send success:" + result);
}
```

**Comment by yoohoxiao** [comment]
```
public IEnumerator Join(string roomId, string nickName)
{
       var r = client.Join(roomId, nickName).ResponseAsync.ToYieldInstruction();
       yield return r;
}
```

**Comment by yoohoxiao** [comment]
Do you need to do two "ToYieldInstruction" here?

**Comment by neuecc** [comment]
ah, sorry, require subscribe OnJoin before do anything.

**Comment by neuecc** [comment]
I've fixed sample code and upload `v0.5.1.1` includes this fix.
https://github.com/neuecc/MagicOnion/commit/4d1c8af6a2d9747c6ae855202c6e57ce67ff6e90

main fix is add new api, when creating StreamingContextRepository

```csharp
new StreamingContextRepository<IChatRoomStreaming>(connection, this);
```

**Comment by yoohoxiao** [comment]
Sorry, did not see the version update!

**Comment by yoohoxiao** [comment]
`public async UnaryResult<RoomResponse> CreateNewRoom(string roomName, string nickName)`
Are you sure you can write this way?
Why the editor that need to add Task <T>, or can not use async.

**Comment by neuecc** [comment]
this is for C# 7.0 only, if you have to use old c#, change signature to `Task<UnaryResult<T>>`.
(but for Unity, generates `IObservable<T>` code).

**Comment by yoohoxiao** [comment]
```
public interface IChatRoomCommand
{
           IObservable<UnaryResult<global::ShareType.RoomResponse>> CreateNewRoom(string roomName, string nickName);
}
```
Does Unity3d need this?

**Comment by neuecc** [comment]
`moc.exe` automatically convert and generate interface.
