### ISSUE TITLE
Waiting for support kit of create server-side loop

### ISSUE THREAD

**Issue by devwithu** [Cysharp/MagicOnion#412]
>>If you want to create ServerSide loop and broadcast out of StreamingHub, 
>>you can pass Broadcast(room) result but it is unnatural, 
>>I'll add support kit of create server-side loop

I am a beginner who wants to make a multiplayer game. 
i am studying use of MagicOnion. 
Thanks!
Great work!

i don't know how to make main-loop for game logic and access every Group.
welcome advice and example code.
please share your know-how and opinions.
thank you very much.

**Comment by neuecc** [comment]
We're providing loop-engine, `LogicLooper` 
https://github.com/Cysharp/LogicLooper

However, sample for MagicOnion is not yet.

**Comment by devwithu** [comment]
i saw LogicLooper.
that's good.
but i don't know how can i access Groups of MagicOnion Hub from LogicLooper.
Anybody have some advice?

**Comment by locus84** [comment]
+1 This, Don't know where is 'natual' way
![image](https://user-images.githubusercontent.com/6591432/109797016-3ac8b680-7c5c-11eb-85da-ed710a3baabd.png)

**Comment by slimshader** [comment]
Is the sample of integration of MagicOnion and LogicLooper coming?

**Comment by slimshader** [comment]
I looked at the example of LogicLooper hosted in ASP app and it seems that integration with MagicOnion would require:
1) adding LogicLooperService to hosted services of MagicOnion server app
2) integrating Looper with streaming Hub via Pub/Sub like MessagePipe to push updates from Loop => Hub
is that correct?

**Comment by mayuki** [comment]
That's correct! I apologize for not being able to provide a sample. 
If you have a very simple case, you can hold onto HubReceiver and send message from Looper.

**Comment by devwithu** [comment]
I am waiting for support kit of create server-side loop.
and maybe many peaple do.

**Comment by devwithu** [comment]
I am waiting for support kit of create server-side loop.
and maybe many peaple do.
