### ISSUE TITLE
Improve grpc library file size in iOS and Android build

### ISSUE THREAD

**Issue by parkycai** [Cysharp/MagicOnion#415]
The document provides a way to strip debug symbols from `libgrpc.a`, which reduce the file size from about 100m to 18m.
Meanwhile, the stripped `libgrpc.a` is still a FAT file, which contains x86_64, armv7 and arm64 architecture. Since armv7 is already deprecated, we can use `lipo` command to remove x86_64 and armv7 from it.
```
lipo libgrpc.a -remove x86_64 -remove armv7 
```
The file size can be reduced to ~6M, if you are targeting arm64 devices only (iPhone 5s and later).

The `libgrpc_csharp_ext.so` for Android platform can also be stripped by following command:
```
##Choose proper architecture
[NDK_PATH]\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64\aarch64-linux-android\bin\strip.exe" libgrpc_csharp_ext.so
```
The file size can be reduced from 46M to 3M

Hope these tips would help someone who hesitated because of client library file size.

**Comment by andre-laskawy** [comment]
Any idea if there is a chance to include this command during a package build in xamarin?

**Comment by bartutiryakioglu** [comment]
Hey, I was trying your solution but getting this error. input file (libgrpc.a) must be a fat file when the -remove option is specified. Do you have any idea why?

**Comment by parkycai** [comment]
> Hey, I was trying your solution but getting this error. input file (libgrpc.a) must be a fat file when the -remove option is specified. Do you have any idea why?

Is it already thinned? A FAT file means it contains multiple archs in it.  Try `lipo libgrpc.a -archs`  to find out which archs it contains.

**Comment by bartutiryakioglu** [comment]
yes, only arm64 is included in build process. Thanks!! However, its size is still too big for an iOS project. After stripping its debug symbols, it is 354 mb. Do you know if there is anything else I can do to reduce its size?

**Comment by triste24** [comment]
same issue as [bartutiryakioglu](https://github.com/bartutiryakioglu)

**Comment by parkycai** [comment]
It looks like grpc-unity-packaged is removed from grpc daily build page. Where can I download the latest version? @triste24 @bartutiryakioglu 

Meanwhile, could you try that whether the version in this repo is still working? [libgrpc.a](https://github.com/Cysharp/MagicOnion/blob/master/src/MagicOnion.Client.Unity/Assets/Plugins/Grpc.Core/runtimes/ios/libgrpc.a)
