### ISSUE TITLE
UWP Support

### ISSUE THREAD

**Issue by torston** [Cysharp/MagicOnion#42]
Hello,

Is your project support Universal Windows Platform with Unity3d?

I'm tried to use it in Unity Editor (2017.1.1) and it works fine, and build process from Unity to UWP Application goes fine without error. But when I tried to build UWP Project to get binaries I got several errors. ( Used IL2CPP Scripting Backend)

As a unity project, I used your unity3d sample from the repository.

![image](https://user-images.githubusercontent.com/5497223/30651393-3e6644de-9e2e-11e7-9679-fd23a1422b90.png)

**Comment by neuecc** [comment]
already I've used Hololens project(its UWP).
But that was quite a while ago.
I do not know how it is in the current state unless I confirm it.

**Comment by neuecc** [comment]
Ah, When I've tried, not used UWP+IL2CPP.
My tested environment are
iOS + IL2CPP, Android + IL2CPP, Win + IL2CPP and UWP(not IL2CPP)

**Comment by torston** [comment]
So you've tried UWP with .NET scripting backend and it works, right?

**Comment by neuecc** [comment]
yes.

**Comment by torston** [comment]
I have tried to build with .NET scripting backend and have several errors too.

Configuration in Unity: 
![image](https://user-images.githubusercontent.com/5497223/30686300-868585c6-9ec0-11e7-9f30-51c183dfa5b9.png)
Full Unity Editor errors output:
[Full_errors_log.txt](https://github.com/neuecc/MagicOnion/files/1320479/Full_errors_log.txt)

**Comment by neuecc** [comment]
It seems messagepack compiler error.
It is realted to https://github.com/neuecc/MessagePack-CSharp/issues/134
replace `UNITY_METRO` -> `UNITY_WSA`.
It is not fixed yet.

**Comment by torston** [comment]
Replaced, but it does not work for me, unfortunately.

There a lot of unsupported APIs and a got pretty same errors after I'm calling build from unity.
[ApiPortAnalysis.xlsx](https://github.com/neuecc/MagicOnion/files/1320888/ApiPortAnalysis.xlsx)
