### ISSUE TITLE
MagicOnion.OpenTelemetry nuget package is outdated

### ISSUE THREAD

**Issue by Energy0124** [Cysharp/MagicOnion#421]
In issue #380 it is mentioned that MagicOnion.Server.OpenTelemetry will be published after #374 is merged. It seems that it is not available yet. Is there anything that is blocking that? Thank you!

**Comment by guitarrapc** [comment]
Let me check.

**Comment by guitarrapc** [comment]
opentelemetry-dotnet blocking release OpenTelemetry.Extensions.Hosting since rc3 and MagicOnion.OpenTelemetry depends on this pacakge.
Now I'm asking load map, and will decide action when answer comes.

> https://github.com/open-telemetry/opentelemetry-dotnet/issues/1959

**Comment by guitarrapc** [comment]
Still waiting rc4.

**Comment by guitarrapc** [comment]
Update PR to support OpenTelemetry 1.1.0-beta2 and OpenTelemetry.Extensions.Hosting 1.0.0-rc4.

**Comment by guitarrapc** [comment]
I've dropped `OpenTelemetry.Extensions.Hosting 1.0.0-rc4` dependency. This bring package update match easier and simpler.
Now it's in review.
