### ISSUE TITLE
[Question] Accessing StreamingHubs from each other

### ISSUE THREAD

**Issue by ehakan-veloxia** [Cysharp/MagicOnion#424]
Is there any way to trigger broadcast events of one streaming hub through another streaming hub, on the server?

For example, if `MatchmakingHub` finds a match, I want to broadcast the player statuses as "Now in match" through `PresenceHub`.

**Comment by neuecc** [comment]
We've released new library `MessagePipe` https://github.com/Cysharp/MessagePipe
It brdiges hub to hub.
