### ISSUE TITLE
Is it possible to embed Server WinForms/WPF app

### ISSUE THREAD

**Issue by slimshader** [Cysharp/MagicOnion#428]
Hi,

I'd like to create a windows desktop app (WinForms / WPF / Avalonia etc) that talks to Unity application, possibly even embedding Unity window inside via custom HWND. Desktop app would be "UI" for the view that heppend in Unity window so MagicOnion would server the purpose of inter-process communication.

Currently I see the solution as:
1. MagicOnion server - ASP console app
2. WinForms/WPF MagicOnion.Client app connects to 1.
3. Unity app MagicOnion.Client app connets to 1
so overall 3 separate apps.

My question is this: is it possible to create a single app from 1 and 2 meaning WinForms/WPF app would have MagicOnion service running and remove the need to have separate console server application.

**Comment by mayuki** [comment]
MagicOnion.Server currently depends on ASP.NET Core.
If you don't want to separate your desktop app from the server, there is a way to host ASP.NET Core inside your desktop app.

If your WPF (or desktop) app is running on .NET 5 or .NET Core 3.1, I think it is possible to run ASP.NET Core + MagicOnion inside your desktop app.
