### ISSUE TITLE
How to create a library with the interface to share between service and client?

### ISSUE THREAD

**Issue by ComptonAlvaro** [Cysharp/MagicOnion#429]
I am following this documentation: [(https://github.com/Cysharp/MagicOnion)]

It is needed to define an interface, to be shared between service and client. So i created a new library class project which target is net standar 2.1, I want to use MagicOnion with Xamarin forms. My idea it is to have 3 libraries, one for the service, that is ASP.Net .NET 5, one library for share between the service and the client, which target is net standard 2.1 and the last library that it is the xamarin forms application and it will be the client.

My problem is that I don't konw which nuget package I have to install to can use MagicOnion and to have access to IService and UnarayResult. How could create this shared library?

Thanks.

PD: I have found the jwt sample that it does what i want to do, I have needed to install the nuget package magicOnion.Shared in the shared library.

**Comment by mayuki** [comment]
I am sorry for the very late reply.

For a class library project to share interfaces, please use [MagicOnion.Abstractions NuGet package](https://www.nuget.org/packages/MagicOnion.Abstractions/).
This package contains interfaces and classes that are used by both clients and servers, such as `UnaryResult` and `IService<T>`.

We will document that in the README later.

**Comment by ComptonAlvaro** [comment]
Sure, don't need to apologize, really I have to thanks your work and share it.

I will wait for the readme and the update documentation.


Thanks so much.
