### ISSUE TITLE
Xamarin forms and gRPC: The server returned an invalid or unrecognized response

### ISSUE THREAD

**Issue by ComptonAlvaro** [Cysharp/MagicOnion#432]
I am trying to get a response from the gRPC service but I get the error that the server returned an invalid or unrecognized response when I make the call from a Xamarin application. However, if I use a WPF client, that use the same gRPC client library than the Xamarin application, it works as exepected, I get the response from the service.

The service code is this:

```
            webBuilder.ConfigureKestrel(options =>
            {
                options.Listen(IPAddress.Any, 5001, listenOptions =>
                {
                    listenOptions.Protocols = HttpProtocols.Http2;
                    listenOptions.UseHttps("server.pfx", "1111");
                });
            });
            webBuilder.UseStartup<Startup>();
```

Client library:

```
        HttpClientHandler miHandler = new HttpClientHandler();

        miHandler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;

        GrpcChannelOptions misOpciones = new GrpcChannelOptions() { HttpHandler = miHandler };

        var miChannel = GrpcChannel.ForAddress("https://192.168.1.134:5001", misOpciones);
```

What I am doing wrong? At first I thought it was because from android I couldn't use http, that I need https, but now I am using https. It is true that I am ignoring any certificate from the server, could it be this the reason for that? But the error message it would be related with SSL or something like that, instead of telling that the response is not recognized.

I have realized that in the service window, I get this message: HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint.

Thanks.

**Comment by mayuki** [comment]
Grpc.Net.Client does not provide full HTTP/2 support on Xamarin, so you will need to use Grpc.Core (C-core) library instead of Grpc.Net.Client.

- See: https://docs.microsoft.com/en-us/aspnet/core/grpc/netstandard?view=aspnetcore-5.0#net-implementations

**Comment by ComptonAlvaro** [comment]
Thank you so much.

Then I will use Grpc.Core until Net 6.
