### ISSUE TITLE
the gRpc service and method can't be shown in the gRpc web ui tools 

### ISSUE THREAD

**Issue by gzh4455** [Cysharp/MagicOnion#438]
when  I use the grpc web UI to debug it ,I  can't not find the services in the grpc  web.  but  I can call the method  in the code.

How  can I  support this feature ?
because  I want to let other soft engineers (they are using the difference developing language )  to call it.
 
Looking forward your reply .

Note: the gRpc web Ui tools is located  in https://github.com/fullstorydev/grpcui/

**Comment by mayuki** [comment]
Currently, there is UI support for making Unary requests with Swagger, but no further support is available.
Also, since MessagePack is used as the data format, it would be difficult to use it with grpcui.

In the future, we would like to provide development UI support including Streaming with Blazor and others.

**Comment by gzh4455** [comment]
So , I have a question ,  if   I use this way to private gRPC service , other language developers can call those gRPC services  and how ?

**Comment by gzh4455** [comment]
And it is a way to use auto dependency injection in the client ?  like autofac or the default dependency injection in the net core 5. 0.

**Comment by LeonSpors** [comment]
@mayuki Are planning to ship it to other languages? Or let me ask more accurately. Does MessagePacks support to be send from different os and languages?

**Comment by mayuki** [comment]
Sorry, we currently have no plans to support other languages.

MessagePack is a widely used serialization format and can be used in multiple languages.
However, you will need a specific mechanism to send and receive messages over gRPC (like MagicOnion for .NET platform)

**Comment by LeonSpors** [comment]
Alright. I will take this into consideration. Thanks for the quick response.
