### ISSUE TITLE
Compiling error on  iOS Version 4.3.0

### ISSUE THREAD

**Issue by isax5** [Cysharp/MagicOnion#440]
Build doesn't work on iOS Xamarin Project any more
Xamarin Android works correctly by the way

There is a problem in a .dll file:

**/Users/isaac/Developer/Licklider/enrolamientomobile/Enrollment.XF/Enrollment.XF.iOS/MTOUCH: Error MT3001: Could not AOT the assembly Project.XF.iOS/obj/iPhone/Debug/device-builds/iphone9.3-14.4.2/mtouch-cache/3-Build/MagicOnion.Shared.dll' (MT3001) (Project.XF.iOS)**

**Comment by isax5** [comment]
This is still not working....

**Comment by mayuki** [comment]
I tried a debug build on the device with the following environment, but I couldn't reproduce the error.

- Development environment
  - Visual Studio 2019 for Mac 8.10.6
  - Xamarin.iOS 14.20.0.24
  - macOS 10.16.0
  - Xcode 12.5.1
- NuGet
  - MagicOnion.Client 4.3.1
  - Grpc.Core 2.40.0
  - Grpc.Core.Xamarin 2.40.0
- Device
  - iPhone 12 Pro + iOS 14.8

Do you have any project-specific build settings?

**Comment by isax5** [comment]
I'll make an example project this week 👍
