### ISSUE TITLE
Mirroring Transforms over network

### ISSUE THREAD

**Issue by slimshader** [Cysharp/MagicOnion#441]
I'd like to simulate a small world by 1 Unity client and reflect it in the other. In addition to 2 players, world had simulated Rigidbody objects. So there would be 2 Unity clients:

- Simulator (running Rigibodies via Unity Physics)
- Mirror (only showing current positions and orientations of objects from Simulator)

what is the best way to approach this problem? Should there be 2 separate streaming hubs 1 for players and 1 for mirrored transforms? Can a single Channel be used for multiple Hubs or maybe multiple channels are preferred?

**Comment by mayuki** [comment]
I think it would be better to have different StreamingHubs for different purposes.
We recommend using a PubSub-like mechanism to bridge data between StreamingHubs.

We provide a PubSub library called [MessagePipe](https://github.com/Cysharp/MessagePipe) and may be useful for you.

**Comment by slimshader** [comment]
> I think it would be better to have different StreamingHubs for different purposes.

Should Hubs share a Channel?

> We recommend using a PubSub-like mechanism to bridge data between StreamingHubs.
> 

I am already using MessagePipe in 2 projects but not for Hub bridging. So will try this out.

Are there recommendations on how to inter/extrapolate/smooth posistions / rotations on the Mirror side?

**Comment by mayuki** [comment]
Whether to share a channel or not depends on the amount of data. If you send and receive frequently or use a lot of bandwidth, you may need to separate them.

If the main purpose of the mirror client is to receive, I think a single channel can be used for sending and receiving.

> I am already using MessagePipe in 2 projects but not for Hub bridging. So will try this out.
> Are there recommendations on how to inter/extrapolate/smooth posistions / rotations on the Mirror side?

Very nice, thank you! 👍

MessagePipe doesn't include those features, but maybe a [custom Filter](https://github.com/Cysharp/MessagePipe#filter) can handle them.

**Comment by slimshader** [comment]
I see, thank you, follow-up questions:

- should every new Rigidbody/Mirrored Transform be a new "Player"/connection in the system, having a dedicated IHub/IHubReceiver? or:
- should all Rigidbody/Mirrored Transform share existing IH/IHubReceiver which requires a server-side state keeping the list of such objects, in that case how to keep such state. InMemoryStorage seems only allows to add per-connection data so does not seem like something that could be used in that case.
- what is the life-cycle of a StreamingHub? When is it destroyed and associated Group and storage?

**Comment by mayuki** [comment]
If you just want to stream data easily, you can share StreamingHub, but if you want to strictly separate them, you need to split a StreamingHub and connect them via server-side states.

The way to have server-side states that cannot be handled by IInMemoryStorage is dependent on your application implementation (static field, injected services, pubsub, etc.).

> - what is the life-cycle of a StreamingHub? When is it destroyed and associated Group and storage?

A StreamingHub will be created for each user connection, and will be disposed of when disconnected.
Any group registration will be automatically deleted when disconnected.
