### ISSUE TITLE
Unity Exception FormatterNotRegisteredException

### ISSUE THREAD

**Issue by bluekms** [Cysharp/MagicOnion#444]
Hi. I want to develop a project with MagicOnion.
But a problem arose. I need your help.

**Exception :**
FormatterNotRegisteredException: MagicOnion.DynamicArgumentTuple`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] is not registered in resolver: MessagePack.Resolvers.StandardResolver

**Test Development Situation**
1. Server <-> Unity PC Client : Success
2. Server <-> Android Client : Fail
3. Proceed to item 'MagicOnion.MSBuild.Tasks (MessagePack 2.2.85)' of the manual : Fail. MagicOnionGemerator Invaild Argument.
4. MessagePack downgrade 2.1.194 : Generate Success (MessagePack.Generated.cs, MagicOnion.Generated.cs)
5. Fix compilation errors in the generated code : using must come first
6. Android Client Build : Success
7. Server <-> Android Client : Fail. Exception FormatterNotRegisteredException

https://github.com/Cysharp/MagicOnion/issues/47
similar case. But it is closed. I can't find a workaround.
Waiting for your solution. Thank you.

- - -

**Versions
Client**
* Unity 2020.3.8f1
* MagicOnion.Client.Unity 4.3.1
* MessagePack 2.2.85 -> 2.1.194

**Server And Shard**
* VS2019 16.9.6
* MagicOnion 4.3.1
* MagicOnion.Abstractions 4.3.1
* MagicOnion.MsBuild.Tasks 4.3.1
* MagicOnion.Server 4.3.1
* MessagePack.MSBuild.Tasks 2.1.194
* MessagePack.UnityShims 2.2.85

- - -

**Detail Exception**
FormatterNotRegisteredException: MagicOnion.DynamicArgumentTuple`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] is not registered in resolver: MessagePack.Resolvers.StandardResolver

MessagePack.FormatterResolverExtensions.Throw (System.Type t, MessagePack.IFormatterResolver resolver) (at <00000000000000000000000000000000>:0)
MessagePack.FormatterResolverExtensions.GetFormatterWithVerify[T] (MessagePack.IFormatterResolver resolver) (at <00000000000000000000000000000000>:0)
MessagePack.MessagePackSerializer.Serialize[T] (MessagePack.MessagePackWriter& writer, T value, MessagePack.MessagePackSerializerOptions options) (at <00000000000000000000000000000000>:0)
MagicOnion.Client.StreamingHubClientBase`2[TStreamingHub,TReceiver].<WriteMessageWithResponseAsync>g__BuildMessage|26_0[TRequest,TResponse] (MagicOnion.Client.StreamingHubClientBase`2+<>c__DisplayClass26_0`2[TStreamingHub,TReceiver,TRequest,TResponse]& ) (at <00000000000000000000000000000000>:0)
MagicOnion.Client.StreamingHubClientBase`2+<WriteMessageWithResponseAsync>d__26`2[TStreamingHub,TReceiver,TRequest,TResponse].MoveNext () (at <00000000000000000000000000000000>:0)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].Start[TStateMachine] (TStateMachine& stateMachine) (at <00000000000000000000000000000000>:0)
MagicOnion.Client.StreamingHubClientBase`2[TStreamingHub,TReceiver].WriteMessageWithResponseAsync[TRequest,TResponse] (System.Int32 methodId, TRequest message) (at <00000000000000000000000000000000>:0)
ChatHubClient.JoinAsync (System.String roomName, System.String userName) (at <00000000000000000000000000000000>:0)
ChatComponent+<OnClickJoinButton>d__7.MoveNext () (at <00000000000000000000000000000000>:0)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) (at <00000000000000000000000000000000>:0)
ChatComponent.OnClickJoinButton () (at <00000000000000000000000000000000>:0)
UnityEngine.Events.UnityAction.Invoke () (at <00000000000000000000000000000000>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1].Invoke (T1 handler, UnityEngine.EventSystems.BaseEventData eventData) (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.ProcessTouchPress (UnityEngine.EventSystems.PointerEventData pointerEvent, System.Boolean pressed, System.Boolean released) (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.ProcessTouchEvents () (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.Process () (at <00000000000000000000000000000000>:0)
Rethrow as MessagePackSerializationException: Failed to serialize MagicOnion.DynamicArgumentTuple`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] value.

**Comment by mayuki** [comment]
It looks like MessagePackResolver cannot be found according to the error message, have you tried to register Resolvers?
https://github.com/Cysharp/MagicOnion#messagepack-for-c-1

**Comment by bluekms** [comment]
> It looks like MessagePackResolver cannot be found according to the error message, have you tried to register Resolvers?
> https://github.com/Cysharp/MagicOnion#messagepack-for-c-1

You are right.
However, after registering the resolver, gRPG Connect fails. An error occurs.
As I wrote above, Server <-> Unity PC Client succeeds.
But the server <-> android client fails.

**Comment by mayuki** [comment]
After registering Resolver, does it still throw FormatterNotRegisteredException when connecting?

**Comment by bluekms** [comment]
> After registering Resolver, does it still throw FormatterNotRegisteredException when connecting?

No. This problem is solved.
