### ISSUE TITLE
Unable to connect from Android client. RpcException "failed to connect to all addresses"

### ISSUE THREAD

**Issue by bluekms** [Cysharp/MagicOnion#445]
https://github.com/Cysharp/MagicOnion/issues/444#issue-914863821
continues on this issue.
I solved the 444 issue.
However, I get the following error:
RpcException: Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", 

**Current Situation**
1. AWS Linux Server <-> Local Unity PC Client : Success
2. AWS Linux Server <-> Android Client : Fail

**Server Start**
dotnet MagicOnionTest.dll --urls:httpL//+:5001

The error message is too simplistic.
I don't know how to solve the problem.
I need your help.
Thank you.

- - -

RpcException: Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1623402043.495759291","description":"Failed to pick subchannel","file":"/var/local/git/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3009,"referenced_errors":[{"created":"@1623402043.495744945","description":"failed to connect to all addresses","file":"/var/local/git/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}")

System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <00000000000000000000000000000000>:0)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () (at <00000000000000000000000000000000>:0)
MagicOnion.Client.ResponseContext`1+<Deserialize>d__11[T].MoveNext () (at <00000000000000000000000000000000>:0)
System.Threading.ContextCallback.Invoke (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <00000000000000000000000000000000>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <00000000000000000000000000000000>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run () (at <00000000000000000000000000000000>:0)
System.Action.Invoke () (at <00000000000000000000000000000000>:0)
System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction (System.Action action, System.Boolean allowInlining, System.Threading.Tasks.Task& currentTask) (at <00000000000000000000000000000000>:0)
System.Threading.Tasks.Task.FinishContinuations () (at <00000000000000000000000000000000>:0)
System.Threading.Tasks.Task.Finish (System.Boolean bUserDelegateExecuted) (at <00000000000000000000000000000000>:0)
System.Threading.Tasks.Task`1[TResult].TrySetException (System.Object exceptionObject) (at <00000000000000000000000000000000>:0)
System.Threading.Tasks.TaskCompletionSource`1[TResult].TrySetException (System.Exception exception) (at <00000000000000000000000000000000>:0)
System.Threading.Tasks.TaskCompletionSource`1[TResult].SetException (System.Exception exception) (at <00000000000000000000000000000000>:0)
Grpc.Core.Internal.AsyncCall`2[TRequest,TResponse].HandleUnaryResponse (System.Boolean success, Grpc.Core.Internal.ClientSideStatus receivedStatus, Grpc.Core.Internal.IBufferReader receivedMessageReader, Grpc.Core.Metadata responseHeaders) (at <00000000000000000000000000000000>:0)
Grpc.Core.Internal.AsyncCall`2[TRequest,TResponse].Grpc.Core.Internal.IUnaryResponseClientCallback.OnUnaryResponseClient (System.Boolean success, Grpc.Core.Internal.ClientSideStatus receivedStatus, Grpc.Core.Internal.IBufferReader receivedMessageReader, Grpc.Core.Metadata responseHeaders) (at <00000000000000000000000000000000>:0)
Grpc.Core.Internal.CallSafeHandle+<>c.<.cctor>b__33_0 (System.Boolean success, Grpc.Core.Internal.BatchContextSafeHandle context, System.Object state) (at <00000000000000000000000000000000>:0)
Grpc.Core.Internal.BatchCompletionDelegate.Invoke (System.Boolean success, Grpc.Core.Internal.BatchContextSafeHandle ctx, System.Object state) (at <00000000000000000000000000000000>:0)
Grpc.Core.Internal.BatchContextSafeHandle.Grpc.Core.Internal.IOpCompletionCallback.OnComplete (System.Boolean success) (at <00000000000000000000000000000000>:0)
Grpc.Core.Internal.GrpcThreadPool.RunCompletionQueueEventCallback (Grpc.Core.Internal.IOpCompletionCallback callback, System.Boolean success) (at <00000000000000000000000000000000>:0)
System.Threading.WaitCallback.Invoke (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.ContextCallback.Invoke (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <00000000000000000000000000000000>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <00000000000000000000000000000000>:0)
System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () (at <00000000000000000000000000000000>:0)
System.Threading.ThreadPoolWorkQueue.Dispatch () (at <00000000000000000000000000000000>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <00000000000000000000000000000000>:0)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () (at <00000000000000000000000000000000>:0)
MagicOnion.UnaryResult`1+<UnwrapResponse>d__11[TResponse].MoveNext () (at <00000000000000000000000000000000>:0)
System.Threading.ContextCallback.Invoke (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <00000000000000000000000000000000>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <00000000000000000000000000000000>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run () (at <00000000000000000000000000000000>:0)
System.Action.Invoke () (at <00000000000000000000000000000000>:0)
System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction (System.Action action, System.Boolean allowInlining, System.Threading.Tasks.Task& currentTask) (at <00000000000000000000000000000000>:0)
System.Threading.Tasks.Task.FinishContinuations () (at <00000000000000000000000000000000>:0)
System.Threading.Tasks.Task.Finish (System.Boolean bUserDelegateExecuted) (at <00000000000000000000000000000000>:0)
System.Threading.Tasks.Task`1[TResult].TrySetException (System.Object exceptionObject) (at <00000000000000000000000000000000>:0)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].SetException (System.Exception exception) (at <00000000000000000000000000000000>:0)
MagicOnion.Client.ResponseContext`1+<Deserialize>d__11[T].MoveNext () (at <00000000000000000000000000000000>:0)
System.Threading.ContextCallback.Invoke (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <00000000000000000000000000000000>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <00000000000000000000000000000000>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run () (at <00000000000000000000000000000000>:0)
System.Action.Invoke () (at <00000000000000000000000000000000>:0)
System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction (System.Action action, System.Boolean allowInlining, System.Threading.Tasks.Task& currentTask) (at <00000000000000000000000000000000>:0)
System.Threading.Tasks.Task.FinishContinuations () (at <00000000000000000000000000000000>:0)
System.Threading.Tasks.Task.Finish (System.Boolean bUserDelegateExecuted) (at <00000000000000000000000000000000>:0)
System.Threading.Tasks.Task`1[TResult].TrySetException (System.Object exceptionObject) (at <00000000000000000000000000000000>:0)
System.Threading.Tasks.TaskCompletionSource`1[TResult].TrySetException (System.Exception exception) (at <00000000000000000000000000000000>:0)
System.Threading.Tasks.TaskCompletionSource`1[TResult].SetException (System.Exception exception) (at <00000000000000000000000000000000>:0)
Grpc.Core.Internal.AsyncCall`2[TRequest,TResponse].HandleUnaryResponse (System.Boolean success, Grpc.Core.Internal.ClientSideStatus receivedStatus, Grpc.Core.Internal.IBufferReader receivedMessageReader, Grpc.Core.Metadata responseHeaders) (at <00000000000000000000000000000000>:0)
Grpc.Core.Internal.AsyncCall`2[TRequest,TResponse].Grpc.Core.Internal.IUnaryResponseClientCallback.OnUnaryResponseClient (System.Boolean success, Grpc.Core.Internal.ClientSideStatus receivedStatus, Grpc.Core.Internal.IBufferReader receivedMessageReader, Grpc.Core.Metadata responseHeaders) (at <00000000000000000000000000000000>:0)
Grpc.Core.Internal.CallSafeHandle+<>c.<.cctor>b__33_0 (System.Boolean success, Grpc.Core.Internal.BatchContextSafeHandle context, System.Object state) (at <00000000000000000000000000000000>:0)
Grpc.Core.Internal.BatchCompletionDelegate.Invoke (System.Boolean success, Grpc.Core.Internal.BatchContextSafeHandle ctx, System.Object state) (at <00000000000000000000000000000000>:0)
Grpc.Core.Internal.BatchContextSafeHandle.Grpc.Core.Internal.IOpCompletionCallback.OnComplete (System.Boolean success) (at <00000000000000000000000000000000>:0)
Grpc.Core.Internal.GrpcThreadPool.RunCompletionQueueEventCallback (Grpc.Core.Internal.IOpCompletionCallback callback, System.Boolean success) (at <00000000000000000000000000000000>:0)
System.Threading.WaitCallback.Invoke (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.ContextCallback.Invoke (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <00000000000000000000000000000000>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <00000000000000000000000000000000>:0)
System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () (at <00000000000000000000000000000000>:0)
System.Threading.ThreadPoolWorkQueue.Dispatch () (at <00000000000000000000000000000000>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <00000000000000000000000000000000>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <00000000000000000000000000000000>:0)
SampleController+<SampleServiceTest>d__4.MoveNext () (at <00000000000000000000000000000000>:0)
System.Threading.ContextCallback.Invoke (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <00000000000000000000000000000000>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <00000000000000000000000000000000>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run () (at <00000000000000000000000000000000>:0)
System.Action.Invoke () (at <00000000000000000000000000000000>:0)
System.Threading.SendOrPostCallback.Invoke (System.Object state) (at <00000000000000000000000000000000>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <00000000000000000000000000000000>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <00000000000000000000000000000000>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <00000000000000000000000000000000>:0)
System.Threading.SendOrPostCallback.Invoke (System.Object state) (at <00000000000000000000000000000000>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <00000000000000000000000000000000>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <00000000000000000000000000000000>:0)
UnityEngine.UnitySynchronizationContext:Exec()

**Comment by mayuki** [comment]
Do you allow `android.permission.INTERNET` in AndroidManifest.xml?

**Comment by bluekms** [comment]
> Do you allow `android.permission.INTERNET` in AndroidManifest.xml?

Thank you. Completely resolved.
It was set to auto in Unity, but changing it to Require solved it.
