### ISSUE TITLE
[Question] Why wait five seconds to reconnect?

### ISSUE THREAD

**Issue by hwanghwang** [Cysharp/MagicOnion#452]
Why wait five seconds to reconnect?
Is there any particular reason?

```
Debug.Log($"Failed to connect to the server. Retry after 5 seconds...");
await Task.Delay(5 * 1000);
```
this is part of sample code.
Thanks:-)

**Comment by mayuki** [comment]
This is a experience-based way of waiting that avoids raising a lot of errors in situations where an immediate failure would occur.
There is no particular reason for this as it is sample code. 🙂

**Comment by hwanghwang** [comment]
Thank you so much for your reply.👍🏻
