### ISSUE TITLE
MessagePack.MSBuild.Tasks (MSBuild Integration) sample is outdated?

### ISSUE THREAD

**Issue by land297** [Cysharp/MagicOnion#453]
Hi.

Per https://github.com/neuecc/MessagePack-CSharp/issues/1246 the setup has changed in version 2.2.
I tried to use the new setup but couldn't grasp how to set the variables without an sample.

**Comment by mccokumura** [comment]
I succeed to generate resolver.
`
  <Target Name="GenerateMessagePack" AfterTargets="Compile">
    <MessagePackGenerator
      IntermediateOutputPath="..MyFolderPath\MyApp\Generated"
      Compile="@(Compile)"
      ReferencePath="@(ReferencePath)"
      ResolverName ="MyResolverName"/>
  </Target>
`

The file is generated at "MyFolderPath\MyApp\Generated\mpc_generated.cs".

And I could access resolver 
"Resolvers.MyResolverName.Instance"

But I've been not test the resolver yet.

**Comment by mayuki** [comment]
We apologise that the sample has not been updated.

We recommend setting latest MessagePack.MSBuild.Tasks as described in https://github.com/neuecc/MessagePack-CSharp/issues/1246, or using mpc (MessagePack generator CLI tool) instead.

**Comment by land297** [comment]
Thanks for the assistance mccokumura, I used your example and could generate the file and user the "new" resolver in Unity after some namespace updates
