### ISSUE TITLE
Moc.exe does not work correctly

### ISSUE THREAD

**Issue by xICELIFEx** [Cysharp/MagicOnion#46]
Hello,

I've faced an issue with the utile moc.exe. On its launch, with specified path to Sandbox.ConsoleServerDefinition.csproj there is generated file, that contain the following:
`
#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
namespace MagicOnion
{
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::MagicOnion;
    using global::MagicOnion.Client;

    public static partial class MagicOnionInitializer
    {
        static bool isRegistered = false;

        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
        public static void Register()
        {
            if(isRegistered) return;
            isRegistered = true;

        }
    }
}
#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

namespace MagicOnion.Resolvers
{
    using System;
    using MessagePack;

    public class MagicOnionResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new MagicOnionResolver();

        MagicOnionResolver()
        {

        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.formatter;
        }

        static class FormatterCache<T>
        {
            public static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> formatter;

            static FormatterCache()
            {
                var f = MagicOnionResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class MagicOnionResolverGetFormatterHelper
    {
        static readonly global::System.Collections.Generic.Dictionary<Type, int> lookup;

        static MagicOnionResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<Type, int>(0)
            {
            };
        }

        internal static object GetFormatter(Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                if (t == typeof(UniRx.Unit))
                {
                    return MagicOnion.Resolvers.UniRxIntegrate.UnitFormatter.Instance;
                }
                else if (t == typeof(Nullable<UniRx.Unit>))
                {
                    return MagicOnion.Resolvers.UniRxIntegrate.NullableUnitFormatter.Instance;
                }
                return null;
            }

            switch (key)
            {
                default: return null;
            }
        }
    }
}

namespace MagicOnion.Resolvers.UniRxIntegrate
{
    using System;
    using UniRx;
    using MessagePack;
    using MessagePack.Formatters;

    public class UnitFormatter : IMessagePackFormatter<Unit>
    {
        public static readonly IMessagePackFormatter<Unit> Instance = new UnitFormatter();

        UnitFormatter()
        {

        }

        public int Serialize(ref byte[] bytes, int offset, Unit value, IFormatterResolver typeResolver)
        {
            return MessagePackBinary.WriteNil(ref bytes, offset);
        }

        public Unit Deserialize(byte[] bytes, int offset, IFormatterResolver typeResolver, out int readSize)
        {
            if (bytes[offset] == MessagePackCode.Nil)
            {
                readSize = 1;
                return Unit.Default;
            }
            else
            {
                throw new InvalidOperationException(string.Format("code is invalid. code:{0} format:{1}", bytes[offset], MessagePackCode.ToFormatName(bytes[offset])));
            }
        }
    }

    public class NullableUnitFormatter : IMessagePackFormatter<Unit?>
    {
        public static readonly IMessagePackFormatter<Unit?> Instance = new NullableUnitFormatter();

        NullableUnitFormatter()
        {

        }

        public int Serialize(ref byte[] bytes, int offset, Unit? value, IFormatterResolver typeResolver)
        {
            return MessagePackBinary.WriteNil(ref bytes, offset);
        }

        public Unit? Deserialize(byte[] bytes, int offset, IFormatterResolver typeResolver, out int readSize)
        {
            if (bytes[offset] == MessagePackCode.Nil)
            {
                readSize = 1;
                return Unit.Default;
            }
            else
            {
                throw new InvalidOperationException(string.Format("code is invalid. code:{0} format:{1}", bytes[offset], MessagePackCode.ToFormatName(bytes[offset])));
            }
        }
    }
}

#pragma warning disable 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612
`
So there is no declaration or implementation for interfaces that present in MagicOnionGenerated.cs

Could you please advise on how to use the utile moc.exe? If possible, on the example of your project so that it was clear which paths should be specified and so on.

**Comment by DaniilSokolyuk** [comment]
Hi, this happen if MSBuildWorskspace cant load documents (.cs)
Can you download latest sources and compile moc.exe
I added Console.Writeline here https://github.com/neuecc/MagicOnion/pull/45/files#diff-31aa1fd191716b2832c2ccee2d124ab7R73
And in console you get error on MSBuildWorkspace failed

**Comment by kt81** [comment]
I've faced same issue.
In my case, built new moc.exe works perfectly but after processed by libz, it's represented.

**Comment by kt81** [comment]
In another matter, I found moc.exe does not work for .NET Core and .NET Standard projects.
It seems that is caused by the workaround in ```RoslynExtensions.cs```.

**Comment by DaniilSokolyuk** [comment]
ok for open new csproj
1) we can use https://github.com/daveaglick/Buildalyzer 
2) write custom workspace like https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.DotNet/DotNetWorkspace.cs

any ideas?

**Comment by xICELIFEx** [comment]
Hello,

I have checked the solution with logs,
An access to the files available, but there is no data about the following MagicOnion types:

public ReferenceSymbols(Compilation compilation) {
UnaryResult = compilation.GetTypeByMetadataName("MagicOnion.UnaryResult`1");
ClientStreamingResult = compilation.GetTypeByMetadataName("MagicOnion.ClientStreamingResult`2");
DuplexStreamingResult = compilation.GetTypeByMetadataName("MagicOnion.DuplexStreamingResult`2");
ServerStreamingResult = compilation.GetTypeByMetadataName("MagicOnion.ServerStreamingResult`1");
GenerateDefineIf = compilation.GetTypeByMetadataName("MagicOnion.GenerateDefineIfAttribute");
}

As a result, the following variables are null: UnaryResult, ClientStreamingResult, DuplexStreamingResult, ServerStreamingResult, GenerateDefineIf 

On searching  the following services, Marker and baseInterface are also null:
public MethodCollector(string csProjPath, IEnumerable<string> conditinalSymbols) {
var marker = compilation.GetTypeByMetadataName("IService`1");
baseInterface = compilation.GetTypeByMetadataName("MagicOnion.IService`1");
}

So moc.exe cannot find services in my application. Even if it find it though, it won't pass the verification of returning types in the following method:

void ExtractRequestResponseType(IMethodSymbol method, out MethodType methodType, out string requestType, out string responseType, out ITypeSymbol unwrappedOriginalResponseType)
        {
            var retType = method.ReturnType as INamedTypeSymbol;

            var constructedFrom = retType.ConstructedFrom;
            if (constructedFrom == typeReferences.TaskOfT)
            {
                retType = retType.TypeArguments[0] as INamedTypeSymbol;
                constructedFrom = retType.ConstructedFrom;
            }

            if (constructedFrom == typeReferences.UnaryResult)
            {
                methodType = MethodType.Unary;
                requestType = (method.Parameters.Length == 1) ? method.Parameters[0].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) : null;
                responseType = retType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                unwrappedOriginalResponseType = retType.TypeArguments[0];
            }
            else if (constructedFrom == typeReferences.ServerStreamingResult)
            {
                methodType = MethodType.ServerStreaming;
                requestType = (method.Parameters.Length == 1) ? method.Parameters[0].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) : null;
                responseType = retType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                unwrappedOriginalResponseType = retType.TypeArguments[0];
            }
            else if (constructedFrom == typeReferences.ClientStreamingResult)
            {
                methodType = MethodType.ClientStreaming;
                requestType = retType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                responseType = retType.TypeArguments[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                unwrappedOriginalResponseType = retType.TypeArguments[1];
            }
            else if (constructedFrom == typeReferences.DuplexStreamingResult)
            {
                methodType = MethodType.DuplexStreaming;
                requestType = retType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                responseType = retType.TypeArguments[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                unwrappedOriginalResponseType = retType.TypeArguments[1];
            }
            else
            {
                throw new Exception("Invalid Return Type, method:" + method.Name + " returnType:" + method.ReturnType);
            }
        }


There is also a workaround for the described case: in project Definition (Sandbox.ConsoleServerDefinition) specify not a link to the MagicOnion project, but the  link to the compiled dll file - in this case it works fine.

**Comment by neuecc** [comment]
new MagicOnion2's code generator maybe works.
