### ISSUE TITLE
Porting to Nintendo Switch

### ISSUE THREAD

**Issue by miv** [Cysharp/MagicOnion#460]
I've been tinkering with porting one of our project that uses Unity MagicOnion to Nintendo Switch, and found out that there is no GRPC C-client for NX platform anywhere on the internet. Porting GRPC to new platform is not trivial to say the least. 

Do you have plans to support Switch? 

PS: If you happen to have a compiled version of GRPC for switch i would be very grateful if you attach it :)

**Comment by neuecc** [comment]
You need to build gRPC Core yourself.
We have the plan that develop Pure C# RPC Client, it will work all platforms.
However we don't know when that will complete.
