### ISSUE TITLE
DateTime serialization exception 

### ISSUE THREAD

**Issue by zqlovejyc** [Cysharp/MagicOnion#462]
Similar to this issue: https://github.com/Cysharp/MagicOnion/issues/237

The exception details is : 
```c#
Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler.")
   at MagicOnion.Client.ResponseContext`1.Deserialize()
   at MagicOnion.UnaryResult`1.UnwrapResponse()
   at MagicOnionClient1.Program.Main(String[] args) in C:\Users\***\Desktop\MagicOnionSample\MagicOnionClient\Program.cs:line 41
```

Please see the attachment for details ！
[MagicOnionSample.zip](https://github.com/Cysharp/MagicOnion/files/7160812/MagicOnionSample.zip)

**Comment by handloong** [comment]
I have the same trouble, how to fix ?

**Comment by handloong** [comment]
I got it,
when addMagicUnion
you should be set default option like this.

`services.AddMagicOnion(configureOptions =>
            {
                configureOptions.SerializerOptions = MessagePackSerializer.DefaultOptions.WithResolver(
                     CompositeResolver.Create(
                     NativeDateTimeResolver.Instance,
                     StandardResolver.Instance
                 ));
            });
            `

**Comment by zqlovejyc** [comment]
> when server project addMagicUnion
> you should be set default option like this.
> 
> ```
> services.AddMagicOnion(configureOptions =>
>             {
>                 configureOptions.SerializerOptions = MessagePackSerializer.DefaultOptions.WithResolver(
>                      CompositeResolver.Create(
>                      NativeDateTimeResolver.Instance,
>                      StandardResolver.Instance
>                  ));
>             });
> ```

Thanks
