### ISSUE TITLE
Would it be possible to expose MethodHandler.BindHandler publicly, for ease of integration with non ASP gRPC?

### ISSUE THREAD

**Issue by AlexVallat** [Cysharp/MagicOnion#464]
I am trying to implement some IPC gRPC, and have found https://github.com/cyanfish/grpc-dotnet-namedpipes to be a good candidate. The entry point to make this work with MagicOnion appears to be the ServiceBinderBase - for a proto-generated gRPC interface you can do a `Greeter.BindService(namedPipeServer.ServiceBinder, new GreeterService());` sort of call to hook it up, but for MagicOnion this is tricker to do.

I've managed to make it work in a generic host (not ASP.net) with this:
```c#
Host.CreateDefaultBuilder()
    .ConfigureServices((_, services) =>
    {
        services.AddMagicOnion();
        services.AddHostedService<NamedPipeMagicOnionServer>();
    }).Build().Run();

public class NamedPipeMagicOnionServer : BackgroundService
{
    private readonly MagicOnionServiceDefinition _magicOnionServerServiceDefinition;
    private readonly NamedPipeServer _server = new NamedPipeServer("MyPipeName");

    public NamedPipeMagicOnionServer(MagicOnionServiceDefinition magicOnionServerServiceDefinition)
    {
        _magicOnionServerServiceDefinition = magicOnionServerServiceDefinition;
    }

    protected override Task ExecuteAsync(CancellationToken stoppingToken)
    {
        var bindMethod = typeof(MethodHandler).GetMethod("BindHandler", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic) ?? throw new FieldAccessException("Could not find MethodHandler.BindHandler method");
        foreach (var methodHandler in _magicOnionServerServiceDefinition.MethodHandlers)
        {
            bindMethod.Invoke(methodHandler, new object[] { _server.ServiceBinder });
        }

        _server.Start();

        return Task.CompletedTask;
    }

    public override Task StopAsync(CancellationToken cancellationToken)
    {
        _server.Kill();
        return base.StopAsync(cancellationToken);
    }

    public override void Dispose()
    {
        _server.Dispose();
        base.Dispose();
    }
}
```

But to make it work I had to use the internal `BindHandler` method. I'd like to request this be changed from internal to public so that it is considered part of the public API, and therefore more robust to breaking changes than using reflection to get at it like this.

Or, if there are serious problems with this approach and therefore a good reason to keep it non-public, I'd appreciate knowing that too!

**Comment by mayuki** [comment]
Well, that's interesting.

But, MagicOnion.Server is implemented on top of ASP.NET Core. So, it is possible that some code will be added in the future that depends on ASP.NET Core services, and it will not be possible to run outside a context of ASP.NET Core.

Currently, we cannot guarantee that it will work outside of ASP.NET Core.
