### ISSUE TITLE
Resolve rather than create instance of Service?

### ISSUE THREAD

**Issue by AlexVallat** [Cysharp/MagicOnion#465]
In https://github.com/Cysharp/MagicOnion/blob/c7609f8671c6126aa5dd1c753fb245146f9ce373/src/MagicOnion.Server/ServiceProviderHelper.cs#L13 you always create a new instance of the Service for every call.

Is there any reason this could not, instead, resolve `TServiceBase `from `context.ServiceProvider.GetRequiredService<TServiceBase>()`, allowing it to be registered as a singleton? Or is there a reason it must always be a new instance?

**Comment by mayuki** [comment]
`TServiceBase` (implementation of `IService<T>`) is the same as `Controller` in ASP.NET Core MVC and created on every request.
MagicOnion always requires a new instance of `TServiceBase` and is not designed to be reused.

**Comment by AlexVallat** [comment]
Understood, thanks. I will redesign my service with that in mind.
