### ISSUE TITLE
Generic interface for StreamingHubBase

### ISSUE THREAD

**Issue by NissimOha** [Cysharp/MagicOnion#474]
Hi,

There is a way to make generic StreamingHubBase (for reuse base functionality)?

I tried something like this:

    public class NotificationServiceBase<TCallback> : StreamingHubBase<INotificationService<TCallback>, TCallback>,
        INotificationService<TCallback>
    {
        public Task Subscribe(string subscriberId)
        {
            ...
        }

        public Task Unsubscribe(string subscriberId)
        {
            ...
        }
    }

    public class NotificationService : NotificationServiceBase<INotificationServiceCallback>
	{ .... }

I tried even to register it manually:

    public void ConfigureServices(IServiceCollection services)
            {
            services.AddGrpc();
            services.AddSingleton<IStreamingHub<INotificationService<INotificationServiceCallback>,
                INotificationServiceCallback>, NotificationService>();

            services.AddMagicOnion(assemblies);
            ..
            }

but I got this exception:

    Autofac.Core.DependencyResolutionException: 'An exception was thrown while activating 
    λ:MagicOnion.Server.Glue.MagicOnionServiceDefinitionGlueDescriptor -> λ:MagicOnion.Server.MagicOnionServiceDefinition.'
    ArgumentException: Type Host.Grpc.Services.NotificationServiceBase`1[TCallback] is a generic type definition (Parameter 'type')

Any solution or workaround?

Regards,
Nissim Ohayon

**Comment by mayuki** [comment]
The base class should have an `Ignore` attribute or be `abstract`.
