### ISSUE TITLE
Support dependency injection for services

### ISSUE THREAD

**Issue by daemon4d** [Cysharp/MagicOnion#48]
Hello. It will be really good if it will be possible to use DI for services. 
For example this one https://autofac.org/
As I understand now it's not possible because services are created with Reflection instead of DI container.

**Comment by neuecc** [comment]
Yes, I've investigated about DI - https://github.com/neuecc/MicroResolver/
I should support DI.
Thank you.

**Comment by neuecc** [comment]
not yet resolved but issue was moved to 64.
