### ISSUE TITLE
I don't have the startup.cs file in my Grpc server project

### ISSUE THREAD

**Issue by ComptonAlvaro** [Cysharp/MagicOnion#481]
Hello:

I am trying to create a new Gprc project in Visual Studio 2022, and in the documentation it is said that I have to edit the StartUp.cs file, but I don't have this file.

I should to edit ConfigureServices method and another more, I tried to search for this method in in the hole Grpc project, but I don't find anything.

I am using Visual Studio 2022 template to create the Grpc project, and I am using Net Core 6.0.

Perhaps in the new template of Visual Studio there is no this file?

Thanks so much.

EDIT: I have seen that it is because I am using Net Core 6, because in some examples with Net Core 5, there is a StartUp.cs file and the methods that I need to modify.

So I am wondering if I could use Magic Onion in a prject that use Net Core 6, and if it is possible, how could I do it? Because the documention is for Net Core 5.

Thanks so much.

**Comment by ehakan-veloxia** [comment]
If you're using the new gRPC template this is what the new MagicOnion enabled `Program.cs` should look like. Not much has changed, just the two methods in `Startup.cs` have been replaced with `builder.Service` and `app` in `Program.cs`

```csharp
var builder = WebApplication.CreateBuilder(args);

// other services
// builder.Service.AddFooBarService();

// MagicOnion service
builder.Services.AddMagicOnion();

var app = builder.Build();

// Map the endpoints
app.MapMagicOnionService();

app.Run();
```

**Comment by ComptonAlvaro** [comment]
Thanks for the help.

But I am getting an exceptión mapping the endpoint that tells:

"InvalidOperationException: Unable to find the required services. Please add all the required services by calling 'IServiceCollection.AddGrpc' inside the call to 'ConfigureServices(...)' in the application startup code."

**Comment by binhnguyen86** [comment]
You are missing the app.AddRouting before
app.MapMagicOnionService();
here the code:

app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapMagicOnionService();
            });

**Comment by felinepunch** [comment]
```
var builder = WebApplication.CreateBuilder(args);

// other services
// builder.Service.AddFooBarService();

builder.Services.AddGrpc();
// MagicOnion service
builder.Services.AddMagicOnion();

var app = builder.Build();

app.UseRouting();
// Map the endpoints
app.UseEndpoints(endpoints =>
        {
            endpoints.MapMagicOnionService();
        });

app.Run();
```
