### ISSUE TITLE
gRPC library update for reduce package size

### ISSUE THREAD

**Issue by doodoori2** [Cysharp/MagicOnion#490]
As you know, these days Google Play requires an APK file size of less than 150MB. 
https://developer.android.com/guide/app-bundle

And the file libgrpc_csharp_ext.so that embedded in this project is almost 50MB.
https://github.com/Cysharp/MagicOnion/tree/master/src/MagicOnion.Client.Unity/Assets/Plugins/Grpc.Core/runtimes/android

By the way, gRPC project already discussed about reducing the package size.
https://github.com/grpc/grpc/issues/25862
A comment of the PR says, the libgrpc_csharp_ext.x64.so is ~ 6MB from version 2.42. 

Currently, Magic Onion using gRPC version 2.23 
Do you guys have any plan to update gRPC version?
Or is there any expected problem when update the so file?

**Comment by parkycai** [comment]
Use following command to reduce the library size:

```
##Choose proper architecture
[NDK_PATH]\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64\aarch64-linux-android\bin\strip.exe" libgrpc_csharp_ext.so```
