### ISSUE TITLE
AWS ALB + MagicOnion + AspNet WebAPI, healthcheck and deploy

### ISSUE THREAD

**Issue by Danila24ru** [Cysharp/MagicOnion#495]
So, after two days of brain storm, I give up. How properly deploy server with grpc + webApi.
What I do on server:
AppSettings:
![изображение](https://user-images.githubusercontent.com/19823722/150676737-6639577c-445d-442d-b5cd-e8e9f3950634.png)
EndPoints:
![изображение](https://user-images.githubusercontent.com/19823722/150676788-ebaad1d0-c15b-459a-95c1-27ceab6a7f57.png)
Dockerfile:
```
EXPOSE 12345
EXPOSE 80
EXPOSE 443
```
On AWS:
TaskDefinition:
![изображение](https://user-images.githubusercontent.com/19823722/150677066-6826a861-7320-4058-b2f5-aff6ff3f274b.png)
TargetGroup:
![изображение](https://user-images.githubusercontent.com/19823722/150679605-e33e91bd-a281-4520-8993-144cc7388956.png)
![изображение](https://user-images.githubusercontent.com/19823722/150679653-7d63288c-eee3-4a2c-83f0-42dfd46c1d40.png)
So I set path of healthcheck to "/" as @locus84 mention https://github.com/Cysharp/MagicOnion/issues/491#issuecomment-1019297913 here (thanks for you). But with no luck :(

So for now i still can't get Healthy status.
Anyone help @mayuki @neuecc 
Maybe @locus84 can you provide more info how did you configure server? Thanks.
Also, i publish server with AWS Toolkit (VS),  (publish Container to AWS... button)

**Comment by mayuki** [comment]
If you want `/` to be used for health checking, then ALB health-check protocol should be HTTP/1, not gRPC.

Grpc.AspNetCore.HealthCheck has recently been released, so you may be able to use this for gRPC health checks.
https://www.nuget.org/packages/Grpc.AspNetCore.HealthChecks/

**Comment by Danila24ru** [comment]
@mayuki  Thank you!
I succesfuly integrated MO + WebAPI with ALB. I created two listeners/target groups one for grpc, one for api and bind them for same service.
I still use https://github.com/Cysharp/MagicOnion/issues/491#issuecomment-1019297913 But listen container port on 80 for grpc + "/" path for health check.
