### ISSUE TITLE
gRPC server host in Unity 5

### ISSUE THREAD

**Issue by TuancuongNguyen** [Cysharp/MagicOnion#50]
Hi Neuecc,
I've been studying your UnityClient and the MagicUnion & MessagePack lib. They are awesome!
I have the grpc  client hosted from a Unity 5 game (.Net 3.5) and it works great.
I have tried to host a grpc server from a Unity 5 game (.Net 3.5)  and wonder if it is possible with your plugin libraries? Please, give your advises. 
If it is possible, would you please give a basic instructions or guide lines or so. Very much appreciate it.
Thanks Neuecc.

**Comment by neuecc** [comment]
Thank you for trying.
I've dropped server hosting support on Unity(for security, complexity and binary size).
so answer is can not host, it means can not connect Unity to Unity.
Currently only supports Unity to Server to Unity.

**Comment by TuancuongNguyen** [comment]
Hi Neuecc,
Thanks for a quick reply. That helps and I will move to the other approach.

**Comment by WeitesFeld** [comment]
@neuecc 
So I't wont be possible to use MagicOnion in its current state as a server in a C# Xamarin iOS context? If it is indeed possible, may you be so kind to post a short tutorial on how to get it done?

**Comment by neuecc** [comment]
I do not know because I have not tried it,
I think that it is impossible to use Xamarin iOS as a server.
