### ISSUE TITLE
Future of WebGl support

### ISSUE THREAD

**Issue by paasso** [Cysharp/MagicOnion#504]
What is there future of WebGl support? Wil it be only server side streaming or some magic with websocket?

**Comment by binhnguyen86** [comment]
I think it can achieved by using: Grpc.Net.Client and Grpc.Net.Client.Web

**Comment by chinpok** [comment]
> 

No, i tried

**Comment by miv** [comment]
I can attest that WebGL working great with new https://github.com/Cysharp/GrpcWebSocketBridge .
