### ISSUE TITLE
Does services use connected hubs(if any) in the background?

### ISSUE THREAD

**Issue by feritzcan2** [Cysharp/MagicOnion#506]
Hello, I have some questions. I don't know if they are not logical questions or not since I'm new in gRPC  but I'm searching answer for days and could get one. I hope somebody may answer my question...

We build a game backend using magic onion....
   We have some services for clan, friends. ( Add friend, Create clan etc.)
   We have a hub for game and clan chat.

1) Since client will always be connected to some hubs, I think that creating new connections through services is extra load. Are those request use the same connection if there any in the background since they use same channel? If so I guess services might be scoped as well as hubs? 

2) We will send user events and validate/update User every 30 seconds... Does making sync through open hub or another hub or through service matters in terms of server load? Speed wont be an issue here. 

3) We must create only one channel on client-side and reuse it for every service, hub  isn't it?

4) Is it result in the same performance, bandwidth to use 10x hubs 10x Services  vs  using only one hub to do all of the stuff?

Thank you very much.
I appreciate your answers

**Comment by feritzcan2** [comment]
@mayuki :(

**Comment by mayuki** [comment]
Sorry for the late reply.

We think that it is a case-by-case basis whether you should share channels and have multiple connections on one channel.

Having said that, we recommend in many cases that the game (high frequency real-time, such as events like unit movement or attacks) and other things (such as API calls or notifications like Unary) should be on separate channels.

Even when sharing a single channel, there is only one network communication connection, which can lead to unexpected delays if the multiplexed streams on that connection become overloaded.
By contrast, low frequency activities (e.g. real-time notifications or API calls) may benefit from sharing a channel, as this reduces the number of network connections on the server.

A frequency of about 30 seconds is usually not a problem, but as mentioned above, depending on the number of clients connecting at the same time and the size of the data.

Hub and Service (Unary) can share channels, but their lifetimes are different (they appear as separate requests to ASP.NET Core/gRPC).

It is recommended not to over-integrate Hubs for simplicity as they are stateful and having too many jobs in one Hub can make disconnecting and reconnecting a lot of work.

**Comment by binhnguyen86** [comment]
I built a game that had 50,000 CCU.
In my scenario, I have one channel for the hub and one channel for all services.
It's because I never think sharing hub's channel for service is a good idea.
