### ISSUE TITLE
Is MagicOnion Support IPC (Inter-process_communication) ?

### ISSUE THREAD

**Issue by leeveel** [Cysharp/MagicOnion#534]
https://docs.microsoft.com/en-us/aspnet/core/grpc/interprocess?view=aspnetcore-6.0

**Comment by mayuki** [comment]
We haven't verified it but expect it will probably work.
MagicOnion relies on gRPC protocol between Kestrel and Grpc.Net.Client.

If it does not work, please let us know.

**Comment by leeveel** [comment]
thanks a lot! I will try it.

**Comment by leeveel** [comment]
Ipc works fine with MagicOnion
