### ISSUE TITLE
No _channel.ShutdownAsync method

### ISSUE THREAD

**Issue by IKatyrov** [Cysharp/MagicOnion#542]
In unity, in the MagicOnion.Unity project, the GrpcChannelx class has a private readonly ChannelBase _channel field that calls the await _channel.ShutdownAsync().ConfigureAwait(false); method on line 275. But ChannelBase does not contain such a method.

**Comment by mayuki** [comment]
Check and update gRPC libraries in your project. `ChannelBase.ShutdownAsync` was introduced in v1.27.0 (Feb, 2020).
https://github.com/grpc/grpc/releases/tag/v1.27.0

**Comment by IKatyrov** [comment]
Thanks!

**Comment by FeMauri** [comment]
I'm having the same problem in version 2.46.5 of grpc, ChannelBase doesn't have a ShutdownAsync or ShutdownAsyncCore. It's also not using System.Threading.Tasks

**Comment by mayuki** [comment]
`ShutdownAsync` looks to be existing in that version of `ChannelBase`, what error do you see?

gRPC 1.46.5 (= 2.46.5 for .NET)
https://github.com/grpc/grpc/blob/v1.46.5/src/csharp/Grpc.Core.Api/ChannelBase.cs#L65-L80

**Comment by FeMauri** [comment]
I get an error on GrpcChannelx in lines 129 and 275 saying that shutdownasync and shutdownasynccore are not in the channelBase script. I can't find a way to add it or modify that dll.

**Comment by FeMauri** [comment]
![imagen](https://user-images.githubusercontent.com/65312872/210411322-120c3fb6-97e8-4bc0-86c4-28b59b2a9e0e.png)

@mayuki That is the error I even tried using older libraries and nothing changed
