### ISSUE TITLE
Methods inherited from other interfaces are ignored

### ISSUE THREAD

**Issue by AntonC9018** [Cysharp/MagicOnion#550]
The code generator for both services and the hub ignores methods that come from inherited interfaces. For example, in this piece of code, there will be no trace of Test1 in the generated code:
```csharp
public interface A
{
    Task Test1();
}
public interface B : A, IService<B>
{
    Task Test2();
}
```

**Comment by mayuki** [comment]
Sorry, It is not possible to create a combination of Service interfaces. 
This may become possible in the future, but at this time it is necessary to define them as a single interface.
