### ISSUE TITLE
StackOverflow exception when there is cycle reference

### ISSUE THREAD

**Issue by ComptonAlvaro** [Cysharp/MagicOnion#551]
I have 2 classes that one have to a property to the other and  viceversa. In this case, I get a stackoverflow exception.

I am using to contractless serialization

`MessagePackSerializer.DefaultOptions = MessagePack.Resolvers.ContractlessStandardResolver.Options;`

The code is this:

```
public class ClaseTest2
{
    public ClaseTest3 Clase3 {get; set; }
}



public class ClaseTest3
{
    public ClaseTest2 Clase2;
}



public class ClaseTest4
{
    public ClaseTest4()
    {
            ClaseTest2 miClase2 = new ClaseTest2();
            ClaseTest3 miClase3 = new ClaseTest3();


            miClase2.Clase3 = miClase3;
            miClase3.Clase2 = miClase2;


            this.Clase2 = miClase2;
    }


    public ClaseTest2 Clase2;
}
```

Does it not allow cycling reference? Because for example in EF Core, sometimes there are bidirectional navigation properties, and if there are this kind of references, the it would not possible to serialize this classes.

Thank you so much.

**Comment by mayuki** [comment]
This problem is not within the scope of MagicOnion. Please see the following Issue.
https://github.com/neuecc/MessagePack-CSharp/issues/57
