### ISSUE TITLE
Null check for required fields during communication

### ISSUE THREAD

**Issue by ry18847** [Cysharp/MagicOnion#560]
In communication between the client and server, I would like to automatically check for `null` (or any validation) in the arguments and return values of service methods when they contain required items.

```C#
[MessagePackObject(true)]
public class MyData
{
      public string RequiredMember { get; }
      public string? OptionalMember { get; }
}

public interface IMyService : IService<IMyService>
{
      // I want to receive an exception at the caller before send to server if data.RequiredMember is null or empty
      UnaryResult<Nil> Execute(MyData data);
}

```

MessagePack's `IMessagePackSerializationCallbackReceiver` could be used to check null in `BeforeSerialize()` and throw an exception. 
The exception would be set to the `MessagePackSerializationException.InnerException`, so it was possible to validate it in the client filter.

Would a simpler validation method be standard in MagicOnion?
If not, I will build my own SourceGenerator to handle this.

**Comment by mayuki** [comment]
Currently, MagicOnion has no extension points to intercept between deserializing a request and calling a service method.
If you want to validate the value of a request, you need to do so during deserialization or validate it within a service method.

**Comment by ry18847** [comment]
Ok, thank you for the reply.
