### ISSUE TITLE
Server to client requests

### ISSUE THREAD

**Issue by ProkopRandacek** [Cysharp/MagicOnion#561]
Hi,
Is is possible for the server to request data from the client?

If I understand it correctly, the hub receiver methods have to return void, so they can't be used to querry data. And services are only client->server requests.

Should I create a service that is implemented on the client? I'm not sure if that is the intended usage.

Sorry if I missed something obvious in the docs
Thanks for any help

**Comment by mayuki** [comment]
You are correct, MagicOnion cannot get the return value of a client call from the server.
If the server wants to receive the result, it must call a method on the server from the client to notify the result.

**Comment by ProkopRandacek** [comment]
Alright. Thanks!
