### ISSUE TITLE
Enabling compression?

### ISSUE THREAD

**Issue by AdamFrisby** [Cysharp/MagicOnion#562]
Hi - any pointers on where to enable MessagePack compression in MagicOnion?

The  serializerOptions: MessagePackSerializerOptions.Standard.WithCompression(MessagePackCompression.Lz4BlockArray) in the client-side requests to StreamingHubClient.ConnectAsync makes sense, but I presume this needs to be enabled in the server somehow as well?

Thankyou! (great library btw)

**Comment by mwegner** [comment]
We do this server-side, which I think is right?

```csharp
builder.Services.Configure<MagicOnionOptions>(options =>
{
	// messagepack options for magiconion-managed serialization
	options.SerializerOptions = MessagePackSerializerOptions.Standard
		.WithCompression(MessagePackCompression.Lz4BlockArray)
		.WithResolver(MessagePackX.GetResolver());

	options.IsReturnExceptionStackTraceInErrorDetail = true;
});
```

(That `MessagePackX` is an extension class that returns our resolver--could skip that or plug in your resolvers there)

**Comment by AdamFrisby** [comment]
Alas, I need to re-open this as the method has changed, I've tried a few variations, but they're not longer working. Does anyone know the current correct method for this?

**Comment by AdamFrisby** [comment]
And this is what is needed now.

```
MagicOnionSerializerProvider.Default =
MessagePackMagicOnionSerializerProvider.Default.WithOptions(MessagePackSerializerOptions.Standard.WithCompression(MessagePackCompression.Lz4BlockArray));
```
