### ISSUE TITLE
Can i use MagicOnion in client side on a browser?

### ISSUE THREAD

**Issue by Sajjad2678** [Cysharp/MagicOnion#563]
Hi guys. microsoft says grpc is not supported on browsers because http2 is not supported. but there is a grpc web . is it supported in MagicOnion?

**Comment by miv** [comment]
We're using https://github.com/Cysharp/GrpcWebSocketBridge and it works great

**Comment by Sajjad2678** [comment]
First off all Thank you for your reply. so according to you, I can implement the server with MagicOnion and in the client, I use[ [GrpcWebSocketBridge](https://github.com/Cysharp/GrpcWebSocketBridge)](https://github.com/Cysharp/GrpcWebSocketBridge) for web App. am I right?

**Comment by miv** [comment]
Yup. The setup itself has a learning curve and server pretty much must be a C# server, but it works pretty good. You can check our webgl version here https://id.fx.gl/play/dnl

Our first version has had just the most simple proxy-server game<->c#-proxy-with-mo<->old-game-server, but now we transitioning to c# server fully.

GrpcWebSocketBridge repo has a two full example, one with MO and one without it.

**Comment by Sajjad2678** [comment]
thank you. also, your game is good.
