### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by FoxTes** [Cysharp/MagicOnion#565]
Hello. I really liked your project.

I would like to know (unfortunately not in the examples). How to implement dependencies in the client part. For example, ASP Net.
Can I register the service as a singleton and get "chanel" from there, or does its lifetime depend on the scope of use?
Can I give an example?

**Comment by binhnguyen86** [comment]
Magic Onion is server-side only
If you mean DI on Unity, you can try to use Zenject.

**Comment by FoxTes** [comment]
For example, ms has a factory for this, which can be injected

https://learn.microsoft.com/ru-ru/aspnet/core/grpc/clientfactory?view=aspnetcore-7.0

**Comment by mayuki** [comment]
There is no official support for this, but you can inject clients with the following code:

```csharp
public static IHttpClientBuilder AddMagicOnionClient<T>(this IServiceCollection services, string name, Action<GrpcClientFactoryOptions>? configureClient = default)
    where T : class, IService<T>
{
    return services.AddGrpcClient<T>(name, (sp, options) =>
    {
        options.Creator = (callInvoker) => MagicOnionClient.Create<T>(callInvoker);
        configureClient?.Invoke(options);
    });
}
```
