### ISSUE TITLE
Does MagicOnion code generator support multiple Servers?

### ISSUE THREAD

**Issue by c9234** [Cysharp/MagicOnion#566]
Using multiple MagicOnion Servers in a single Unity client, I had the following troubles in MagicOnion code  generator.
We have temporarily handled them as follows, but are there any solutions or workarounds?

- MagicOnionInitializer partial class conflicts in MagicOnion.Generated.cs

MagicOnionInitializer conflicts in MagicOnion namespace, so register method does not work as expected. 
I set `NameSpace` and `UnuseUnityAttr` params in code generator to avoid using generated MagicOnionInitializer, and implemented MagicOnionInitializer manually.

- Resolver namespace conflicts in mpc_generated.cs

~~Resolver namespace conflicts, so I cannot register resolvers in StaticCompositeResolver.
I rewrote the namespace manually.~~
I set `NameSpace` param in message pack generator.

Thank you for your help.

**Comment by c9234** [comment]
I missed the params of the message pack generator, so I set these params and resolved resolver namespace issue.

**Comment by mayuki** [comment]
Can' t you separate namespace and generated files for each server in your project?
```
moc -i Foo.csproj -o MagicOnion.Generated.Foo.cs -NameSpace MagicOnion.Foo
moc -i Bar.csproj -o MagicOnion.Generated.Bar.cs -NameSpace MagicOnion.Bar
```

**Comment by c9234** [comment]
Work as expected! Thanks a lot.
