### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by FoxTes** [Cysharp/MagicOnion#568]
Hello. I have written a couple of tests to compare performance against REST.

The results saddened me. The usual http client turns out to be faster in speed and more optimal in memory.

![image](https://user-images.githubusercontent.com/55885862/203921222-0f08e0e8-6dbe-4489-9495-943e3c458980.png)
![image](https://user-images.githubusercontent.com/55885862/203921288-50a8d9be-6644-4224-99c7-1ffc1307dffc.png)
![image](https://user-images.githubusercontent.com/55885862/203921563-d5d51153-6582-4bd2-8785-dc04f3f70c28.png)

Is it possible if there are any tips to improve performance?

**Comment by FoxTes** [comment]
Does it make sense to show the code?

**Comment by GustafValentine** [comment]
@FoxTes; could you try again after changing the following;

1) remove the 'true' parameter from [MessagePackObject]
2) add [Key(0)] to Date, [Key(1)] to TemperatureC, [Key(2)] to Summary
3) add [IgnoreMember] to TemperatureF

You should obtain better results.
