### ISSUE TITLE
Getting MagicOnion working with AirSim (MessagePack)

### ISSUE THREAD

**Issue by tank104** [Cysharp/MagicOnion#569]
Hi,
Firstly nice work on this library- looks like great packages!

I am trying to get this working with AirSim - that uses MessagePack RPC - which I believe MagicOnion is.

This code in Python works:
```
client = msgpackrpc.Client(msgpackrpc.Address(ip, port), timeout = timeout_value, pack_encoding = 'utf-8', unpack_encoding = 'utf-8')
return self.client.call('isApiControlEnabled', vehicle_name)
```

And the code I have to do similiar is this:
```
  public interface IAirSimService : IService<IAirSimService>
  {
    UnaryResult<bool> isApiControlEnabled();// string vehicle_name = "");

.....
      var channel = GrpcChannel.ForAddress("http://localhost:41451");
      var client = MagicOnionClient.Create<IAirSimService>(channel);
      var result = await client.isApiControlEnabled();
```

However this doesn't work and crashes AirSim.  My knowledge on both RPC and MesagePack is limited - but I have checked wirehsakr, and can't find why the messages are different, but they are.

Any pointers or ideas on how to make this work?

**Comment by tank104** [comment]
Not sure if it helps but this is the message from python client:

[148, 0, 0, 179, 105, 115, 65, 112, 105, 67, 111, 110, 116, 114, 111, 108, 69, 110, 97, 98, 108, 101, 100, 145, 160]

Which unpacks to (using this https://kawanet.github.io/msgpack-lite/):
[
  0,
  0,
  "isApiControlEnabled",
  [
    ""
  ]
]

The example above passes this (which doesn't even work in that msgpack tool):
0000   02 00 00 00 45 00 00 dc ad 05 40 00 80 06 00 00   ....E.....@.....
0010   7f 00 00 01 7f 00 00 01 cc 45 a1 eb 01 53 ae c8   .........E...S..
0020   ae a2 91 07 50 18 04 ff bd 4e 00 00 00 00 93 01   ....P....N......
0030   04 00 00 00 01 83 86 01 0f 31 32 37 2e 30 2e 30   .........127.0.0
0040   2e 31 3a 34 31 34 35 31 04 23 2f 49 41 69 72 53   .1:41451.#/IAirS
0050   69 6d 53 65 72 76 69 63 65 2f 69 73 41 70 69 43   imService/isApiC
0060   6f 6e 74 72 6f 6c 45 6e 61 62 6c 65 64 0f 2b 14   ontrolEnabled.+.
0070   67 72 70 63 2d 64 6f 74 6e 65 74 2f 32 2e 33 39   grpc-dotnet/2.39
0080   2e 30 2e 30 00 02 74 65 08 74 72 61 69 6c 65 72   .0.0..te.trailer
0090   73 00 14 67 72 70 63 2d 61 63 63 65 70 74 2d 65   s..grpc-accept-e
00a0   6e 63 6f 64 69 6e 67 0d 69 64 65 6e 74 69 74 79   ncoding.identity
00b0   2c 67 7a 69 70 0f 10 10 61 70 70 6c 69 63 61 74   ,gzip...applicat
00c0   69 6f 6e 2f 67 72 70 63 00 00 06 00 00 00 00 00   ion/grpc........
00d0   01 00 00 00 00 01 a0 00 00 00 00 01 00 00 00 01   ................

**Comment by tank104** [comment]
Using MessagePack alone gives the right output too:
MessagePackSerializer.Serialize(new object[] { 0, msgCounter++, "isApiControlEnabled", new string[] { "" } });

94 D2 00 00 00 00 D2 00 00 00 00 B3 69 73 41 70 69 43 6F 6E 74 72 6F 6C 45 6E 61 62 6C 65 64 91 A0

So somethng with the way I am using MagicOnionClient

**Comment by tank104** [comment]
(Forgot to mention I also tried this setup:

```
  public interface IAirSimService : IService<IAirSimService>
  {
    UnaryResult<bool> isApiControlEnabled(Object[] values);

....

await client.isApiControlEnabled(new object[] { 0, msgCounter++, "isApiControlEnabled", new string[] { "" } });// new object[] { 0, msgCounter++, "isApiControlEnabled", new string[] { "" } });

```

with no luck either

**Comment by Alezy80** [comment]
MagicOnion is totally unrelated with MessagePack RPC and can't communicate with it. MagicOnion uses gRPC for network calls with serialization by MessagePack.

**Comment by tank104** [comment]
Ah right sorry so I have missed understood.

Although they sound identical to me what your saying, I am guessing for you who knows a lot about it they are rather different.

I gRPC not an implementation of RPC?

don’t suppose you have any ideas to point me in the right direction?

**Comment by Alezy80** [comment]
RCP is common name for Remote Procedure Call, it is not one concrete technology. MessagePack RPC and gRPC has different, not compatible implementations. MessagePack RPC seems look abandoned. 
As you already see in another repo, people recommend look into https://github.com/yfakariya/msgpack-rpc-cli/wiki/Quick-start,
but it implements only client.

**Comment by tank104** [comment]
@Alezy80 thanks so much for taking the time to reply - and appreciate the response.

I was worried I was completely misunderstanding something and it turns out I was quite wrong in this case.

I saw that repo - it was just very old, and yours was up to date, but alas, will revert to that now.
