### ISSUE TITLE
Grpc.Core.RpcException:“Status(StatusCode=Unimplemented, Detail="")”

### ISSUE THREAD

**Issue by zqlovejyc** [Cysharp/MagicOnion#57]
When I implements IService<T> In  single Library, Then will throw a exception like issue title.
but I implements it in Server project. It's Successful.
I read souce code ,then find this code:
( code in MagicOnionEngine.cs of line 40)

        /// <summary>
        /// Search MagicOnion service from entry assembly.
        /// </summary>
        public static MagicOnionServiceDefinition BuildServerServiceDefinition(MagicOnionOptions options)
        {
            return BuildServerServiceDefinition(new[] { Assembly.GetEntryAssembly() }, options);
        }

I think you'd better change Assembly.GetEntryAssembly to Assembly.GetExecutingAssembly

**Comment by CCEVEN** [comment]
Use this
`
public static MagicOnionServiceDefinition BuildServerServiceDefinition(Assembly[] searchAssemblies, MagicOnionOptions option)
`
