### ISSUE TITLE
Initial MagicOnion setup on Unity fails with errors from DynamicClientAssemblyHolder

### ISSUE THREAD

**Issue by SeungHuLee** [Cysharp/MagicOnion#602]
First of all, Thank you for developing and sharing this amazing library.

By the news of MagicOnion 5 release, I started to setup basic environment following readme. 
And I got stuck with some errors from DynamicClientAssemblyHolder. Can you help me if I'm missing any instructions?

![image](https://user-images.githubusercontent.com/39406255/211506226-2469e760-9555-4cfb-a666-f3872e579995.png)

Unity Version: 2021.3.16f1
### Pre-Installed 
- MessagePack for C# [v2.5.64-alpha](https://github.com/neuecc/MessagePack-CSharp/releases/tag/v2.5.64-alpha)
- grpc_unity_package.2.47.0-dev202204190851

### PlayerSettings
- Windows Standalone IL2CPP, .NET Standard 2.1 (Did the IL2CPP guideline provided in readme)

### Reproduction
- Make new Unity 3D Project
- Install MessagePack, grpc with versions stated above
- Install MagicOnion 5.0.2 unitypackage

I think it has something to do with DynamicClientAssemblyHolder couldn't find reference to DynamicAssembly because of directives given in DynamicAssembly.
Maybe need more directives for DynamicClient related codes? 

![image](https://user-images.githubusercontent.com/39406255/211507355-125478de-62e0-48d2-9dbf-554ac5f42159.png)
![image](https://user-images.githubusercontent.com/39406255/211507608-198d1ff6-6d8c-41dc-8580-330a6ff757d4.png)

**Comment by FreshL4ma** [comment]
This issue goes away when you use the AOT-Code Generator (or "moc") commandline tool which you will need for IL2CPP! The reference "DynamicAssembly" will be defined in the generated script. It is detailed in 
[this section](https://github.com/Cysharp/MagicOnion#moc-magiconion-codegen-command-line-tool). I set the input parameter to the my Server-Client-Shared csproj though :)

**Comment by mwegner** [comment]
You shouldn't need generated code for the editor (or Mono builds).

Try using the sample project as a starting point here: https://github.com/Cysharp/MagicOnion/tree/main/samples/ChatApp

**Comment by FreshL4ma** [comment]
Oh my mistake I miss remembered :) A simple fix that doesn't require commenting anything (and still use IL2CPP) out is to set ApiCompatibilityLevel in the ProjectSettings to .NET Framework instead of .NET Standard 2.1. Because for some cases, like building for Android, IL2CPP is required.

**Comment by SeungHuLee** [comment]
This seems solved in [#606](https://github.com/Cysharp/MagicOnion/pull/606). Closing!
