### ISSUE TITLE
Beraking change: Excludes non-public services and hubs when collecting types

### ISSUE THREAD

**Issue by Alezy80** [Cysharp/MagicOnion#607]
After upgrading to v5 my services are all "unimplemented", because of MR #555 . There is no information about it in changelog. Can you allow to search not public types, maybe as option?

**Comment by mayuki** [comment]
Oops, sorry.

The same as when ASP.NET Core MVC discovers controllers, there is a workaround but no such thing as a bool option.
If you want to target non-public services, there is a way to manually collect the types and pass them to `AddMagicOnion`.

```csharp
var types = assembly
    .SelectMany(x =>
    {
        try
        {
            return x.GetTypes()
                .Where(x => typeof(IServiceMarker).IsAssignableFrom(x))
                .Where(x => x.GetCustomAttribute<IgnoreAttribute>(false) == null)
                .Where(x => !x.IsAbstract && !x.IsGenericTypeDefinition);
        }
        catch (ReflectionTypeLoadException ex)
        {
            return Array.Empty<Type>();
        }
    });

services.AddMagicOnion(types);
```

When MagicOnion implicitly collects types for a service, it also scans the assembly and just uses the public types.
