### ISSUE TITLE
.net 7 Server as Console Application

### ISSUE THREAD

**Issue by devopg** [Cysharp/MagicOnion#609]
Hello how can i initialize server with .net 7 Console Application without use DI and ServiceCollection?

**Comment by mayuki** [comment]
MagicOnion server is built on top of ASP.NET Core, it is not possible to run without DI and IServiceCollection.

**Comment by AshIceLoky** [comment]
Do you have a sample with a magiconion server un a console app in .net 7 with the last version ?
My program works with v3.13 and I can't find a sample for the last revision
thanks
