### ISSUE TITLE
Build error when targeting .Net Standard 2.0 and enabling IL2CPP.

### ISSUE THREAD

**Issue by hs-playt** [Cysharp/MagicOnion#617]
Hi,
I recently migrated from 4.5.2 to 5.1.2.
I encountered an build error in Unity 2020.3 while using IL2CPP and targeting .Net 2.0 Standard.
Here are the details of the error:

`Assets/Scripts/MagicOnion/MagicOnion.Client/MagicOnionClientFactoryProvider.cs(99,86): error CS0234: The type or namespace name 'DynamicClientBuilder' does not exist in the namespace 'MagicOnion.Client.DynamicClient' (are you missing an assembly reference?)`

After examining the source code, I found a suspicious line in the `MagicOnionClientFactoryProvider.cs` file. Specifically, 
`#if ((!ENABLE_IL2CPP || UNITY_EDITOR) && !NET_STANDARD_2_0)` on line 16 does not match 
`"#if ((ENABLE_IL2CPP && !UNITY_EDITOR) || !NET_STANDARD_2_0)"` on line 80.

Thank you for your attention to this matter.

**Comment by aldetkov** [comment]
I have same problem :(
I 2 days dont enable the plugin on webGl
