### ISSUE TITLE
v5: Breaking change in server filter not catching exceptions from serializers

### ISSUE THREAD

**Issue by dave-yotta** [Cysharp/MagicOnion#618]
Hopefully there is an easy fix for this - we were previously raising errors in the serializers we provide to magiconion.

We also then provide additional information within a MagicOnionFilterAttribute by using a `try { next(); } catch { context.CallContext.ResponseTrailers.Add; throw; }`.

That additional information was used to reconstruct the true exception from the RPCException on the other side.

Since trying to update to v5 those serializer exceptions are no longer raised from `next()` in the filter, so we are unable to do this any more.

Any advice?  Can these be caught and rethrown in a different place now?  Is there any way we can write to the response trailers directly from a serializer?  Perhaps there is a special type of exception we can raise that will marshal it's information?

The actual use case, incase you wonder, is: we have an out of process c# scripting service (roslyn).  We want to differentiate between serialization failures that are real server errors in our coding of the serializers, or if the user has managed to return a type that is not supported by our serializer (which we advise them in the error and treat as bad request).

**Comment by mayuki** [comment]
We apologize for the breaking change. This is due to the reason that v5 is rebuilt on top of grpc-dotnet's serialization (marshalling) mechanism.
For example, a generic gRPC using protobufs would similarly have no way to catch an exception caused by an invalid protobuf.

I think the only way to catch exceptions when deserializing gRPC messages is to use ASP.NET Core Middleware.

**Comment by NikoKapalos** [comment]
Hello! I'm working on the same project Dave mentions above. Our goal is essentially to catch our CustomException that we throw during serialisation, and pass the appropriate trailers along, so we can reconstruct it from the RpcException we catch in the ClientFilter. We tried grpc interceptors and ASP.NET Core Middleware with try/catch blocks but the error is either thrown after the end of the block is reached, or it simply doesn't catch it. Any other ideas we could try..?
