### ISSUE TITLE
Internal service class not found in v5.0

### ISSUE THREAD

**Issue by ry18847** [Cysharp/MagicOnion#629]
I upgraded from v4.5.2 to v5.1.2, and now the service class I accidentally defined in `internal` cannot be called from the client.
Both `Grpc.AspNetCore` version is 4.5.2.
Is this an intended breaking change in v5.0? 

Service Interface:
```C#
public interface IHelloWorld : IService<IHelloWorld>
{
    UnaryResult<string> Call();
}
```

Service Class:
```C#
internal class HelloWorld : ServiceBase<IHelloWorld>, IHelloWorld
{
    public UnaryResult<string> Call()
    {
        return new UnaryResult<string>("hello world");
    }
}
```

Client:
```C#
using Common;
using Grpc.Net.Client;
using MagicOnion.Client;

var channel = GrpcChannel.ForAddress("http://localhost:5000");
var client = MagicOnionClient.Create<IHelloWorld>(channel);
var result = await client.Call();
Console.WriteLine($"Result: {result}");

```

When this service is called from a client, v.4.5.2 returns "hello world", but v5.1.2 throws `Grpc.Core.RpcException: 'Status(StatusCode="Unimplemented", Detail="Service is unimplemented.")'`.
It seems obvious that we cannot call the `internal` service class , but I'm afraid I would be very happy if you could put it in the Readme.md, just in case.

**Comment by mayuki** [comment]
Duplicate #607

Sorry for the inconvenience, MagicOnion 5.x now collects only public types by default.
