### ISSUE TITLE
Add MagicOnion.Hosting

### ISSUE THREAD

**Issue by neuecc** [Cysharp/MagicOnion#63]
How to host on [.NET Generic Host](https://docs.microsoft.com/ja-jp/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2)
and create middleware to easy to host.

**Comment by itn3000** [comment]
[I tried implementing](https://github.com/itn3000/magiconionhostingtest/tree/master/MagicOnion.Extensions.Hosting).
current considerations are
* extension method interface(`MagicOnionServerServiceExtension.UseMagicOnion`)
* namespace(`MagicOnion.Hosting` is better?)

If you like it, I will create PR.

**Comment by neuecc** [comment]
Thanks, yes, i want to your PR.

UseMagicOnion is no problem.
namespace, I think `MagicOnion.Hosting` is good.

**Comment by itn3000** [comment]
PR was merged(#78), thank you.

**Comment by neuecc** [comment]
I've upload to NuGet.
