### ISSUE TITLE
NET_STANDARD_2_0(1) doesn't support DynamicMagicOnionClientFactoryProvider ?

### ISSUE THREAD

**Issue by goldsphere48** [Cysharp/MagicOnion#634]
In the source of MagicOnionClientFactoryProvider I've seen this restrictions:
```
public static IMagicOnionClientFactoryProvider Default { get; set; }
#if ((!ENABLE_IL2CPP || UNITY_EDITOR) && !NET_STANDARD_2_0)
            = DynamicMagicOnionClientFactoryProvider.Instance;
#else
            = DynamicNotSupportedMagicOnionClientFactoryProvider.Instance;
#endif
```

Am I right that if we are using net stadndart 2.0 or 2.1 we can't use DynamicMagicOnionClientFactoryProvider and we should configure generation code by guide from documentation ? I just setuped empty Unity project with Magic onion. And when I've started client after server I 've got 
`InvalidOperationException: Unable to find a client factory of type 'Sample.Shared.Services.ISampleService'. If the application is running on IL2CPP or AOT, dynamic code generation is not supported. Please use the code generator (moc).`

I can push my sample on github and share with you if it can help you :)

**Comment by mayuki** [comment]
We currently do not support dynamic clients targeting the .NET Standard in Unity.
If you have a use case that requires it, please let us know.
