### ISSUE TITLE
DI support to create IService/IStreamingHub instance

### ISSUE THREAD

**Issue by neuecc** [Cysharp/MagicOnion#64]

**Comment by neuecc** [comment]
related #48

**Comment by vfrz** [comment]
Are you planning to add DI any time soon?

Thanks 😀

**Comment by neuecc** [comment]
I'm now trying to experiment that how to merge DI to a framework,
As a result of that, I have now created the following framework.
https://github.com/Cysharp/MicroBatchFramework/
Once this framework is completed and I can confirm that integration with DI is no problem,
I port it to MagicOnion.
That is not so distant future.

**Comment by neuecc** [comment]
2.1.0 support it.
