### ISSUE TITLE
How LTS Unity client should be treated?

### ISSUE THREAD

**Issue by artiku** [Cysharp/MagicOnion#645]
LTS Unity (2021.3.+) supports .Net Standard 2.1.
Thus should we treat Unity as a normal .net standard 2.1 client or we still have to use the unity installation guide with Grpc.Core as a dependency, whose support ends this month?

**Comment by artiku** [comment]
I guess not, due to insufficient support of HTTP/2 in Unity. 
Then I have the following question: 
Where should I get Grpc.Core libraries (based on the native code) for Unity if they dropped that experimental support for it?

**Comment by mayuki** [comment]
Duplicate #584

We are looking for a way to support gRPC based on grpc-dotnet (Grpc.Net.Client) in Unity.
We do not have anything to offer at this time but hope to provide an update in the near future.
