### ISSUE TITLE
Can MagicOnion achieve function overloading and separation of client and server interfaces.

### ISSUE THREAD

**Issue by weiyoucheng** [Cysharp/MagicOnion#648]
In protobuf net, I can separate function overloading and dependencies between client and server interfaces by marking the "ServiceAttribute" and "OperationAttribute" attributes above the interface declaration (sometimes we don't want the front-end to see the entity class structure information of the backend, such as not wanting the front-end to see a certain field and avoiding unnecessary dependencies) 。 Naming is a headache for many developers. If we can make function overloading, it will become much simpler. The following is a demonstration of using protobuf net to implement function overloading and separation of front-end and back-end interfaces. I am not sure if MagicOnion can also be implemented, and if not, will I consider adding it.

protobuf-net can achieve function overloading by marking the 'ServiceAttribute' attribute and the 'OperationAttribute' attribute : 

![Setp2](https://github.com/Cysharp/MagicOnion/assets/112521929/1a013ba3-43dc-412d-8257-90afcaa64596)

Define an interface that is the same as the server to break away from dependence on the server interface. By marking the "ServiceAttribute" attribute and adding a name attribute, the front-end can access the corresponding interface : 

![Setp0](https://github.com/Cysharp/MagicOnion/assets/112521929/12186f57-6114-486b-98d1-a0ea80354838)

An exception occurred when I used MagicOnion to perform the same operation :

![Setp3](https://github.com/Cysharp/MagicOnion/assets/112521929/389c2ad3-61da-4c11-91f2-aac82e3f37ec)

An exception also occurred while attempting to overload the function

![Setp4](https://github.com/Cysharp/MagicOnion/assets/112521929/f9e40bad-0364-4593-b624-68085df989bf)
![Setp5](https://github.com/Cysharp/MagicOnion/assets/112521929/0e8ffae9-3a31-4940-9ae7-ec0dedf128bd)

Demonstration project link: https://github.com/weiyoucheng/MagicOnionSimple

**Comment by mayuki** [comment]
There is no way to overload this at this time, but we could consider a way to explicitly specify service (interface) and method names.

**Comment by weiyoucheng** [comment]
Do you have any plans to add this feature in the future?

**Comment by licentia88** [comment]
I'm very much interested in this featuer
