### ISSUE TITLE
Pooling objects?

### ISSUE THREAD

**Issue by AdamFrisby** [Cysharp/MagicOnion#655]
Is there a way to get MagicOnion/MessagePack to use pooled data structures?

We're passing a few List<T>'s around that are quite heavy after decoding (1-2mb uncompressed), and it would be great if we could pool these - as currently we're causing memory fragmentation which Unity is struggling to recover.

(IL2CPP using `moc` generated serialisers, iOS/Android, Unity 2021 LTS)

**Comment by mayuki** [comment]
It may be possible to customize MessagePack's serialization process (Formatter) to use object pooling.
We have no plans to introduce object pooling into MagicOnion.
