### ISSUE TITLE
Will this work for WebGL applications?

### ISSUE THREAD

**Issue by AVOGames** [Cysharp/MagicOnion#685]
Will this work for WebGL applications?

**Comment by AByte-L** [comment]
> 是的，您应该将[GrpcWebSocketBridge](https://github.com/Cysharp/GrpcWebSocketBridge)与 MagicOnion 一起使用。工作完美。参见[示例](https://galaxycontrol.app)

How do you set this resolution, can you give a WebGLTemplate, thank you

**Comment by AByte-L** [comment]
> Yes, you should use [GrpcWebSocketBridge](https://github.com/Cysharp/GrpcWebSocketBridge) with MagicOnion. Works perfectly. See [Example](https://galaxycontrol.app)

Can you use https? I can only use http. Do I need to set something else
