### ISSUE TITLE
In my use, when creating a service client object, it will report an error. How to solve it? Thank you.

### ISSUE THREAD

**Issue by LeisurelyYang** [Cysharp/MagicOnion#72]
System.TypeInitializationException: “MagicOnion.Client.DynamicClient.Septnet.AI.Ocr.ServiceDefination.IUserServiceClient”Type initializer throws an exception. ---> System.TypeInitializationException: “MagicOnion.MagicOnionMarshallers”Type initializer throws an exception. ---> System.Reflection.ReflectionTypeLoadException: The type of one or more requests could not be loaded. For more information, please search LoaderExceptions props。
   IN System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   IN System.Reflection.RuntimeModule.GetTypes()
   IN System.Reflection.Assembly.GetTypes()
   IN MagicOnion.MagicOnionMarshallers..cctor()
   --- End of internal exception stack trace ---
   IN MagicOnion.Client.DynamicClient.Septnet.AI.Ocr.ServiceDefination.IUserServiceClient..cctor()
   ---End of internal exception stack trace ---
   IN System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   IN System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   IN System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   IN System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   IN System.Activator.CreateInstance(Type type, Object[] args)
   IN MagicOnion.Client.MagicOnionClient.Create[T](CallInvoker invoker, IFormatterResolver resolver)
   IN MagicOnion.Client.MagicOnionClient.Create[T](Channel channel)
   IN Septnet.AI.TestClient.Program.Test() location D:\Program\gitlab\septnet.ai.ocr\src\Septnet.AI.TestClient\Program.cs:line 34

**Comment by neuecc** [comment]
Thank you for reporting.
Would you show show `IUserServiceClient` definition?
