### ISSUE TITLE
Performance is very slow, taking 355ms for the Add function to return the result

### ISSUE THREAD

**Issue by QuocTan** [Cysharp/MagicOnion#735]
Here is my server-side and client-side code, Where did I go wrong?

![image](https://github.com/Cysharp/MagicOnion/assets/12717678/1eddf001-f6ab-49be-a904-91421d3ab671)

**Comment by osexpert** [comment]
How fast is the second time? First time of anything is always slow (cold start).

**Comment by QuocTan** [comment]
> How fast is the second time? First time of anything is always slow (cold start).

First time: 351ms
Second time: 4ms
