### ISSUE TITLE
support  webgl?

### ISSUE THREAD

**Issue by labyte** [Cysharp/MagicOnion#743]
I can use YetAnotherHttpHandler and GrpcWebSocketBridge to support webgl platform?

**Comment by mayuki** [comment]
It is possible to use MagicOnion on WebGL by using GrpcWebSocketBridge, but we are not in a state of official support or confirming it works.

**Comment by AByte-L** [comment]
Yes, but that means I can only use gRPC's C-core, not the new YetAnotherHttpHandler
