### ISSUE TITLE
error CS0305: Using the generic type 'MemoryPackWriter<TBufferWriter>' requires 1 type arguments

### ISSUE THREAD

**Issue by kimk-s** [Cysharp/MagicOnion#751]
I'm install MemoryPack 1.20.4 by NugetForUnity recently changed.
The error probably appears after this.
https://github.com/Cysharp/MemoryPack?tab=readme-ov-file#unity

<img width="972" alt="image" src="https://github.com/Cysharp/MagicOnion/assets/71550078/1c28c90c-80b3-4800-a09d-95736412fef9">

**Comment by 0x5143** [comment]
I have the same problem, solved with PR: https://github.com/Cysharp/MagicOnion/pull/757

**Comment by Rurouni** [comment]
@neuecc @mayuki  can we please merge the above PR, or maybe there is another workaround?

**Comment by mayuki** [comment]
Sorry for the late reply, but we have just released version 6.1.3 with the PR merged.
https://github.com/Cysharp/MagicOnion/releases/tag/6.1.3
