### ISSUE TITLE
Telemetry

### ISSUE THREAD

**Issue by israellot** [Cysharp/MagicOnion#79]
One of the great advantages of using HTTP is the vast quantity of tools for telemetry/debug available. 
Having a HTTP/1 gateway is a great step, good job.
Is there any plans on integrating an ApplicationInsights provider for service methods like if they were webapi calls for example?

**Comment by neuecc** [comment]
I am assuming to use Datadog or Prometheus.
![image](https://user-images.githubusercontent.com/46207/51124158-f2be5e00-1860-11e9-83c1-bb9b81c05c3c.png)
(This is the Datadog graph of my application two years ago)

If we want to implement telemetry, we can add by IMagicOnionLogger and MagicOnionFilter.
It is the same for Datadog, Prometeheus, and ApplicationInsight.
