### ISSUE TITLE
could enhanced swagger ui for modify value ? 

### ISSUE THREAD

**Issue by vivid216** [Cysharp/MagicOnion#81]
I create a class Contract data model like a javabean, a interface like 
`public UnaryResult<int> Modify(string id, Contract c)`

when use swaggerUI for debug program ,  'Contract  c' in web is json string at one input textbox, it's hard to modify the Contract property.  could it generate the ‘Contract’ data model for multi property and multi input textbox ?

**Comment by neuecc** [comment]
Update to the new SwaggerUI https://github.com/Cysharp/MagicOnion/issues/59
(Live Demo https://petstore.swagger.io/ )
It put the template JSON model so maybe solved.
I'll try soon.

**Comment by vivid216** [comment]
wonderful

**Comment by neuecc** [comment]
#59 was finished, I'll release soon.

**Comment by neuecc** [comment]
2.1.0 released and it updates SwaggerUI.
