### ISSUE TITLE
Your console app Server example does nothing because it doesn't have any reference to the service.

### ISSUE THREAD

**Issue by Noemata** [Cysharp/MagicOnion#82]
How could this code do anything given it has no reference to the service?

        static void Main(string[] args)
        {
            GrpcEnvironment.SetLogger(new Grpc.Core.Logging.ConsoleLogger());

            // setup MagicOnion and option.
            var service = MagicOnionEngine.BuildServerServiceDefinition(isReturnExceptionStackTraceInErrorDetail: true);

            var server = new global::Grpc.Core.Server
            {
                Services = { service },
                Ports = { new ServerPort("localhost", 12345, ServerCredentials.Insecure) }
            };

            // launch gRPC Server.
            server.Start();

            // and wait.
            Console.ReadLine();
        }

**Comment by neuecc** [comment]
In default,
.NET Framework -> search types from all assemblies
.NET Core -> search types from entry assembly

This constraint has been used since it was not able to retrieve from all assembly references in .NET Core before.
However, now it is possible (perhaps).
I'll change search types from all assemblies, it will solve this annoying issue.

Thanks.

**Comment by Noemata** [comment]
I don't understand your reply.  I was just referring to your sample and the fact that it was not functional because it did not have any reference to MyFirstService.  The code below works as expected:

        static void Main(string[] args)
        {
            GrpcEnvironment.SetLogger(new Grpc.Core.Logging.ConsoleLogger());

            // setup MagicOnion and option.
            //var service = MagicOnionEngine.BuildServerServiceDefinition(isReturnExceptionStackTraceInErrorDetail: true);

            var service = MagicOnionEngine.BuildServerServiceDefinition(
                           targetTypes: new[] { typeof(MyFirstService) },
                           option: new MagicOnionOptions(isReturnExceptionStackTraceInErrorDetail: true));

            var server = new global::Grpc.Core.Server
            {
                Services = { service },
                Ports = { new ServerPort("localhost", 12345, ServerCredentials.Insecure) }
            };

            // launch gRPC Server.
            server.Start();

            // and wait.
            Console.ReadLine();
        }

The code on your landing page does nothing.

**Comment by neuecc** [comment]
code discover is

* from entry assembly https://github.com/Cysharp/MagicOnion/blob/master/src/MagicOnion/Server/MagicOnionEngine.cs#L42
* from assembly(s) https://github.com/Cysharp/MagicOnion/blob/master/src/MagicOnion/Server/MagicOnionEngine.cs#L50-L65
* from type(s) https://github.com/Cysharp/MagicOnion/blob/master/src/MagicOnion/Server/MagicOnionEngine.cs#L67

Basically, it is desirable that Service be discovered automatically without any special configuration.
I am concerned that the current implementation is away from it.

**Comment by Noemata** [comment]
I understand now.  This automatic capability does not appear to be working at the moment.  Note I have the service in a separate DLL.  I would prefer something like this:

    [RegisterMagicService(xxx.flags)]
    public class MyFirstService : ServiceBase<IMyFirstService>, IMyFirstService

And then something like:

            var types = this.GetType().GetTypeInfo().Assembly.DefinedTypes
                .Select(t => new { T = t, Mode = t.GetCustomAttribute<RegisterMagicService>()?.Mode })
                .Where(o => o.Mode != null && o.Mode != xxx.flag);

To locate the service within a given assembly or assemblies.

An explicit attribute makes it clearer what's going on when looking at the service layer.  You can go too far with the magic ;-)

Lastly, for a basic example, like what you have on your landing page, showing the explicit type reference is perfectly ok.  It does make things clearer.  You can always follow up with an explanation of how the "magic" is supposed to work in order to automatically locate the service reference.

**Comment by Noemata** [comment]
![image](https://user-images.githubusercontent.com/6632315/51642323-d1cbcc00-1f36-11e9-9011-468dcecd0df1.png)

Above is how I have things laid out.

**Comment by Noemata** [comment]
So this works.  It appears that having the service in a separate assembly was the problem:

// Client.cs
`using System;
using System.Threading.Tasks;

using Grpc.Core;
using MagicOnion;
using MagicOnion.Client;
using MagicOnion.Server;
using MagicServices;

namespace Client
{
    class Program
    {
        static void Main(string[] args)
        {
            GrpcEnvironment.SetLogger(new Grpc.Core.Logging.ConsoleLogger());

            Task.Run(() =>
            {
                ClientImpl();
            });

            Console.ReadLine();
        }

        static async void ClientImpl()
        {
            // standard gRPC channel
            var channel = new Channel("localhost", 12345, ChannelCredentials.Insecure);

            // create MagicOnion dynamic client proxy
            var client = MagicOnionClient.Create<IMyFirstService>(channel);
            // call method.
            var result = await client.SumAsync(100, 200);
            Console.WriteLine("Client Received:" + result);
            result = await client.SumAsync(10, 10);
            Console.WriteLine("Client Received:" + result);
        }
    }
}
`

// Server.cs
`using System;
using System.Threading.Tasks;

using Grpc.Core;
using MagicOnion;
using MagicOnion.Client;
using MagicOnion.Server;
using MagicServices;

namespace Server
{
    // implement RPC service to Server Project.
    // inehrit ServiceBase<interface>, interface
    public class MyFirstService : ServiceBase<IMyFirstService>, IMyFirstService
    {
        public async UnaryResult<int> SumAsync(int x, int y)
        {
            Logger.Debug($"Received:{x}, {y}");

            return x + y;
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            GrpcEnvironment.SetLogger(new Grpc.Core.Logging.ConsoleLogger());

            //setup MagicOnion and option.
            var service = MagicOnionEngine.BuildServerServiceDefinition(isReturnExceptionStackTraceInErrorDetail: true);

            //var service = MagicOnionEngine.BuildServerServiceDefinition(
            //               targetTypes: new[] { typeof(MyFirstService) },
            //               option: new MagicOnionOptions(isReturnExceptionStackTraceInErrorDetail: true));

            var server = new global::Grpc.Core.Server
            {
                Services = { service },
                Ports = { new ServerPort("localhost", 12345, ServerCredentials.Insecure) }
            };

            // launch gRPC Server.
            server.Start();

            // and wait.
            Console.ReadLine();
        }
    }
}
`

// Services.cs
`using System;
using MagicOnion;
using MagicOnion.Server;

namespace MagicServices
{
    // define interface as Server/Client IDL.
    // implements T : IService<T> and share this type between server and client.
    public interface IMyFirstService : IService<IMyFirstService>
    {
        UnaryResult<int> SumAsync(int x, int y);
    }
}
`

**Comment by MkazemAkhgary** [comment]
I had this question exactly! it's called MagicOnion for some reason 🤔

**Comment by neuecc** [comment]
released in 2.0.4.
