### ISSUE TITLE
integration with python example

### ISSUE THREAD

**Issue by BenDerPan** [Cysharp/MagicOnion#83]
Hi, if I write a server(write by C#)/client(write by python) with original grpc, can I use MagicOnion instead the server? can this work ? if it is possible, what should I do? thanks :)

**Comment by neuecc** [comment]
If python gRPC can change serializer to MsgPack may work.

**Comment by neuecc** [comment]
In addition, you can communicate usingHTTP/1 + JSON by using `MagicOnion.HttpGateway`.

**Comment by BenDerPan** [comment]
thanks ! Close this now.
