### ISSUE TITLE
Please update Nuget pacakges to use latest Grpc.Core

### ISSUE THREAD

**Issue by Noemata** [Cysharp/MagicOnion#84]
The version of Grpc.Core you are using does not support UWP server functionality.  The latest Grpc.Core 1.18.0 does support UWP as a server.  Please update your Nuget package to use the latest version of Grpc.Core.

**Comment by neuecc** [comment]
Currently 1.17.0 and 1.18.0 release notes does not mentioned about UWP https://github.com/grpc/grpc/releases/tag/v1.18.0
Where is the UWP support commitment?

and I've seen this gRPC issue
https://github.com/grpc/grpc/issues/8636

**Comment by Noemata** [comment]
I created UWP client/server console applications to facilitate quick testing.  Without the latest gRPC release, the server side never responds.  With the latest, 1.18.0 release, MagicOnion works quite nicely as a server running inside a UWP application.  Note that the usual limitations still apply, you cannot have a UWP application on the same device connect to a server instance that is running on that device.  I built MagicOnion from your master branch and pulled in Nuget packages for gRPC and MessagePack separately to get this working.  So if you incorporate the 1.18.0 version of gRPC into the MagicOnion Nuget package, server connections will be available for UWP.  If you'd like I can send you the UWP Console projects for testing (very handy).  You can also put these up as UWP samples, since they are much easier to understand than a conventional UWP application.

**Comment by neuecc** [comment]
In the next update, I will update gRPC version.
By the way, if update only gRPC version, does it work?

**Comment by Noemata** [comment]
Yes, updating just gRPC was all that is needed.

**Comment by neuecc** [comment]
ver 2.0.4 update it.
