### ISSUE TITLE
Already running .net 7 gRPC service is not working when upgraded to .net 8

### ISSUE THREAD

**Issue by cjmakwana** [Cysharp/MagicOnion#845]
Hello,

I am facing a weird issue. My production service, which is on .net 7 is reachable from other services in the cluster. However, the same service, when upgraded to .net 8, with the required other Nuget packages updated, doesn't work, as it is not reachable. The MagicOnion client throws the following exception:

Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler.")
   at MagicOnion.Client.ResponseContextRaw`2.FromRawResponseToResponseAsync()
   at MagicOnion.UnaryResult`1.UnwrapResponse()
   at .... (from the client code using MagicOnion)

**Comment by licentia88** [comment]
Hi, do you still have the same problem? to me it seems like your client. shared and server versions are different, also if you are using memory pack make sure its the compatible version.

**Comment by cjmakwana** [comment]
Hi @licentia88, sorry as I was on vacation. But thanks for asking. The issue is resolved. In fact, the root cause was in my code of DI container, which resulted in the gRPC error for each call.
