### ISSUE TITLE
Current version of MessagePack has vulnerability. 

### ISSUE THREAD

**Issue by VladimirRudt** [Cysharp/MagicOnion#867]
Hi guys, We are using MagicOnion in one of our projects and we encountered a problem.

The Mend.io diagnostic service has detected that we are using a vulnerable version of MessagePack. We don't use MessagePack directly, but MagicOnion (v6.1.5) does:

![image](https://github.com/user-attachments/assets/fb81ce4f-2127-4fc6-89e9-e00c1392f41c)

Link to vulnerability description: https://github.com/MessagePack-CSharp/MessagePack-CSharp/security/advisories/GHSA-4qm4-8hg2-g2xm

Do you plan to upgrade MessagePack to the patched version 2.5.187?

**Comment by mayuki** [comment]
Thank you for your feedback. We have released 6.1.6, which includes an update to MessagePack.
