### ISSUE TITLE
how to detect client grpexeception while grpServer close?

### ISSUE THREAD

**Issue by vivid216** [Cysharp/MagicOnion#88]
I am not familiar with grpc project,  I want use magicOnion in my program,  start a grpcServer and a grpClient in two different solution.  
1、while I force close grpServer application,  the connected client throw a system grpexception,  this exception may be catched in UnhandledException function, but not in service code,  could it  raise a ConnectionEvent in `StreamingHubClient`  and how catch disconnect exception ?   
2、i define a interface OssHub with a method FindAll(),   when `
 _OssHub = MagicOnion.Client.StreamingHubClient.Connect<IOssHub, IOssReceiver>(RpcChannel);
  var allcs = _OssHub.FindAll().Result;
  etc...
`
  sometimes call FindAll().Result cause a long time block or throw different exception，how to define a **timeout** in StreamingHubClient settings，when exceed timeout give a timeout exception.
thanks very much.

**Comment by neuecc** [comment]
disconnect event can receive via `StreamingHubClient.WaitForDisconnect()`.

currently streaminghubclient.method does not support timeout https://github.com/Cysharp/MagicOnion/issues/73
you can use old good Task.Delay timeout combination.

```csharp
var timeout = Task.Delay();
if((await Task.WhenAny(FindAll(), timeout)) == timeout)
{
    // timeout...
}
```
