### ISSUE TITLE
When used with class library importing shareditems, moc does not work properly.

### ISSUE THREAD

**Issue by mitchydeath** [Cysharp/MagicOnion#90]
If you set csproj of project which imported shareditems as input of moc, formatter is correctly generated.
However, if csproj that refers to the class library importing shareditems is set as input, no formatter is generated.

This is a sample project
https://github.com/mitchydeath/MagicOnionSharedProjectSample

**Comment by mitchydeath** [comment]
This is because AnalyzerManager can not resolve the project you are looking at.

For example, adding slnPath as an argument as below solves this problem
```
    internal static class RoslynExtensions
    {
        public static async Task<Compilation> GetCompilationFromProject(string slnPath, string csprojPath, params string[] preprocessorSymbols)
        {
            var analyzerOptions = new AnalyzerManagerOptions();

            var manager = new AnalyzerManager(slnPath);
            var projectAnalyzer = manager.GetProject(csprojPath); // addproj
            ...
```

However, since it will be hard to use, I do not want to add slnPath too much to the argument of moc.exe ...

**Comment by neuecc** [comment]
Sorry, I'll drop sharedproject supports.
