### ISSUE TITLE
Provide a simple readme and complete Sample

### ISSUE THREAD

**Issue by ZUOXIANGE** [Cysharp/MagicOnion#93]
This will make it easier to use,thanks

**Comment by Sajjad2678** [comment]
+1

**Comment by mingyangzhu** [comment]
+1

**Comment by neuecc** [comment]
Thank you for many votes:)
Okay, I'll try this weekend:)

**Comment by dulubi** [comment]
Hi @neuecc any luck with the more comprehensive readme and a complete sample?

This seems to be a very good engine but lack of documentation.

Thanks for sharing :)

**Comment by neuecc** [comment]
Thanks, yes, I must prepare quickly...
(sorry, I'm not good at write English so it takes time to get started)
I will definitely make it.

**Comment by Serepa** [comment]
+1

**Comment by Parfianovich** [comment]
+1

**Comment by neuecc** [comment]
Currently my company(Cysharp) is working to provide simple sample for sharing interface between server and unity.

**Comment by JauntyGame** [comment]
@neuecc sorry for pushing, can you provide info on how things with sample are going? Planning to make a cool game (idea came from anime Kakegurui). Find your framework really cool for making a backend. Thanks in advance!

**Comment by neuecc** [comment]
our team created simple unity chat app with messagepack code generation and using shared project.
it is done but should remove some japanese comment and more.
maybe publish end of this week.

**Comment by neuecc** [comment]
We've added Unity sample and ReadMe.
https://github.com/Cysharp/MagicOnion/tree/master/samples
