### ISSUE TITLE
Dependency injection feature when using IHostBuilder.UseMagicOnion(...) extensions

### ISSUE THREAD

**Issue by vova-lantsov-dev** [Cysharp/MagicOnion#95]
I've created the class which inherits from StreamingHubBase. As far as I know, gRPC server supports only parameterless constructors. Maybe it's a good idea to implement something like https://github.com/grpc/grpc/issues/12478#issuecomment-328555173 if it's possible. Thanks

**Comment by neuecc** [comment]
Yes, DI is the most propsed feature.
I'm now investigating and it can, please wait a moment.
https://github.com/Cysharp/MagicOnion/issues/64

**Comment by neuecc** [comment]
2.1.0 support it.
